package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author TheElk801
 */
public final class EdgeOfEternitiesCommander extends ExpansionSet {

    private static final EdgeOfEternitiesCommander instance = new EdgeOfEternitiesCommander();

    public static EdgeOfEternitiesCommander getInstance() {
        return instance;
    }

    private EdgeOfEternitiesCommander() {
        super("Edge of Eternities Commander", "EOC", ExpansionSet.buildDate(2025, 8, 1), SetType.SUPPLEMENTAL);
        this.hasBasicLands = false;

        cards.add(new SetCardInfo("Adarkar Wastes", 147, Rarity.RARE, mage.cards.a.AdarkarWastes.class));
        cards.add(new SetCardInfo("Aftermath Analyst", 91, Rarity.UNCOMMON, mage.cards.a.AftermathAnalyst.class));
        cards.add(new SetCardInfo("Alibou, Ancient Witness", 113, Rarity.MYTHIC, mage.cards.a.AlibouAncientWitness.class));
        cards.add(new SetCardInfo("Ancient Den", 148, Rarity.COMMON, mage.cards.a.AncientDen.class));
        cards.add(new SetCardInfo("Angel of the Ruins", 63, Rarity.RARE, mage.cards.a.AngelOfTheRuins.class));
        cards.add(new SetCardInfo("Arcane Signet", 53, Rarity.COMMON, mage.cards.a.ArcaneSignet.class));
        cards.add(new SetCardInfo("Astral Cornucopia", 131, Rarity.RARE, mage.cards.a.AstralCornucopia.class));
        cards.add(new SetCardInfo("Augur of Autumn", 92, Rarity.RARE, mage.cards.a.AugurOfAutumn.class));
        cards.add(new SetCardInfo("Baloth Prime", 13, Rarity.RARE, mage.cards.b.BalothPrime.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Baloth Prime", 33, Rarity.RARE, mage.cards.b.BalothPrime.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Battlefield Forge", 58, Rarity.RARE, mage.cards.b.BattlefieldForge.class));
        cards.add(new SetCardInfo("Beast Within", 93, Rarity.UNCOMMON, mage.cards.b.BeastWithin.class));
        cards.add(new SetCardInfo("Binding the Old Gods", 52, Rarity.UNCOMMON, mage.cards.b.BindingTheOldGods.class));
        cards.add(new SetCardInfo("Blasphemous Act", 86, Rarity.RARE, mage.cards.b.BlasphemousAct.class));
        cards.add(new SetCardInfo("Bojuka Bog", 149, Rarity.COMMON, mage.cards.b.BojukaBog.class));
        cards.add(new SetCardInfo("Braids, Arisen Nightmare", 82, Rarity.RARE, mage.cards.b.BraidsArisenNightmare.class));
        cards.add(new SetCardInfo("Buried Ruin", 150, Rarity.UNCOMMON, mage.cards.b.BuriedRuin.class));
        cards.add(new SetCardInfo("Cabaretti Courtyard", 151, Rarity.COMMON, mage.cards.c.CabarettiCourtyard.class));
        cards.add(new SetCardInfo("Canyon Slough", 152, Rarity.RARE, mage.cards.c.CanyonSlough.class));
        cards.add(new SetCardInfo("Cascade Bluffs", 153, Rarity.RARE, mage.cards.c.CascadeBluffs.class));
        cards.add(new SetCardInfo("Centaur Vinecrasher", 94, Rarity.RARE, mage.cards.c.CentaurVinecrasher.class));
        cards.add(new SetCardInfo("Chain Reaction", 87, Rarity.RARE, mage.cards.c.ChainReaction.class));
        cards.add(new SetCardInfo("Chaos Warp", 49, Rarity.RARE, mage.cards.c.ChaosWarp.class));
        cards.add(new SetCardInfo("Chrome Host Seedshark", 68, Rarity.RARE, mage.cards.c.ChromeHostSeedshark.class));
        cards.add(new SetCardInfo("Cinder Glade", 154, Rarity.RARE, mage.cards.c.CinderGlade.class));
        cards.add(new SetCardInfo("Clifftop Retreat", 155, Rarity.RARE, mage.cards.c.ClifftopRetreat.class));
        cards.add(new SetCardInfo("Cloud Key", 54, Rarity.RARE, mage.cards.c.CloudKey.class));
        cards.add(new SetCardInfo("Command Tower", 59, Rarity.COMMON, mage.cards.c.CommandTower.class));
        cards.add(new SetCardInfo("Coretapper", 132, Rarity.UNCOMMON, mage.cards.c.Coretapper.class));
        cards.add(new SetCardInfo("Crystalline Crawler", 133, Rarity.RARE, mage.cards.c.CrystallineCrawler.class));
        cards.add(new SetCardInfo("Cultivate", 95, Rarity.COMMON, mage.cards.c.Cultivate.class));
        cards.add(new SetCardInfo("Cyberdrive Awakener", 69, Rarity.RARE, mage.cards.c.CyberdriveAwakener.class));
        cards.add(new SetCardInfo("Dakmor Salvage", 156, Rarity.UNCOMMON, mage.cards.d.DakmorSalvage.class));
        cards.add(new SetCardInfo("Darksteel Reactor", 134, Rarity.RARE, mage.cards.d.DarksteelReactor.class));
        cards.add(new SetCardInfo("Deepglow Skate", 70, Rarity.RARE, mage.cards.d.DeepglowSkate.class));
        cards.add(new SetCardInfo("Depthshaker Titan", 29, Rarity.RARE, mage.cards.d.DepthshakerTitan.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Depthshaker Titan", 9, Rarity.RARE, mage.cards.d.DepthshakerTitan.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Dispatch", 64, Rarity.UNCOMMON, mage.cards.d.Dispatch.class));
        cards.add(new SetCardInfo("Empowered Autogenerator", 135, Rarity.RARE, mage.cards.e.EmpoweredAutogenerator.class));
        cards.add(new SetCardInfo("Emry, Lurker of the Loch", 71, Rarity.RARE, mage.cards.e.EmryLurkerOfTheLoch.class));
        cards.add(new SetCardInfo("Enthusiastic Mechanaut", 114, Rarity.UNCOMMON, mage.cards.e.EnthusiasticMechanaut.class));
        cards.add(new SetCardInfo("Escape Tunnel", 157, Rarity.COMMON, mage.cards.e.EscapeTunnel.class));
        cards.add(new SetCardInfo("Escape to the Wilds", 115, Rarity.RARE, mage.cards.e.EscapeToTheWilds.class));
        cards.add(new SetCardInfo("Etched Oracle", 136, Rarity.UNCOMMON, mage.cards.e.EtchedOracle.class));
        cards.add(new SetCardInfo("Etherium Sculptor", 72, Rarity.COMMON, mage.cards.e.EtheriumSculptor.class));
        cards.add(new SetCardInfo("Eumidian Hatchery", 20, Rarity.RARE, mage.cards.e.EumidianHatchery.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Eumidian Hatchery", 40, Rarity.RARE, mage.cards.e.EumidianHatchery.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Eumidian Wastewaker", 28, Rarity.RARE, mage.cards.e.EumidianWastewaker.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Eumidian Wastewaker", 8, Rarity.RARE, mage.cards.e.EumidianWastewaker.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Evendo Brushrazer", 10, Rarity.RARE, mage.cards.e.EvendoBrushrazer.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Evendo Brushrazer", 30, Rarity.RARE, mage.cards.e.EvendoBrushrazer.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Everflowing Chalice", 137, Rarity.UNCOMMON, mage.cards.e.EverflowingChalice.class));
        cards.add(new SetCardInfo("Evolving Wilds", 158, Rarity.COMMON, mage.cards.e.EvolvingWilds.class));
        cards.add(new SetCardInfo("Exotic Orchard", 159, Rarity.RARE, mage.cards.e.ExoticOrchard.class));
        cards.add(new SetCardInfo("Experimental Augury", 73, Rarity.COMMON, mage.cards.e.ExperimentalAugury.class));
        cards.add(new SetCardInfo("Exploration Broodship", 14, Rarity.RARE, mage.cards.e.ExplorationBroodship.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Exploration Broodship", 34, Rarity.RARE, mage.cards.e.ExplorationBroodship.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Fabled Passage", 60, Rarity.RARE, mage.cards.f.FabledPassage.class));
        cards.add(new SetCardInfo("Farseek", 50, Rarity.COMMON, mage.cards.f.Farseek.class));
        cards.add(new SetCardInfo("Festering Thicket", 21, Rarity.RARE, mage.cards.f.FesteringThicket.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Festering Thicket", 41, Rarity.RARE, mage.cards.f.FesteringThicket.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Formless Genesis", 96, Rarity.RARE, mage.cards.f.FormlessGenesis.class));
        cards.add(new SetCardInfo("Fumigate", 65, Rarity.RARE, mage.cards.f.Fumigate.class));
        cards.add(new SetCardInfo("Gavel of the Righteous", 55, Rarity.RARE, mage.cards.g.GavelOfTheRighteous.class));
        cards.add(new SetCardInfo("Gaze of Granite", 116, Rarity.RARE, mage.cards.g.GazeOfGranite.class));
        cards.add(new SetCardInfo("Glacial Fortress", 160, Rarity.RARE, mage.cards.g.GlacialFortress.class));
        cards.add(new SetCardInfo("Glittering Massif", 22, Rarity.RARE, mage.cards.g.GlitteringMassif.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Glittering Massif", 42, Rarity.RARE, mage.cards.g.GlitteringMassif.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("God-Eternal Bontu", 83, Rarity.MYTHIC, mage.cards.g.GodEternalBontu.class));
        cards.add(new SetCardInfo("Golem Foundry", 138, Rarity.COMMON, mage.cards.g.GolemFoundry.class));
        cards.add(new SetCardInfo("Great Furnace", 161, Rarity.COMMON, mage.cards.g.GreatFurnace.class));
        cards.add(new SetCardInfo("Groundskeeper", 97, Rarity.UNCOMMON, mage.cards.g.Groundskeeper.class));
        cards.add(new SetCardInfo("Hammer of Purphoros", 88, Rarity.RARE, mage.cards.h.HammerOfPurphoros.class));
        cards.add(new SetCardInfo("Hangarback Walker", 139, Rarity.RARE, mage.cards.h.HangarbackWalker.class));
        cards.add(new SetCardInfo("Harrow", 98, Rarity.COMMON, mage.cards.h.Harrow.class));
        cards.add(new SetCardInfo("Hearthhull, the Worldseed", 1, Rarity.MYTHIC, mage.cards.h.HearthhullTheWorldseed.class));
        cards.add(new SetCardInfo("Horizon Explorer", 15, Rarity.RARE, mage.cards.h.HorizonExplorer.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Horizon Explorer", 35, Rarity.RARE, mage.cards.h.HorizonExplorer.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Infernal Grasp", 84, Rarity.UNCOMMON, mage.cards.i.InfernalGrasp.class));
        cards.add(new SetCardInfo("Insight Engine", 26, Rarity.RARE, mage.cards.i.InsightEngine.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Insight Engine", 6, Rarity.RARE, mage.cards.i.InsightEngine.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Inspirit, Flagship Vessel", 2, Rarity.MYTHIC, mage.cards.i.InspiritFlagshipVessel.class));
        cards.add(new SetCardInfo("Irrigated Farmland", 162, Rarity.RARE, mage.cards.i.IrrigatedFarmland.class));
        cards.add(new SetCardInfo("Jhoira, Weatherlight Captain", 118, Rarity.RARE, mage.cards.j.JhoiraWeatherlightCaptain.class));
        cards.add(new SetCardInfo("Juri, Master of the Revue", 119, Rarity.UNCOMMON, mage.cards.j.JuriMasterOfTheRevue.class));
        cards.add(new SetCardInfo("Kappa Cannoneer", 74, Rarity.RARE, mage.cards.k.KappaCannoneer.class));
        cards.add(new SetCardInfo("Karn's Bastion", 163, Rarity.RARE, mage.cards.k.KarnsBastion.class));
        cards.add(new SetCardInfo("Karplusan Forest", 164, Rarity.RARE, mage.cards.k.KarplusanForest.class));
        cards.add(new SetCardInfo("Kilo, Apogee Mind", 3, Rarity.MYTHIC, mage.cards.k.KiloApogeeMind.class));
        cards.add(new SetCardInfo("Korvold, Fae-Cursed King", 120, Rarity.MYTHIC, mage.cards.k.KorvoldFaeCursedKing.class));
        cards.add(new SetCardInfo("Llanowar Wastes", 165, Rarity.RARE, mage.cards.l.LlanowarWastes.class));
        cards.add(new SetCardInfo("Loamcrafter Faun", 99, Rarity.RARE, mage.cards.l.LoamcrafterFaun.class));
        cards.add(new SetCardInfo("Lonely Sandbar", 166, Rarity.COMMON, mage.cards.l.LonelySandbar.class));
        cards.add(new SetCardInfo("Long-Range Sensor", 11, Rarity.RARE, mage.cards.l.LongRangeSensor.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Long-Range Sensor", 31, Rarity.RARE, mage.cards.l.LongRangeSensor.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Lux Artillery", 140, Rarity.RARE, mage.cards.l.LuxArtillery.class));
        cards.add(new SetCardInfo("Lux Cannon", 141, Rarity.RARE, mage.cards.l.LuxCannon.class));
        cards.add(new SetCardInfo("Maestros Theater", 167, Rarity.COMMON, mage.cards.m.MaestrosTheater.class));
        cards.add(new SetCardInfo("Mayhem Devil", 121, Rarity.UNCOMMON, mage.cards.m.MayhemDevil.class));
        cards.add(new SetCardInfo("Mazirek, Kraul Death Priest", 122, Rarity.RARE, mage.cards.m.MazirekKraulDeathPriest.class));
        cards.add(new SetCardInfo("Mindless Automaton", 142, Rarity.UNCOMMON, mage.cards.m.MindlessAutomaton.class));
        cards.add(new SetCardInfo("Moraug, Fury of Akoum", 89, Rarity.MYTHIC, mage.cards.m.MoraugFuryOfAkoum.class));
        cards.add(new SetCardInfo("Mountain Valley", 61, Rarity.UNCOMMON, mage.cards.m.MountainValley.class));
        cards.add(new SetCardInfo("Moxite Refinery", 17, Rarity.RARE, mage.cards.m.MoxiteRefinery.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Moxite Refinery", 37, Rarity.RARE, mage.cards.m.MoxiteRefinery.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Multani, Yavimaya's Avatar", 100, Rarity.MYTHIC, mage.cards.m.MultaniYavimayasAvatar.class));
        cards.add(new SetCardInfo("Myriad Landscape", 169, Rarity.UNCOMMON, mage.cards.m.MyriadLandscape.class));
        cards.add(new SetCardInfo("Mystic Monastery", 170, Rarity.UNCOMMON, mage.cards.m.MysticMonastery.class));
        cards.add(new SetCardInfo("Nature's Lore", 101, Rarity.UNCOMMON, mage.cards.n.NaturesLore.class));
        cards.add(new SetCardInfo("Night's Whisper", 85, Rarity.COMMON, mage.cards.n.NightsWhisper.class));
        cards.add(new SetCardInfo("Omnath, Locus of Rage", 123, Rarity.MYTHIC, mage.cards.o.OmnathLocusOfRage.class));
        cards.add(new SetCardInfo("Oracle of Mul Daya", 102, Rarity.RARE, mage.cards.o.OracleOfMulDaya.class));
        cards.add(new SetCardInfo("Organic Extinction", 66, Rarity.RARE, mage.cards.o.OrganicExtinction.class));
        cards.add(new SetCardInfo("Patrolling Peacemaker", 25, Rarity.RARE, mage.cards.p.PatrollingPeacemaker.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Patrolling Peacemaker", 5, Rarity.RARE, mage.cards.p.PatrollingPeacemaker.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Pentad Prism", 56, Rarity.UNCOMMON, mage.cards.p.PentadPrism.class));
        cards.add(new SetCardInfo("Pest Infestation", 103, Rarity.RARE, mage.cards.p.PestInfestation.class));
        cards.add(new SetCardInfo("Phyrexian Metamorph", 75, Rarity.RARE, mage.cards.p.PhyrexianMetamorph.class));
        cards.add(new SetCardInfo("Planetary Annihilation", 12, Rarity.RARE, mage.cards.p.PlanetaryAnnihilation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Planetary Annihilation", 32, Rarity.RARE, mage.cards.p.PlanetaryAnnihilation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Pull from Tomorrow", 76, Rarity.RARE, mage.cards.p.PullFromTomorrow.class));
        cards.add(new SetCardInfo("Putrefy", 124, Rarity.UNCOMMON, mage.cards.p.Putrefy.class));
        cards.add(new SetCardInfo("Radiant Summit", 23, Rarity.RARE, mage.cards.r.RadiantSummit.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Radiant Summit", 43, Rarity.RARE, mage.cards.r.RadiantSummit.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Rakdos Charm", 125, Rarity.UNCOMMON, mage.cards.r.RakdosCharm.class));
        cards.add(new SetCardInfo("Rampaging Baloths", 104, Rarity.RARE, mage.cards.r.RampagingBaloths.class));
        cards.add(new SetCardInfo("Razortide Bridge", 171, Rarity.COMMON, mage.cards.r.RazortideBridge.class));
        cards.add(new SetCardInfo("Resourceful Defense", 67, Rarity.RARE, mage.cards.r.ResourcefulDefense.class));
        cards.add(new SetCardInfo("Ripples of Potential", 77, Rarity.RARE, mage.cards.r.RipplesOfPotential.class));
        cards.add(new SetCardInfo("Riveteers Overlook", 172, Rarity.COMMON, mage.cards.r.RiveteersOverlook.class));
        cards.add(new SetCardInfo("Rocky Tar Pit", 173, Rarity.UNCOMMON, mage.cards.r.RockyTarPit.class));
        cards.add(new SetCardInfo("Roiling Regrowth", 105, Rarity.UNCOMMON, mage.cards.r.RoilingRegrowth.class));
        cards.add(new SetCardInfo("Rugged Prairie", 174, Rarity.RARE, mage.cards.r.RuggedPrairie.class));
        cards.add(new SetCardInfo("Rustvale Bridge", 175, Rarity.COMMON, mage.cards.r.RustvaleBridge.class));
        cards.add(new SetCardInfo("Satyr Wayfinder", 106, Rarity.COMMON, mage.cards.s.SatyrWayfinder.class));
        cards.add(new SetCardInfo("Scouring Swarm", 16, Rarity.RARE, mage.cards.s.ScouringSwarm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Scouring Swarm", 36, Rarity.RARE, mage.cards.s.ScouringSwarm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Seat of the Synod", 176, Rarity.COMMON, mage.cards.s.SeatOfTheSynod.class));
        cards.add(new SetCardInfo("Secluded Steppe", 177, Rarity.COMMON, mage.cards.s.SecludedSteppe.class));
        cards.add(new SetCardInfo("Sheltered Thicket", 178, Rarity.RARE, mage.cards.s.ShelteredThicket.class));
        cards.add(new SetCardInfo("Shivan Reef", 179, Rarity.RARE, mage.cards.s.ShivanReef.class));
        cards.add(new SetCardInfo("Silverbluff Bridge", 180, Rarity.COMMON, mage.cards.s.SilverbluffBridge.class));
        cards.add(new SetCardInfo("Skycloud Expanse", 181, Rarity.RARE, mage.cards.s.SkycloudExpanse.class));
        cards.add(new SetCardInfo("Skyshroud Claim", 107, Rarity.COMMON, mage.cards.s.SkyshroudClaim.class));
        cards.add(new SetCardInfo("Smoldering Marsh", 182, Rarity.RARE, mage.cards.s.SmolderingMarsh.class));
        cards.add(new SetCardInfo("Sol Ring", 57, Rarity.UNCOMMON, mage.cards.s.SolRing.class));
        cards.add(new SetCardInfo("Solar Array", 18, Rarity.RARE, mage.cards.s.SolarArray.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Solar Array", 38, Rarity.RARE, mage.cards.s.SolarArray.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Soul of Windgrace", 126, Rarity.MYTHIC, mage.cards.s.SoulOfWindgrace.class));
        cards.add(new SetCardInfo("Soul-Guide Lantern", 143, Rarity.UNCOMMON, mage.cards.s.SoulGuideLantern.class));
        cards.add(new SetCardInfo("Spire of Industry", 183, Rarity.RARE, mage.cards.s.SpireOfIndustry.class));
        cards.add(new SetCardInfo("Splendid Reclamation", 108, Rarity.RARE, mage.cards.s.SplendidReclamation.class));
        cards.add(new SetCardInfo("Springbloom Druid", 51, Rarity.COMMON, mage.cards.s.SpringbloomDruid.class));
        cards.add(new SetCardInfo("Sprouting Goblin", 90, Rarity.UNCOMMON, mage.cards.s.SproutingGoblin.class));
        cards.add(new SetCardInfo("Steel Overseer", 144, Rarity.RARE, mage.cards.s.SteelOverseer.class));
        cards.add(new SetCardInfo("Sulfur Falls", 184, Rarity.RARE, mage.cards.s.SulfurFalls.class));
        cards.add(new SetCardInfo("Sulfurous Springs", 185, Rarity.RARE, mage.cards.s.SulfurousSprings.class));
        cards.add(new SetCardInfo("Surge Conductor", 19, Rarity.RARE, mage.cards.s.SurgeConductor.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Surge Conductor", 39, Rarity.RARE, mage.cards.s.SurgeConductor.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swan Song", 46, Rarity.RARE, mage.cards.s.SwanSong.class));
        cards.add(new SetCardInfo("Swords to Plowshares", 45, Rarity.UNCOMMON, mage.cards.s.SwordsToPlowshares.class));
        cards.add(new SetCardInfo("Szarel, Genesis Shepherd", 4, Rarity.MYTHIC, mage.cards.s.SzarelGenesisShepherd.class));
        cards.add(new SetCardInfo("Tear Asunder", 109, Rarity.UNCOMMON, mage.cards.t.TearAsunder.class));
        cards.add(new SetCardInfo("Tekuthal, Inquiry Dominus", 78, Rarity.MYTHIC, mage.cards.t.TekuthalInquiryDominus.class));
        cards.add(new SetCardInfo("Temple of Enlightenment", 186, Rarity.RARE, mage.cards.t.TempleOfEnlightenment.class));
        cards.add(new SetCardInfo("Temple of Epiphany", 187, Rarity.RARE, mage.cards.t.TempleOfEpiphany.class));
        cards.add(new SetCardInfo("Temple of Triumph", 188, Rarity.RARE, mage.cards.t.TempleOfTriumph.class));
        cards.add(new SetCardInfo("Terramorphic Expanse", 62, Rarity.COMMON, mage.cards.t.TerramorphicExpanse.class));
        cards.add(new SetCardInfo("Tezzeret's Gambit", 47, Rarity.UNCOMMON, mage.cards.t.TezzeretsGambit.class));
        cards.add(new SetCardInfo("The Gitrog Monster", 117, Rarity.MYTHIC, mage.cards.t.TheGitrogMonster.class));
        cards.add(new SetCardInfo("The Mycosynth Gardens", 168, Rarity.RARE, mage.cards.t.TheMycosynthGardens.class));
        cards.add(new SetCardInfo("Thirst for Knowledge", 48, Rarity.UNCOMMON, mage.cards.t.ThirstForKnowledge.class));
        cards.add(new SetCardInfo("Thought Monitor", 79, Rarity.RARE, mage.cards.t.ThoughtMonitor.class));
        cards.add(new SetCardInfo("Threefold Thunderhulk", 145, Rarity.RARE, mage.cards.t.ThreefoldThunderhulk.class));
        cards.add(new SetCardInfo("Thrummingbird", 80, Rarity.UNCOMMON, mage.cards.t.Thrummingbird.class));
        cards.add(new SetCardInfo("Tireless Tracker", 110, Rarity.RARE, mage.cards.t.TirelessTracker.class));
        cards.add(new SetCardInfo("Titan Forge", 146, Rarity.RARE, mage.cards.t.TitanForge.class));
        cards.add(new SetCardInfo("Titania, Protector of Argoth", 111, Rarity.MYTHIC, mage.cards.t.TitaniaProtectorOfArgoth.class));
        cards.add(new SetCardInfo("Twilight Mire", 189, Rarity.RARE, mage.cards.t.TwilightMire.class));
        cards.add(new SetCardInfo("Universal Surveillance", 81, Rarity.RARE, mage.cards.u.UniversalSurveillance.class));
        cards.add(new SetCardInfo("Uthros Research Craft", 27, Rarity.RARE, mage.cards.u.UthrosResearchCraft.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Uthros Research Craft", 7, Rarity.RARE, mage.cards.u.UthrosResearchCraft.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Uurg, Spawn of Turg", 127, Rarity.UNCOMMON, mage.cards.u.UurgSpawnOfTurg.class));
        cards.add(new SetCardInfo("Vernal Fen", 24, Rarity.RARE, mage.cards.v.VernalFen.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Vernal Fen", 44, Rarity.RARE, mage.cards.v.VernalFen.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Viridescent Bog", 190, Rarity.RARE, mage.cards.v.ViridescentBog.class));
        cards.add(new SetCardInfo("Wake the Past", 128, Rarity.RARE, mage.cards.w.WakeThePast.class));
        cards.add(new SetCardInfo("Wastes", 191, Rarity.COMMON, mage.cards.w.Wastes.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Windgrace's Judgment", 129, Rarity.RARE, mage.cards.w.WindgracesJudgment.class));
        cards.add(new SetCardInfo("World Breaker", 112, Rarity.MYTHIC, mage.cards.w.WorldBreaker.class));
        cards.add(new SetCardInfo("Worldsoul's Rage", 130, Rarity.RARE, mage.cards.w.WorldsoulsRage.class));
    }
}
