package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author North
 */
public final class Homelands extends ExpansionSet {

    private static final Homelands instance = new Homelands();

    public static Homelands getInstance() {
        return instance;
    }

    private Homelands() {
        super("Homelands", "HML", ExpansionSet.buildDate(1995, 9, 1), SetType.EXPANSION);
        this.hasBasicLands = false;
        this.hasBoosters = true;
        this.numBoosterLands = 1;
        this.numBoosterCommon = 10;
        this.numBoosterUncommon = 3;
        this.numBoosterRare = 1;
        this.ratioBoosterMythic = 0;

        cards.add(new SetCardInfo("Abbey Gargoyles", 1, Rarity.UNCOMMON, mage.cards.a.AbbeyGargoyles.class, RETRO_ART));
        cards.add(new SetCardInfo("Abbey Matron", "2a", Rarity.COMMON, mage.cards.a.AbbeyMatron.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Abbey Matron", "2b", Rarity.COMMON, mage.cards.a.AbbeyMatron.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Aether Storm", 21, Rarity.UNCOMMON, mage.cards.a.AetherStorm.class, RETRO_ART));
        cards.add(new SetCardInfo("Aliban's Tower", "61a", Rarity.COMMON, mage.cards.a.AlibansTower.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Aliban's Tower", "61b", Rarity.COMMON, mage.cards.a.AlibansTower.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ambush", 62, Rarity.COMMON, mage.cards.a.Ambush.class, RETRO_ART));
        cards.add(new SetCardInfo("Ambush Party", "63a", Rarity.COMMON, mage.cards.a.AmbushParty.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ambush Party", "63b", Rarity.COMMON, mage.cards.a.AmbushParty.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("An-Havva Constable", 81, Rarity.RARE, mage.cards.a.AnHavvaConstable.class, RETRO_ART));
        cards.add(new SetCardInfo("An-Havva Inn", 82, Rarity.UNCOMMON, mage.cards.a.AnHavvaInn.class, RETRO_ART));
        cards.add(new SetCardInfo("An-Havva Township", 111, Rarity.UNCOMMON, mage.cards.a.AnHavvaTownship.class, RETRO_ART));
        cards.add(new SetCardInfo("An-Zerrin Ruins", 64, Rarity.RARE, mage.cards.a.AnZerrinRuins.class, RETRO_ART));
        cards.add(new SetCardInfo("Anaba Ancestor", 65, Rarity.RARE, mage.cards.a.AnabaAncestor.class, RETRO_ART));
        cards.add(new SetCardInfo("Anaba Bodyguard", "66a", Rarity.COMMON, mage.cards.a.AnabaBodyguard.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Anaba Bodyguard", "66b", Rarity.COMMON, mage.cards.a.AnabaBodyguard.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Anaba Shaman", "67a", Rarity.COMMON, mage.cards.a.AnabaShaman.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Anaba Shaman", "67b", Rarity.COMMON, mage.cards.a.AnabaShaman.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Anaba Spirit Crafter", 68, Rarity.RARE, mage.cards.a.AnabaSpiritCrafter.class, RETRO_ART));
        cards.add(new SetCardInfo("Apocalypse Chime", 101, Rarity.RARE, mage.cards.a.ApocalypseChime.class, RETRO_ART));
        cards.add(new SetCardInfo("Autumn Willow", 83, Rarity.RARE, mage.cards.a.AutumnWillow.class, RETRO_ART));
        cards.add(new SetCardInfo("Aysen Abbey", 112, Rarity.UNCOMMON, mage.cards.a.AysenAbbey.class, RETRO_ART));
        cards.add(new SetCardInfo("Aysen Bureaucrats", "3a", Rarity.COMMON, mage.cards.a.AysenBureaucrats.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Aysen Bureaucrats", "3b", Rarity.COMMON, mage.cards.a.AysenBureaucrats.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Aysen Crusader", 4, Rarity.RARE, mage.cards.a.AysenCrusader.class, RETRO_ART));
        cards.add(new SetCardInfo("Aysen Highway", 5, Rarity.RARE, mage.cards.a.AysenHighway.class, RETRO_ART));
        cards.add(new SetCardInfo("Baki's Curse", 22, Rarity.RARE, mage.cards.b.BakisCurse.class, RETRO_ART));
        cards.add(new SetCardInfo("Baron Sengir", 41, Rarity.RARE, mage.cards.b.BaronSengir.class, RETRO_ART));
        cards.add(new SetCardInfo("Beast Walkers", 6, Rarity.RARE, mage.cards.b.BeastWalkers.class, RETRO_ART));
        cards.add(new SetCardInfo("Black Carriage", 42, Rarity.RARE, mage.cards.b.BlackCarriage.class, RETRO_ART));
        cards.add(new SetCardInfo("Broken Visage", 43, Rarity.RARE, mage.cards.b.BrokenVisage.class, RETRO_ART));
        cards.add(new SetCardInfo("Carapace", "84a", Rarity.COMMON, mage.cards.c.Carapace.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Carapace", "84b", Rarity.COMMON, mage.cards.c.Carapace.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Castle Sengir", 113, Rarity.UNCOMMON, mage.cards.c.CastleSengir.class, RETRO_ART));
        cards.add(new SetCardInfo("Cemetery Gate", "44a", Rarity.COMMON, mage.cards.c.CemeteryGate.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cemetery Gate", "44b", Rarity.COMMON, mage.cards.c.CemeteryGate.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chain Stasis", 23, Rarity.RARE, mage.cards.c.ChainStasis.class, RETRO_ART));
        cards.add(new SetCardInfo("Chandler", 69, Rarity.COMMON, mage.cards.c.Chandler.class, RETRO_ART));
        cards.add(new SetCardInfo("Clockwork Gnomes", 102, Rarity.COMMON, mage.cards.c.ClockworkGnomes.class, RETRO_ART));
        cards.add(new SetCardInfo("Clockwork Steed", 103, Rarity.COMMON, mage.cards.c.ClockworkSteed.class, RETRO_ART));
        cards.add(new SetCardInfo("Clockwork Swarm", 104, Rarity.COMMON, mage.cards.c.ClockworkSwarm.class, RETRO_ART));
        cards.add(new SetCardInfo("Coral Reef", 24, Rarity.COMMON, mage.cards.c.CoralReef.class, RETRO_ART));
        cards.add(new SetCardInfo("Dark Maze", "25a", Rarity.COMMON, mage.cards.d.DarkMaze.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dark Maze", "25b", Rarity.COMMON, mage.cards.d.DarkMaze.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Daughter of Autumn", 85, Rarity.RARE, mage.cards.d.DaughterOfAutumn.class, RETRO_ART));
        cards.add(new SetCardInfo("Death Speakers", 7, Rarity.UNCOMMON, mage.cards.d.DeathSpeakers.class, RETRO_ART));
        cards.add(new SetCardInfo("Didgeridoo", 105, Rarity.RARE, mage.cards.d.Didgeridoo.class, RETRO_ART));
        cards.add(new SetCardInfo("Drudge Spell", 45, Rarity.UNCOMMON, mage.cards.d.DrudgeSpell.class, RETRO_ART));
        cards.add(new SetCardInfo("Dry Spell", "46a", Rarity.COMMON, mage.cards.d.DrySpell.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dry Spell", "46b", Rarity.COMMON, mage.cards.d.DrySpell.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dwarven Pony", 70, Rarity.RARE, mage.cards.d.DwarvenPony.class, RETRO_ART));
        cards.add(new SetCardInfo("Dwarven Sea Clan", 71, Rarity.RARE, mage.cards.d.DwarvenSeaClan.class, RETRO_ART));
        cards.add(new SetCardInfo("Dwarven Trader", "72a", Rarity.COMMON, mage.cards.d.DwarvenTrader.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dwarven Trader", "72b", Rarity.COMMON, mage.cards.d.DwarvenTrader.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ebony Rhino", 106, Rarity.COMMON, mage.cards.e.EbonyRhino.class, RETRO_ART));
        cards.add(new SetCardInfo("Eron the Relentless", 73, Rarity.UNCOMMON, mage.cards.e.EronTheRelentless.class, RETRO_ART));
        cards.add(new SetCardInfo("Evaporate", 74, Rarity.UNCOMMON, mage.cards.e.Evaporate.class, RETRO_ART));
        cards.add(new SetCardInfo("Faerie Noble", 86, Rarity.RARE, mage.cards.f.FaerieNoble.class, RETRO_ART));
        cards.add(new SetCardInfo("Feast of the Unicorn", "47a", Rarity.COMMON, mage.cards.f.FeastOfTheUnicorn.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Feast of the Unicorn", "47b", Rarity.COMMON, mage.cards.f.FeastOfTheUnicorn.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Feroz's Ban", 107, Rarity.RARE, mage.cards.f.FerozsBan.class, RETRO_ART));
        cards.add(new SetCardInfo("Folk of An-Havva", "87a", Rarity.COMMON, mage.cards.f.FolkOfAnHavva.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Folk of An-Havva", "87b", Rarity.COMMON, mage.cards.f.FolkOfAnHavva.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Forget", 26, Rarity.RARE, mage.cards.f.Forget.class, RETRO_ART));
        cards.add(new SetCardInfo("Funeral March", 48, Rarity.COMMON, mage.cards.f.FuneralMarch.class, RETRO_ART));
        cards.add(new SetCardInfo("Ghost Hounds", 49, Rarity.UNCOMMON, mage.cards.g.GhostHounds.class, RETRO_ART));
        cards.add(new SetCardInfo("Giant Albatross", "27a", Rarity.COMMON, mage.cards.g.GiantAlbatross.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Giant Albatross", "27b", Rarity.COMMON, mage.cards.g.GiantAlbatross.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Giant Oyster", 28, Rarity.UNCOMMON, mage.cards.g.GiantOyster.class, RETRO_ART));
        cards.add(new SetCardInfo("Grandmother Sengir", 50, Rarity.RARE, mage.cards.g.GrandmotherSengir.class, RETRO_ART));
        cards.add(new SetCardInfo("Greater Werewolf", 51, Rarity.COMMON, mage.cards.g.GreaterWerewolf.class, RETRO_ART));
        cards.add(new SetCardInfo("Hazduhr the Abbot", 8, Rarity.RARE, mage.cards.h.HazduhrTheAbbot.class, RETRO_ART));
        cards.add(new SetCardInfo("Headstone", 52, Rarity.COMMON, mage.cards.h.Headstone.class, RETRO_ART));
        cards.add(new SetCardInfo("Heart Wolf", 75, Rarity.RARE, mage.cards.h.HeartWolf.class, RETRO_ART));
        cards.add(new SetCardInfo("Hungry Mist", "88a", Rarity.COMMON, mage.cards.h.HungryMist.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Hungry Mist", "88b", Rarity.COMMON, mage.cards.h.HungryMist.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ihsan's Shade", 53, Rarity.UNCOMMON, mage.cards.i.IhsansShade.class, RETRO_ART));
        cards.add(new SetCardInfo("Irini Sengir", 54, Rarity.UNCOMMON, mage.cards.i.IriniSengir.class, RETRO_ART));
        cards.add(new SetCardInfo("Ironclaw Curse", 76, Rarity.RARE, mage.cards.i.IronclawCurse.class, RETRO_ART));
        cards.add(new SetCardInfo("Jinx", 29, Rarity.COMMON, mage.cards.j.Jinx.class, RETRO_ART));
        cards.add(new SetCardInfo("Joven", 77, Rarity.COMMON, mage.cards.j.Joven.class, RETRO_ART));
        cards.add(new SetCardInfo("Joven's Ferrets", 89, Rarity.COMMON, mage.cards.j.JovensFerrets.class, RETRO_ART));
        cards.add(new SetCardInfo("Joven's Tools", 108, Rarity.UNCOMMON, mage.cards.j.JovensTools.class, RETRO_ART));
        cards.add(new SetCardInfo("Koskun Falls", 55, Rarity.RARE, mage.cards.k.KoskunFalls.class, RETRO_ART));
        cards.add(new SetCardInfo("Koskun Keep", 114, Rarity.UNCOMMON, mage.cards.k.KoskunKeep.class, RETRO_ART));
        cards.add(new SetCardInfo("Labyrinth Minotaur", "30a", Rarity.COMMON, mage.cards.l.LabyrinthMinotaur.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Labyrinth Minotaur", "30b", Rarity.COMMON, mage.cards.l.LabyrinthMinotaur.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Leaping Lizard", 90, Rarity.COMMON, mage.cards.l.LeapingLizard.class, RETRO_ART));
        cards.add(new SetCardInfo("Leeches", 9, Rarity.RARE, mage.cards.l.Leeches.class, RETRO_ART));
        cards.add(new SetCardInfo("Mammoth Harness", 91, Rarity.RARE, mage.cards.m.MammothHarness.class, RETRO_ART));
        cards.add(new SetCardInfo("Marjhan", 31, Rarity.RARE, mage.cards.m.Marjhan.class, RETRO_ART));
        cards.add(new SetCardInfo("Memory Lapse", "32a", Rarity.COMMON, mage.cards.m.MemoryLapse.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Memory Lapse", "32b", Rarity.COMMON, mage.cards.m.MemoryLapse.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Merchant Scroll", 33, Rarity.COMMON, mage.cards.m.MerchantScroll.class, RETRO_ART));
        cards.add(new SetCardInfo("Mesa Falcon", "10a", Rarity.COMMON, mage.cards.m.MesaFalcon.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mesa Falcon", "10b", Rarity.COMMON, mage.cards.m.MesaFalcon.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mystic Decree", 34, Rarity.RARE, mage.cards.m.MysticDecree.class, RETRO_ART));
        cards.add(new SetCardInfo("Narwhal", 35, Rarity.RARE, mage.cards.n.Narwhal.class, RETRO_ART));
        cards.add(new SetCardInfo("Orcish Mine", 78, Rarity.UNCOMMON, mage.cards.o.OrcishMine.class, RETRO_ART));
        cards.add(new SetCardInfo("Primal Order", 92, Rarity.RARE, mage.cards.p.PrimalOrder.class, RETRO_ART));
        cards.add(new SetCardInfo("Prophecy", 11, Rarity.COMMON, mage.cards.p.Prophecy.class, RETRO_ART));
        cards.add(new SetCardInfo("Rashka the Slayer", 12, Rarity.UNCOMMON, mage.cards.r.RashkaTheSlayer.class, RETRO_ART));
        cards.add(new SetCardInfo("Reef Pirates", "36a", Rarity.COMMON, mage.cards.r.ReefPirates.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Reef Pirates", "36b", Rarity.COMMON, mage.cards.r.ReefPirates.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Renewal", 93, Rarity.COMMON, mage.cards.r.Renewal.class, RETRO_ART));
        cards.add(new SetCardInfo("Retribution", 79, Rarity.UNCOMMON, mage.cards.r.Retribution.class, RETRO_ART));
        cards.add(new SetCardInfo("Reveka, Wizard Savant", 37, Rarity.RARE, mage.cards.r.RevekaWizardSavant.class, RETRO_ART));
        cards.add(new SetCardInfo("Root Spider", 94, Rarity.UNCOMMON, mage.cards.r.RootSpider.class, RETRO_ART));
        cards.add(new SetCardInfo("Roots", 95, Rarity.UNCOMMON, mage.cards.r.Roots.class, RETRO_ART));
        cards.add(new SetCardInfo("Roterothopter", 109, Rarity.COMMON, mage.cards.r.Roterothopter.class, RETRO_ART));
        cards.add(new SetCardInfo("Rysorian Badger", 96, Rarity.RARE, mage.cards.r.RysorianBadger.class, RETRO_ART));
        cards.add(new SetCardInfo("Samite Alchemist", "13a", Rarity.COMMON, mage.cards.s.SamiteAlchemist.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Samite Alchemist", "13b", Rarity.COMMON, mage.cards.s.SamiteAlchemist.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Sea Sprite", 38, Rarity.UNCOMMON, mage.cards.s.SeaSprite.class, RETRO_ART));
        cards.add(new SetCardInfo("Sea Troll", 39, Rarity.UNCOMMON, mage.cards.s.SeaTroll.class, RETRO_ART));
        cards.add(new SetCardInfo("Sengir Autocrat", 56, Rarity.UNCOMMON, mage.cards.s.SengirAutocrat.class, RETRO_ART));
        cards.add(new SetCardInfo("Sengir Bats", "57a", Rarity.COMMON, mage.cards.s.SengirBats.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Sengir Bats", "57b", Rarity.COMMON, mage.cards.s.SengirBats.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Serra Aviary", 14, Rarity.RARE, mage.cards.s.SerraAviary.class, RETRO_ART));
        cards.add(new SetCardInfo("Serra Bestiary", 15, Rarity.COMMON, mage.cards.s.SerraBestiary.class, RETRO_ART));
        cards.add(new SetCardInfo("Serra Inquisitors", 16, Rarity.UNCOMMON, mage.cards.s.SerraInquisitors.class, RETRO_ART));
        cards.add(new SetCardInfo("Serra Paladin", 17, Rarity.COMMON, mage.cards.s.SerraPaladin.class, RETRO_ART));
        cards.add(new SetCardInfo("Serrated Arrows", 110, Rarity.COMMON, mage.cards.s.SerratedArrows.class, RETRO_ART));
        cards.add(new SetCardInfo("Shrink", "97a", Rarity.COMMON, mage.cards.s.Shrink.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Shrink", "97b", Rarity.COMMON, mage.cards.s.Shrink.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Soraya the Falconer", 18, Rarity.RARE, mage.cards.s.SorayaTheFalconer.class, RETRO_ART));
        cards.add(new SetCardInfo("Spectral Bears", 98, Rarity.UNCOMMON, mage.cards.s.SpectralBears.class, RETRO_ART));
        cards.add(new SetCardInfo("Torture", "59a", Rarity.COMMON, mage.cards.t.Torture.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Torture", "59b", Rarity.COMMON, mage.cards.t.Torture.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Trade Caravan", "19a", Rarity.COMMON, mage.cards.t.TradeCaravan.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Trade Caravan", "19b", Rarity.COMMON, mage.cards.t.TradeCaravan.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Truce", 20, Rarity.RARE, mage.cards.t.Truce.class, RETRO_ART));
        cards.add(new SetCardInfo("Veldrane of Sengir", 60, Rarity.RARE, mage.cards.v.VeldraneOfSengir.class, RETRO_ART));
        cards.add(new SetCardInfo("Wall of Kelp", 40, Rarity.RARE, mage.cards.w.WallOfKelp.class, RETRO_ART));
        cards.add(new SetCardInfo("Willow Faerie", "99a", Rarity.COMMON, mage.cards.w.WillowFaerie.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Willow Faerie", "99b", Rarity.COMMON, mage.cards.w.WillowFaerie.class, RETRO_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Willow Priestess", 100, Rarity.RARE, mage.cards.w.WillowPriestess.class, RETRO_ART));
        cards.add(new SetCardInfo("Winter Sky", 80, Rarity.RARE, mage.cards.w.WinterSky.class, RETRO_ART));
        cards.add(new SetCardInfo("Wizards' School", 115, Rarity.UNCOMMON, mage.cards.w.WizardsSchool.class, RETRO_ART));
    }
}
