package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author TheElk801
 */
public final class LorwynEclipsedCommander extends ExpansionSet {

    private static final LorwynEclipsedCommander instance = new LorwynEclipsedCommander();

    public static LorwynEclipsedCommander getInstance() {
        return instance;
    }

    private LorwynEclipsedCommander() {
        super("Lorwyn Eclipsed Commander", "ECC", ExpansionSet.buildDate(2026, 1, 23), SetType.SUPPLEMENTAL);
        this.hasBasicLands = false; // temporary

        cards.add(new SetCardInfo("Abundant Countryside", 22, Rarity.RARE, mage.cards.a.AbundantCountryside.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Abundant Countryside", 42, Rarity.RARE, mage.cards.a.AbundantCountryside.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Abundant Growth", 97, Rarity.COMMON, mage.cards.a.AbundantGrowth.class));
        cards.add(new SetCardInfo("Ancient Ziggurat", 144, Rarity.UNCOMMON, mage.cards.a.AncientZiggurat.class));
        cards.add(new SetCardInfo("Arcane Signet", 55, Rarity.UNCOMMON, mage.cards.a.ArcaneSignet.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Arcane Signet", 56, Rarity.UNCOMMON, mage.cards.a.ArcaneSignet.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Archfiend of Ifnir", 70, Rarity.RARE, mage.cards.a.ArchfiendOfIfnir.class));
        cards.add(new SetCardInfo("Assassin's Trophy", 119, Rarity.RARE, mage.cards.a.AssassinsTrophy.class));
        cards.add(new SetCardInfo("Auntie Ool, Cursewretch", 2, Rarity.MYTHIC, mage.cards.a.AuntieOolCursewretch.class));
        cards.add(new SetCardInfo("Avenger of Zendikar", 98, Rarity.MYTHIC, mage.cards.a.AvengerOfZendikar.class));
        cards.add(new SetCardInfo("Bane of Progress", 99, Rarity.RARE, mage.cards.b.BaneOfProgress.class));
        cards.add(new SetCardInfo("Belonging", 25, Rarity.RARE, mage.cards.b.Belonging.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Belonging", 5, Rarity.RARE, mage.cards.b.Belonging.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Binding the Old Gods", 120, Rarity.UNCOMMON, mage.cards.b.BindingTheOldGods.class));
        cards.add(new SetCardInfo("Black Sun's Zenith", 71, Rarity.RARE, mage.cards.b.BlackSunsZenith.class));
        cards.add(new SetCardInfo("Blasphemous Act", 89, Rarity.RARE, mage.cards.b.BlasphemousAct.class));
        cards.add(new SetCardInfo("Blowfly Infestation", 46, Rarity.UNCOMMON, mage.cards.b.BlowflyInfestation.class));
        cards.add(new SetCardInfo("Canyon Slough", 145, Rarity.RARE, mage.cards.c.CanyonSlough.class));
        cards.add(new SetCardInfo("Carnifex Demon", 72, Rarity.RARE, mage.cards.c.CarnifexDemon.class));
        cards.add(new SetCardInfo("Cathartic Pyre", 90, Rarity.UNCOMMON, mage.cards.c.CatharticPyre.class));
        cards.add(new SetCardInfo("Cathartic Reunion", 91, Rarity.COMMON, mage.cards.c.CatharticReunion.class));
        cards.add(new SetCardInfo("Cavalier of Thorns", 100, Rarity.MYTHIC, mage.cards.c.CavalierOfThorns.class));
        cards.add(new SetCardInfo("Chain Reaction", 92, Rarity.RARE, mage.cards.c.ChainReaction.class));
        cards.add(new SetCardInfo("Channeler Initiate", 101, Rarity.RARE, mage.cards.c.ChannelerInitiate.class));
        cards.add(new SetCardInfo("Chimil, the Inner Sun", 137, Rarity.MYTHIC, mage.cards.c.ChimilTheInnerSun.class));
        cards.add(new SetCardInfo("Chromatic Lantern", 138, Rarity.RARE, mage.cards.c.ChromaticLantern.class));
        cards.add(new SetCardInfo("Cinder Glade", 146, Rarity.RARE, mage.cards.c.CinderGlade.class));
        cards.add(new SetCardInfo("Command Tower", 59, Rarity.COMMON, mage.cards.c.CommandTower.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Command Tower", 60, Rarity.COMMON, mage.cards.c.CommandTower.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Commander's Sphere", 139, Rarity.COMMON, mage.cards.c.CommandersSphere.class));
        cards.add(new SetCardInfo("Contagion Clasp", 140, Rarity.UNCOMMON, mage.cards.c.ContagionClasp.class));
        cards.add(new SetCardInfo("Cream of the Crop", 102, Rarity.RARE, mage.cards.c.CreamOfTheCrop.class));
        cards.add(new SetCardInfo("Cultivate", 103, Rarity.COMMON, mage.cards.c.Cultivate.class));
        cards.add(new SetCardInfo("Descendants' Fury", 93, Rarity.RARE, mage.cards.d.DescendantsFury.class));
        cards.add(new SetCardInfo("Devoted Druid", 104, Rarity.UNCOMMON, mage.cards.d.DevotedDruid.class));
        cards.add(new SetCardInfo("Distant Melody", 45, Rarity.COMMON, mage.cards.d.DistantMelody.class));
        cards.add(new SetCardInfo("Dragonskull Summit", 147, Rarity.RARE, mage.cards.d.DragonskullSummit.class));
        cards.add(new SetCardInfo("Dusk Urchins", 73, Rarity.RARE, mage.cards.d.DuskUrchins.class));
        cards.add(new SetCardInfo("Endurance", 51, Rarity.MYTHIC, mage.cards.e.Endurance.class));
        cards.add(new SetCardInfo("Everlasting Torment", 121, Rarity.RARE, mage.cards.e.EverlastingTorment.class));
        cards.add(new SetCardInfo("Evolution Sage", 105, Rarity.UNCOMMON, mage.cards.e.EvolutionSage.class));
        cards.add(new SetCardInfo("Exotic Orchard", 148, Rarity.RARE, mage.cards.e.ExoticOrchard.class));
        cards.add(new SetCardInfo("Faeburrow Elder", 53, Rarity.RARE, mage.cards.f.FaeburrowElder.class));
        cards.add(new SetCardInfo("Fellwar Stone", 141, Rarity.UNCOMMON, mage.cards.f.FellwarStone.class));
        cards.add(new SetCardInfo("Fertile Ground", 106, Rarity.COMMON, mage.cards.f.FertileGround.class));
        cards.add(new SetCardInfo("Festering Thicket", 61, Rarity.RARE, mage.cards.f.FesteringThicket.class));
        cards.add(new SetCardInfo("Fire Covenant", 54, Rarity.UNCOMMON, mage.cards.f.FireCovenant.class));
        cards.add(new SetCardInfo("Flamekin Village", 149, Rarity.RARE, mage.cards.f.FlamekinVillage.class));
        cards.add(new SetCardInfo("Flourishing Defenses", 107, Rarity.UNCOMMON, mage.cards.f.FlourishingDefenses.class));
        cards.add(new SetCardInfo("Foundation Breaker", 108, Rarity.UNCOMMON, mage.cards.f.FoundationBreaker.class));
        cards.add(new SetCardInfo("Frontier Bivouac", 150, Rarity.UNCOMMON, mage.cards.f.FrontierBivouac.class));
        cards.add(new SetCardInfo("Fury", 50, Rarity.MYTHIC, mage.cards.f.Fury.class));
        cards.add(new SetCardInfo("Garruk's Uprising", 109, Rarity.UNCOMMON, mage.cards.g.GarruksUprising.class));
        cards.add(new SetCardInfo("Glissa Sunslayer", 122, Rarity.RARE, mage.cards.g.GlissaSunslayer.class));
        cards.add(new SetCardInfo("Golgari Rot Farm", 151, Rarity.UNCOMMON, mage.cards.g.GolgariRotFarm.class));
        cards.add(new SetCardInfo("Grave Titan", 74, Rarity.MYTHIC, mage.cards.g.GraveTitan.class));
        cards.add(new SetCardInfo("Greenwarden of Murasa", 110, Rarity.MYTHIC, mage.cards.g.GreenwardenOfMurasa.class));
        cards.add(new SetCardInfo("Grim Poppet", 142, Rarity.RARE, mage.cards.g.GrimPoppet.class));
        cards.add(new SetCardInfo("Gruul Turf", 152, Rarity.UNCOMMON, mage.cards.g.GruulTurf.class));
        cards.add(new SetCardInfo("Hapatra, Vizier of Poisons", 123, Rarity.RARE, mage.cards.h.HapatraVizierOfPoisons.class));
        cards.add(new SetCardInfo("Harmonize", 111, Rarity.UNCOMMON, mage.cards.h.Harmonize.class));
        cards.add(new SetCardInfo("Haunting Voyage", 75, Rarity.MYTHIC, mage.cards.h.HauntingVoyage.class));
        cards.add(new SetCardInfo("Hoarder's Greed", 47, Rarity.UNCOMMON, mage.cards.h.HoardersGreed.class));
        cards.add(new SetCardInfo("Hoofprints of the Stag", 64, Rarity.RARE, mage.cards.h.HoofprintsOfTheStag.class));
        cards.add(new SetCardInfo("Horde of Notions", 124, Rarity.RARE, mage.cards.h.HordeOfNotions.class));
        cards.add(new SetCardInfo("Ifnir Deadlands", 153, Rarity.UNCOMMON, mage.cards.i.IfnirDeadlands.class));
        cards.add(new SetCardInfo("Ignoble Hierarch", 52, Rarity.RARE, mage.cards.i.IgnobleHierarch.class));
        cards.add(new SetCardInfo("Impulsivity", 13, Rarity.RARE, mage.cards.i.Impulsivity.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Impulsivity", 33, Rarity.RARE, mage.cards.i.Impulsivity.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Incandescent Soulstoke", 94, Rarity.UNCOMMON, mage.cards.i.IncandescentSoulstoke.class));
        cards.add(new SetCardInfo("Incremental Blight", 76, Rarity.UNCOMMON, mage.cards.i.IncrementalBlight.class));
        cards.add(new SetCardInfo("Infernal Grasp", 77, Rarity.UNCOMMON, mage.cards.i.InfernalGrasp.class));
        cards.add(new SetCardInfo("Ingot Chewer", 95, Rarity.COMMON, mage.cards.i.IngotChewer.class));
        cards.add(new SetCardInfo("Jegantha, the Wellspring", 125, Rarity.RARE, mage.cards.j.JeganthaTheWellspring.class));
        cards.add(new SetCardInfo("Jubilation", 17, Rarity.RARE, mage.cards.j.Jubilation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Jubilation", 37, Rarity.RARE, mage.cards.j.Jubilation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Jungle Shrine", 154, Rarity.UNCOMMON, mage.cards.j.JungleShrine.class));
        cards.add(new SetCardInfo("Kindred Summons", 112, Rarity.RARE, mage.cards.k.KindredSummons.class));
        cards.add(new SetCardInfo("Kodama's Reach", 113, Rarity.COMMON, mage.cards.k.KodamasReach.class));
        cards.add(new SetCardInfo("Kulrath Knight", 126, Rarity.UNCOMMON, mage.cards.k.KulrathKnight.class));
        cards.add(new SetCardInfo("Lamentation", 10, Rarity.RARE, mage.cards.l.Lamentation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Lamentation", 30, Rarity.RARE, mage.cards.l.Lamentation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Liliana, Death Wielder", 78, Rarity.MYTHIC, mage.cards.l.LilianaDeathWielder.class));
        cards.add(new SetCardInfo("Maelstrom Wanderer", 127, Rarity.RARE, mage.cards.m.MaelstromWanderer.class));
        cards.add(new SetCardInfo("Massacre Girl, Known Killer", 79, Rarity.MYTHIC, mage.cards.m.MassacreGirlKnownKiller.class));
        cards.add(new SetCardInfo("Midnight Banshee", 80, Rarity.RARE, mage.cards.m.MidnightBanshee.class));
        cards.add(new SetCardInfo("Muldrotha, the Gravetide", 128, Rarity.MYTHIC, mage.cards.m.MuldrothaTheGravetide.class));
        cards.add(new SetCardInfo("Mulldrifter", 67, Rarity.UNCOMMON, mage.cards.m.Mulldrifter.class));
        cards.add(new SetCardInfo("Necroskitter", 48, Rarity.RARE, mage.cards.n.Necroskitter.class));
        cards.add(new SetCardInfo("Nesting Grounds", 155, Rarity.RARE, mage.cards.n.NestingGrounds.class));
        cards.add(new SetCardInfo("Night's Whisper", 81, Rarity.COMMON, mage.cards.n.NightsWhisper.class));
        cards.add(new SetCardInfo("Omnath, Locus of Rage", 129, Rarity.MYTHIC, mage.cards.o.OmnathLocusOfRage.class));
        cards.add(new SetCardInfo("Omnath, Locus of the Roil", 130, Rarity.MYTHIC, mage.cards.o.OmnathLocusOfTheRoil.class));
        cards.add(new SetCardInfo("Opal Palace", 156, Rarity.COMMON, mage.cards.o.OpalPalace.class));
        cards.add(new SetCardInfo("Opulent Palace", 157, Rarity.UNCOMMON, mage.cards.o.OpulentPalace.class));
        cards.add(new SetCardInfo("Painful Truths", 82, Rarity.RARE, mage.cards.p.PainfulTruths.class));
        cards.add(new SetCardInfo("Path of Ancestry", 158, Rarity.COMMON, mage.cards.p.PathOfAncestry.class));
        cards.add(new SetCardInfo("Path to Exile", 65, Rarity.UNCOMMON, mage.cards.p.PathToExile.class));
        cards.add(new SetCardInfo("Persist", 83, Rarity.RARE, mage.cards.p.Persist.class));
        cards.add(new SetCardInfo("Primal Beyond", 159, Rarity.RARE, mage.cards.p.PrimalBeyond.class));
        cards.add(new SetCardInfo("Puppeteer Clique", 84, Rarity.RARE, mage.cards.p.PuppeteerClique.class));
        cards.add(new SetCardInfo("Putrefy", 131, Rarity.UNCOMMON, mage.cards.p.Putrefy.class));
        cards.add(new SetCardInfo("Raging Ravine", 160, Rarity.RARE, mage.cards.r.RagingRavine.class));
        cards.add(new SetCardInfo("Rain-Slicked Copse", 23, Rarity.RARE, mage.cards.r.RainSlickedCopse.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Rain-Slicked Copse", 43, Rarity.RARE, mage.cards.r.RainSlickedCopse.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Rakdos Carnarium", 161, Rarity.UNCOMMON, mage.cards.r.RakdosCarnarium.class));
        cards.add(new SetCardInfo("Reality Shift", 68, Rarity.UNCOMMON, mage.cards.r.RealityShift.class));
        cards.add(new SetCardInfo("Realmwalker", 114, Rarity.RARE, mage.cards.r.Realmwalker.class));
        cards.add(new SetCardInfo("Return of the Wildspeaker", 115, Rarity.RARE, mage.cards.r.ReturnOfTheWildspeaker.class));
        cards.add(new SetCardInfo("Risen Reef", 132, Rarity.UNCOMMON, mage.cards.r.RisenReef.class));
        cards.add(new SetCardInfo("Riveteers Overlook", 162, Rarity.COMMON, mage.cards.r.RiveteersOverlook.class));
        cards.add(new SetCardInfo("Rootbound Crag", 163, Rarity.RARE, mage.cards.r.RootboundCrag.class));
        cards.add(new SetCardInfo("Sandsteppe Citadel", 164, Rarity.UNCOMMON, mage.cards.s.SandsteppeCitadel.class));
        cards.add(new SetCardInfo("Savage Lands", 165, Rarity.UNCOMMON, mage.cards.s.SavageLands.class));
        cards.add(new SetCardInfo("Seaside Citadel", 166, Rarity.UNCOMMON, mage.cards.s.SeasideCitadel.class));
        cards.add(new SetCardInfo("Secluded Courtyard", 62, Rarity.UNCOMMON, mage.cards.s.SecludedCourtyard.class));
        cards.add(new SetCardInfo("Selvala, Heart of the Wilds", 116, Rarity.MYTHIC, mage.cards.s.SelvalaHeartOfTheWilds.class));
        cards.add(new SetCardInfo("Shatter the Sky", 66, Rarity.RARE, mage.cards.s.ShatterTheSky.class));
        cards.add(new SetCardInfo("Sheltered Thicket", 167, Rarity.RARE, mage.cards.s.ShelteredThicket.class));
        cards.add(new SetCardInfo("Shriekmaw", 85, Rarity.UNCOMMON, mage.cards.s.Shriekmaw.class));
        cards.add(new SetCardInfo("Sinister Gnarlbark", 12, Rarity.RARE, mage.cards.s.SinisterGnarlbark.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Sinister Gnarlbark", 32, Rarity.RARE, mage.cards.s.SinisterGnarlbark.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Skinrender", 86, Rarity.UNCOMMON, mage.cards.s.Skinrender.class));
        cards.add(new SetCardInfo("Slithermuse", 69, Rarity.RARE, mage.cards.s.Slithermuse.class));
        cards.add(new SetCardInfo("Smokebraider", 96, Rarity.COMMON, mage.cards.s.Smokebraider.class));
        cards.add(new SetCardInfo("Smoldering Marsh", 168, Rarity.RARE, mage.cards.s.SmolderingMarsh.class));
        cards.add(new SetCardInfo("Sodden Verdure", 24, Rarity.RARE, mage.cards.s.SoddenVerdure.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Sodden Verdure", 44, Rarity.RARE, mage.cards.s.SoddenVerdure.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Sol Ring", 57, Rarity.UNCOMMON, mage.cards.s.SolRing.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Sol Ring", 58, Rarity.UNCOMMON, mage.cards.s.SolRing.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Soul Snuffers", 87, Rarity.UNCOMMON, mage.cards.s.SoulSnuffers.class));
        cards.add(new SetCardInfo("Terminate", 134, Rarity.COMMON, mage.cards.t.Terminate.class));
        cards.add(new SetCardInfo("Terramorphic Expanse", 169, Rarity.COMMON, mage.cards.t.TerramorphicExpanse.class));
        cards.add(new SetCardInfo("The Reaper, King No More", 4, Rarity.MYTHIC, mage.cards.t.TheReaperKingNoMore.class));
        cards.add(new SetCardInfo("The Scorpion God", 133, Rarity.MYTHIC, mage.cards.t.TheScorpionGod.class));
        cards.add(new SetCardInfo("Thriving Bluff", 170, Rarity.COMMON, mage.cards.t.ThrivingBluff.class));
        cards.add(new SetCardInfo("Thriving Grove", 171, Rarity.COMMON, mage.cards.t.ThrivingGrove.class));
        cards.add(new SetCardInfo("Thriving Heath", 172, Rarity.COMMON, mage.cards.t.ThrivingHeath.class));
        cards.add(new SetCardInfo("Thriving Isle", 173, Rarity.COMMON, mage.cards.t.ThrivingIsle.class));
        cards.add(new SetCardInfo("Thriving Moor", 174, Rarity.COMMON, mage.cards.t.ThrivingMoor.class));
        cards.add(new SetCardInfo("Timeless Lotus", 143, Rarity.MYTHIC, mage.cards.t.TimelessLotus.class));
        cards.add(new SetCardInfo("Titan of Industry", 117, Rarity.MYTHIC, mage.cards.t.TitanOfIndustry.class));
        cards.add(new SetCardInfo("Tree of Perdition", 49, Rarity.MYTHIC, mage.cards.t.TreeOfPerdition.class));
        cards.add(new SetCardInfo("Unclaimed Territory", 175, Rarity.UNCOMMON, mage.cards.u.UnclaimedTerritory.class));
        cards.add(new SetCardInfo("Vernal Fen", 63, Rarity.RARE, mage.cards.v.VernalFen.class));
        cards.add(new SetCardInfo("Vernal Sovereign", 135, Rarity.RARE, mage.cards.v.VernalSovereign.class));
        cards.add(new SetCardInfo("Vraska, Betrayal's Sting", 88, Rarity.MYTHIC, mage.cards.v.VraskaBetrayalsSting.class));
        cards.add(new SetCardInfo("Wickerbough Elder", 118, Rarity.COMMON, mage.cards.w.WickerboughElder.class));
        cards.add(new SetCardInfo("Woodland Cemetery", 176, Rarity.RARE, mage.cards.w.WoodlandCemetery.class));
        cards.add(new SetCardInfo("Yarok, the Desecrated", 136, Rarity.MYTHIC, mage.cards.y.YarokTheDesecrated.class));
    }
}
