package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author muz
 */
public final class SecretsOfStrixhavenMysticalArchive extends ExpansionSet {

    private static final SecretsOfStrixhavenMysticalArchive instance = new SecretsOfStrixhavenMysticalArchive();

    public static SecretsOfStrixhavenMysticalArchive getInstance() {
        return instance;
    }

    private SecretsOfStrixhavenMysticalArchive() {
        super("Secrets of Strixhaven Mystical Archive", "SOA", ExpansionSet.buildDate(2026, 4, 24), SetType.SUPPLEMENTAL);
        this.hasBoosters = false;
        this.hasBasicLands = false;
        this.maxCardNumberInBooster = 65;

        cards.add(new SetCardInfo("Abrade", 37, Rarity.UNCOMMON, mage.cards.a.Abrade.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Abrade", 102, Rarity.UNCOMMON, mage.cards.a.Abrade.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Abrade", 167, Rarity.UNCOMMON, mage.cards.a.Abrade.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Ad Nauseam", 25, Rarity.MYTHIC, mage.cards.a.AdNauseam.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Ad Nauseam", 90, Rarity.MYTHIC, mage.cards.a.AdNauseam.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Ad Nauseam", 155, Rarity.MYTHIC, mage.cards.a.AdNauseam.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Akroma's Will", 1, Rarity.MYTHIC, mage.cards.a.AkromasWill.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Akroma's Will", 66, Rarity.MYTHIC, mage.cards.a.AkromasWill.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Akroma's Will", 131, Rarity.MYTHIC, mage.cards.a.AkromasWill.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Angel's Grace", 2, Rarity.RARE, mage.cards.a.AngelsGrace.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Angel's Grace", 67, Rarity.RARE, mage.cards.a.AngelsGrace.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Angel's Grace", 132, Rarity.RARE, mage.cards.a.AngelsGrace.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Armageddon", 3, Rarity.MYTHIC, mage.cards.a.Armageddon.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Armageddon", 68, Rarity.MYTHIC, mage.cards.a.Armageddon.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Armageddon", 133, Rarity.MYTHIC, mage.cards.a.Armageddon.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Awaken the Woods", 49, Rarity.MYTHIC, mage.cards.a.AwakenTheWoods.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Awaken the Woods", 114, Rarity.MYTHIC, mage.cards.a.AwakenTheWoods.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Awaken the Woods", 179, Rarity.MYTHIC, mage.cards.a.AwakenTheWoods.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Berserk", 50, Rarity.MYTHIC, mage.cards.b.Berserk.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Berserk", 115, Rarity.MYTHIC, mage.cards.b.Berserk.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Berserk", 180, Rarity.MYTHIC, mage.cards.b.Berserk.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Big Score", 38, Rarity.RARE, mage.cards.b.BigScore.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Big Score", 103, Rarity.RARE, mage.cards.b.BigScore.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Big Score", 168, Rarity.RARE, mage.cards.b.BigScore.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bitter Triumph", 26, Rarity.UNCOMMON, mage.cards.b.BitterTriumph.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bitter Triumph", 91, Rarity.UNCOMMON, mage.cards.b.BitterTriumph.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bitter Triumph", 156, Rarity.UNCOMMON, mage.cards.b.BitterTriumph.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Brain Freeze", 13, Rarity.RARE, mage.cards.b.BrainFreeze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Brain Freeze", 78, Rarity.RARE, mage.cards.b.BrainFreeze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Brain Freeze", 143, Rarity.RARE, mage.cards.b.BrainFreeze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bring to Light", 61, Rarity.RARE, mage.cards.b.BringToLight.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bring to Light", 126, Rarity.RARE, mage.cards.b.BringToLight.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bring to Light", 191, Rarity.RARE, mage.cards.b.BringToLight.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Brotherhood's End", 39, Rarity.RARE, mage.cards.b.BrotherhoodsEnd.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Brotherhood's End", 104, Rarity.RARE, mage.cards.b.BrotherhoodsEnd.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Brotherhood's End", 169, Rarity.RARE, mage.cards.b.BrotherhoodsEnd.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bulk Up", 40, Rarity.UNCOMMON, mage.cards.b.BulkUp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bulk Up", 105, Rarity.UNCOMMON, mage.cards.b.BulkUp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bulk Up", 170, Rarity.UNCOMMON, mage.cards.b.BulkUp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Burst Lightning", 41, Rarity.UNCOMMON, mage.cards.b.BurstLightning.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Burst Lightning", 106, Rarity.UNCOMMON, mage.cards.b.BurstLightning.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Burst Lightning", 171, Rarity.UNCOMMON, mage.cards.b.BurstLightning.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Crackle with Power", 42, Rarity.MYTHIC, mage.cards.c.CrackleWithPower.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Crackle with Power", 107, Rarity.MYTHIC, mage.cards.c.CrackleWithPower.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Crackle with Power", 172, Rarity.MYTHIC, mage.cards.c.CrackleWithPower.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Crop Rotation", 51, Rarity.RARE, mage.cards.c.CropRotation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Crop Rotation", 116, Rarity.RARE, mage.cards.c.CropRotation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Crop Rotation", 181, Rarity.RARE, mage.cards.c.CropRotation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Culling Ritual", 62, Rarity.RARE, mage.cards.c.CullingRitual.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Culling Ritual", 127, Rarity.RARE, mage.cards.c.CullingRitual.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Culling Ritual", 192, Rarity.RARE, mage.cards.c.CullingRitual.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Culling the Weak", 27, Rarity.RARE, mage.cards.c.CullingTheWeak.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Culling the Weak", 92, Rarity.RARE, mage.cards.c.CullingTheWeak.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Culling the Weak", 157, Rarity.RARE, mage.cards.c.CullingTheWeak.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Cyclonic Rift", 14, Rarity.MYTHIC, mage.cards.c.CyclonicRift.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Cyclonic Rift", 79, Rarity.MYTHIC, mage.cards.c.CyclonicRift.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Cyclonic Rift", 144, Rarity.MYTHIC, mage.cards.c.CyclonicRift.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Daze", 15, Rarity.RARE, mage.cards.d.Daze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Daze", 80, Rarity.RARE, mage.cards.d.Daze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Daze", 145, Rarity.RARE, mage.cards.d.Daze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Deduce", 16, Rarity.UNCOMMON, mage.cards.d.Deduce.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Deduce", 81, Rarity.UNCOMMON, mage.cards.d.Deduce.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Deduce", 146, Rarity.UNCOMMON, mage.cards.d.Deduce.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Deflecting Palm", 63, Rarity.RARE, mage.cards.d.DeflectingPalm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Deflecting Palm", 128, Rarity.RARE, mage.cards.d.DeflectingPalm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Deflecting Palm", 193, Rarity.RARE, mage.cards.d.DeflectingPalm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Disdainful Stroke", 17, Rarity.UNCOMMON, mage.cards.d.DisdainfulStroke.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Disdainful Stroke", 82, Rarity.UNCOMMON, mage.cards.d.DisdainfulStroke.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Disdainful Stroke", 147, Rarity.UNCOMMON, mage.cards.d.DisdainfulStroke.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Dismember", 28, Rarity.RARE, mage.cards.d.Dismember.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Dismember", 93, Rarity.RARE, mage.cards.d.Dismember.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Dismember", 158, Rarity.RARE, mage.cards.d.Dismember.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Duty Beyond Death", 4, Rarity.UNCOMMON, mage.cards.d.DutyBeyondDeath.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Duty Beyond Death", 69, Rarity.UNCOMMON, mage.cards.d.DutyBeyondDeath.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Duty Beyond Death", 134, Rarity.UNCOMMON, mage.cards.d.DutyBeyondDeath.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Empty the Warrens", 43, Rarity.RARE, mage.cards.e.EmptyTheWarrens.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Empty the Warrens", 108, Rarity.RARE, mage.cards.e.EmptyTheWarrens.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Empty the Warrens", 173, Rarity.RARE, mage.cards.e.EmptyTheWarrens.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Expressive Iteration", 64, Rarity.RARE, mage.cards.e.ExpressiveIteration.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Expressive Iteration", 129, Rarity.RARE, mage.cards.e.ExpressiveIteration.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Expressive Iteration", 194, Rarity.RARE, mage.cards.e.ExpressiveIteration.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Feed the Swarm", 29, Rarity.UNCOMMON, mage.cards.f.FeedTheSwarm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Feed the Swarm", 94, Rarity.UNCOMMON, mage.cards.f.FeedTheSwarm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Feed the Swarm", 159, Rarity.UNCOMMON, mage.cards.f.FeedTheSwarm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Flusterstorm", 18, Rarity.MYTHIC, mage.cards.f.Flusterstorm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Flusterstorm", 83, Rarity.MYTHIC, mage.cards.f.Flusterstorm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Flusterstorm", 148, Rarity.MYTHIC, mage.cards.f.Flusterstorm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Force of Will", 19, Rarity.MYTHIC, mage.cards.f.ForceOfWill.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Force of Will", 84, Rarity.MYTHIC, mage.cards.f.ForceOfWill.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Force of Will", 149, Rarity.MYTHIC, mage.cards.f.ForceOfWill.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Fracture", 65, Rarity.RARE, mage.cards.f.Fracture.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Fracture", 130, Rarity.RARE, mage.cards.f.Fracture.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Fracture", 195, Rarity.RARE, mage.cards.f.Fracture.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Giant Growth", 52, Rarity.UNCOMMON, mage.cards.g.GiantGrowth.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Giant Growth", 117, Rarity.UNCOMMON, mage.cards.g.GiantGrowth.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Giant Growth", 182, Rarity.UNCOMMON, mage.cards.g.GiantGrowth.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Glimpse of Nature", 53, Rarity.RARE, mage.cards.g.GlimpseOfNature.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Glimpse of Nature", 118, Rarity.RARE, mage.cards.g.GlimpseOfNature.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Glimpse of Nature", 183, Rarity.RARE, mage.cards.g.GlimpseOfNature.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Helping Hand", 5, Rarity.UNCOMMON, mage.cards.h.HelpingHand.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Helping Hand", 70, Rarity.UNCOMMON, mage.cards.h.HelpingHand.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Helping Hand", 135, Rarity.UNCOMMON, mage.cards.h.HelpingHand.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Hop to It", 6, Rarity.UNCOMMON, mage.cards.h.HopToIt.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Hop to It", 71, Rarity.UNCOMMON, mage.cards.h.HopToIt.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Hop to It", 136, Rarity.UNCOMMON, mage.cards.h.HopToIt.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Jeska's Will", 44, Rarity.MYTHIC, mage.cards.j.JeskasWill.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Jeska's Will", 109, Rarity.MYTHIC, mage.cards.j.JeskasWill.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Jeska's Will", 174, Rarity.MYTHIC, mage.cards.j.JeskasWill.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Knockout Maneuver", 54, Rarity.UNCOMMON, mage.cards.k.KnockoutManeuver.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Knockout Maneuver", 119, Rarity.UNCOMMON, mage.cards.k.KnockoutManeuver.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Knockout Maneuver", 184, Rarity.UNCOMMON, mage.cards.k.KnockoutManeuver.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Living End", 30, Rarity.MYTHIC, mage.cards.l.LivingEnd.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Living End", 95, Rarity.MYTHIC, mage.cards.l.LivingEnd.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Living End", 160, Rarity.MYTHIC, mage.cards.l.LivingEnd.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Locust Spray", 31, Rarity.UNCOMMON, mage.cards.l.LocustSpray.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Locust Spray", 96, Rarity.UNCOMMON, mage.cards.l.LocustSpray.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Locust Spray", 161, Rarity.UNCOMMON, mage.cards.l.LocustSpray.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Monstrous Rage", 45, Rarity.UNCOMMON, mage.cards.m.MonstrousRage.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Monstrous Rage", 110, Rarity.UNCOMMON, mage.cards.m.MonstrousRage.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Monstrous Rage", 175, Rarity.UNCOMMON, mage.cards.m.MonstrousRage.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Pick Your Poison", 55, Rarity.UNCOMMON, mage.cards.p.PickYourPoison.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Pick Your Poison", 120, Rarity.UNCOMMON, mage.cards.p.PickYourPoison.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Pick Your Poison", 185, Rarity.UNCOMMON, mage.cards.p.PickYourPoison.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Pongify", 20, Rarity.RARE, mage.cards.p.Pongify.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Pongify", 85, Rarity.RARE, mage.cards.p.Pongify.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Pongify", 150, Rarity.RARE, mage.cards.p.Pongify.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Preordain", 21, Rarity.RARE, mage.cards.p.Preordain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Preordain", 86, Rarity.RARE, mage.cards.p.Preordain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Preordain", 151, Rarity.RARE, mage.cards.p.Preordain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Prismatic Ending", 7, Rarity.RARE, mage.cards.p.PrismaticEnding.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Prismatic Ending", 72, Rarity.RARE, mage.cards.p.PrismaticEnding.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Prismatic Ending", 137, Rarity.RARE, mage.cards.p.PrismaticEnding.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Pyretic Ritual", 46, Rarity.RARE, mage.cards.p.PyreticRitual.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Pyretic Ritual", 111, Rarity.RARE, mage.cards.p.PyreticRitual.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Pyretic Ritual", 176, Rarity.RARE, mage.cards.p.PyreticRitual.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Repel Calamity", 8, Rarity.UNCOMMON, mage.cards.r.RepelCalamity.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Repel Calamity", 73, Rarity.UNCOMMON, mage.cards.r.RepelCalamity.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Repel Calamity", 138, Rarity.UNCOMMON, mage.cards.r.RepelCalamity.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Reprieve", 9, Rarity.RARE, mage.cards.r.Reprieve.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Reprieve", 74, Rarity.RARE, mage.cards.r.Reprieve.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Reprieve", 139, Rarity.RARE, mage.cards.r.Reprieve.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Requisition Raid", 10, Rarity.UNCOMMON, mage.cards.r.RequisitionRaid.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Requisition Raid", 75, Rarity.UNCOMMON, mage.cards.r.RequisitionRaid.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Requisition Raid", 140, Rarity.UNCOMMON, mage.cards.r.RequisitionRaid.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Return the Favor", 47, Rarity.UNCOMMON, mage.cards.r.ReturnTheFavor.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Return the Favor", 112, Rarity.UNCOMMON, mage.cards.r.ReturnTheFavor.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Return the Favor", 177, Rarity.UNCOMMON, mage.cards.r.ReturnTheFavor.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Return to the Ranks", 11, Rarity.RARE, mage.cards.r.ReturnToTheRanks.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Return to the Ranks", 76, Rarity.RARE, mage.cards.r.ReturnToTheRanks.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Return to the Ranks", 141, Rarity.RARE, mage.cards.r.ReturnToTheRanks.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Royal Treatment", 56, Rarity.UNCOMMON, mage.cards.r.RoyalTreatment.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Royal Treatment", 121, Rarity.UNCOMMON, mage.cards.r.RoyalTreatment.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Royal Treatment", 186, Rarity.UNCOMMON, mage.cards.r.RoyalTreatment.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shamanic Revelation", 57, Rarity.RARE, mage.cards.s.ShamanicRevelation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shamanic Revelation", 122, Rarity.RARE, mage.cards.s.ShamanicRevelation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shamanic Revelation", 187, Rarity.RARE, mage.cards.s.ShamanicRevelation.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shared Roots", 58, Rarity.UNCOMMON, mage.cards.s.SharedRoots.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shared Roots", 123, Rarity.UNCOMMON, mage.cards.s.SharedRoots.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shared Roots", 188, Rarity.UNCOMMON, mage.cards.s.SharedRoots.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Sheoldred's Edict", 32, Rarity.RARE, mage.cards.s.SheoldredsEdict.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Sheoldred's Edict", 97, Rarity.RARE, mage.cards.s.SheoldredsEdict.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Sheoldred's Edict", 162, Rarity.RARE, mage.cards.s.SheoldredsEdict.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Sleight of Hand", 22, Rarity.UNCOMMON, mage.cards.s.SleightOfHand.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Sleight of Hand", 87, Rarity.UNCOMMON, mage.cards.s.SleightOfHand.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Sleight of Hand", 152, Rarity.UNCOMMON, mage.cards.s.SleightOfHand.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Smallpox", 33, Rarity.RARE, mage.cards.s.Smallpox.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Smallpox", 98, Rarity.RARE, mage.cards.s.Smallpox.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Smallpox", 163, Rarity.RARE, mage.cards.s.Smallpox.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Spell Pierce", 23, Rarity.UNCOMMON, mage.cards.s.SpellPierce.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Spell Pierce", 88, Rarity.UNCOMMON, mage.cards.s.SpellPierce.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Spell Pierce", 153, Rarity.UNCOMMON, mage.cards.s.SpellPierce.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Stargaze", 34, Rarity.UNCOMMON, mage.cards.s.Stargaze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Stargaze", 99, Rarity.UNCOMMON, mage.cards.s.Stargaze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Stargaze", 164, Rarity.UNCOMMON, mage.cards.s.Stargaze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Stock Up", 24, Rarity.UNCOMMON, mage.cards.s.StockUp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Stock Up", 89, Rarity.UNCOMMON, mage.cards.s.StockUp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Stock Up", 154, Rarity.UNCOMMON, mage.cards.s.StockUp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Subterranean Tremors", 48, Rarity.MYTHIC, mage.cards.s.SubterraneanTremors.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Subterranean Tremors", 113, Rarity.MYTHIC, mage.cards.s.SubterraneanTremors.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Subterranean Tremors", 178, Rarity.MYTHIC, mage.cards.s.SubterraneanTremors.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Triumph of the Hordes", 59, Rarity.MYTHIC, mage.cards.t.TriumphOfTheHordes.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Triumph of the Hordes", 124, Rarity.MYTHIC, mage.cards.t.TriumphOfTheHordes.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Triumph of the Hordes", 189, Rarity.MYTHIC, mage.cards.t.TriumphOfTheHordes.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Vampiric Tutor", 35, Rarity.MYTHIC, mage.cards.v.VampiricTutor.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Vampiric Tutor", 100, Rarity.MYTHIC, mage.cards.v.VampiricTutor.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Vampiric Tutor", 165, Rarity.MYTHIC, mage.cards.v.VampiricTutor.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Veil of Summer", 60, Rarity.RARE, mage.cards.v.VeilOfSummer.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Veil of Summer", 125, Rarity.RARE, mage.cards.v.VeilOfSummer.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Veil of Summer", 190, Rarity.RARE, mage.cards.v.VeilOfSummer.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Winds of Abandon", 12, Rarity.MYTHIC, mage.cards.w.WindsOfAbandon.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Winds of Abandon", 77, Rarity.MYTHIC, mage.cards.w.WindsOfAbandon.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Winds of Abandon", 142, Rarity.MYTHIC, mage.cards.w.WindsOfAbandon.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Zombify", 36, Rarity.UNCOMMON, mage.cards.z.Zombify.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Zombify", 101, Rarity.UNCOMMON, mage.cards.z.Zombify.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Zombify", 166, Rarity.UNCOMMON, mage.cards.z.Zombify.class, NON_FULL_USE_VARIOUS));
    }
}
