package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author TheElk801
 */
public final class TeenageMutantNinjaTurtles extends ExpansionSet {

    private static final TeenageMutantNinjaTurtles instance = new TeenageMutantNinjaTurtles();

    public static TeenageMutantNinjaTurtles getInstance() {
        return instance;
    }

    private TeenageMutantNinjaTurtles() {
        super("Teenage Mutant Ninja Turtles", "TMT", ExpansionSet.buildDate(2026, 3, 6), SetType.EXPANSION);
        this.blockName = "Teenage Mutant Ninja Turtles"; // for sorting in GUI
        this.hasBasicLands = true;

        cards.add(new SetCardInfo("Action News Crew", 1, Rarity.COMMON, mage.cards.a.ActionNewsCrew.class));
        cards.add(new SetCardInfo("Agent Bishop, Man in Black", 2, Rarity.RARE, mage.cards.a.AgentBishopManInBlack.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Agent Bishop, Man in Black", 258, Rarity.RARE, mage.cards.a.AgentBishopManInBlack.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Anchovy & Banana Pizza", 57, Rarity.COMMON, mage.cards.a.AnchovyAndBananaPizza.class));
        cards.add(new SetCardInfo("April O'Neil, Hacktivist", 227, Rarity.RARE, mage.cards.a.AprilONeilHacktivist.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("April O'Neil, Hacktivist", 282, Rarity.MYTHIC, mage.cards.a.AprilONeilHacktivist.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("April O'Neil, Hacktivist", 29, Rarity.RARE, mage.cards.a.AprilONeilHacktivist.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("April O'Neil, Hacktivist", 292, Rarity.MYTHIC, mage.cards.a.AprilONeilHacktivist.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("April O'Neil, Kunoichi Trainee", 3, Rarity.COMMON, mage.cards.a.AprilONeilKunoichiTrainee.class));
        cards.add(new SetCardInfo("Armaggon, Future Shark", 264, Rarity.RARE, mage.cards.a.ArmaggonFutureShark.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Armaggon, Future Shark", 58, Rarity.RARE, mage.cards.a.ArmaggonFutureShark.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Baxter Stockman", 139, Rarity.UNCOMMON, mage.cards.b.BaxterStockman.class));
        cards.add(new SetCardInfo("Bebop & Rocksteady", 140, Rarity.RARE, mage.cards.b.BebopAndRocksteady.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bebop & Rocksteady", 204, Rarity.RARE, mage.cards.b.BebopAndRocksteady.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bebop & Rocksteady", 241, Rarity.RARE, mage.cards.b.BebopAndRocksteady.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Bebop, Warthog Warrior", 59, Rarity.COMMON, mage.cards.b.BebopWarthogWarrior.class));
        cards.add(new SetCardInfo("Bespoke Bo", 31, Rarity.UNCOMMON, mage.cards.b.BespokeBo.class));
        cards.add(new SetCardInfo("Bot Bashing Time", 85, Rarity.COMMON, mage.cards.b.BotBashingTime.class));
        cards.add(new SetCardInfo("Broadcast Takeover", 234, Rarity.MYTHIC, mage.cards.b.BroadcastTakeover.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Broadcast Takeover", 86, Rarity.MYTHIC, mage.cards.b.BroadcastTakeover.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Buzz Bots", 32, Rarity.COMMON, mage.cards.b.BuzzBots.class));
        cards.add(new SetCardInfo("Casey Jones, Jury-Rig Justiciar", 207, Rarity.UNCOMMON, mage.cards.c.CaseyJonesJuryRigJusticiar.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Casey Jones, Jury-Rig Justiciar", 87, Rarity.UNCOMMON, mage.cards.c.CaseyJonesJuryRigJusticiar.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Casey Jones, Vigilante", 235, Rarity.RARE, mage.cards.c.CaseyJonesVigilante.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Casey Jones, Vigilante", 286, Rarity.MYTHIC, mage.cards.c.CaseyJonesVigilante.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Casey Jones, Vigilante", 296, Rarity.MYTHIC, mage.cards.c.CaseyJonesVigilante.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Casey Jones, Vigilante", 88, Rarity.RARE, mage.cards.c.CaseyJonesVigilante.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Chrome Dome", 172, Rarity.RARE, mage.cards.c.ChromeDome.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Chrome Dome", 276, Rarity.RARE, mage.cards.c.ChromeDome.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Cool but Rude", 89, Rarity.RARE, mage.cards.c.CoolButRude.class));
        cards.add(new SetCardInfo("Courier of Comestibles", 112, Rarity.UNCOMMON, mage.cards.c.CourierOfComestibles.class));
        cards.add(new SetCardInfo("Cowabunga!", 113, Rarity.COMMON, mage.cards.c.Cowabunga.class));
        cards.add(new SetCardInfo("Crustacean Commando", 33, Rarity.COMMON, mage.cards.c.CrustaceanCommando.class));
        cards.add(new SetCardInfo("Dark Leo & Shredder", 142, Rarity.MYTHIC, mage.cards.d.DarkLeoAndShredder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Dark Leo & Shredder", 220, Rarity.MYTHIC, mage.cards.d.DarkLeoAndShredder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Dark Leo & Shredder", 289, Rarity.MYTHIC, mage.cards.d.DarkLeoAndShredder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Dark Leo & Shredder", 299, Rarity.MYTHIC, mage.cards.d.DarkLeoAndShredder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Death in the Family", 61, Rarity.UNCOMMON, mage.cards.d.DeathInTheFamily.class));
        cards.add(new SetCardInfo("Dimension X", 183, Rarity.COMMON, mage.cards.d.DimensionX.class));
        cards.add(new SetCardInfo("Dimensional Exile", 4, Rarity.UNCOMMON, mage.cards.d.DimensionalExile.class));
        cards.add(new SetCardInfo("Does Machines", 34, Rarity.RARE, mage.cards.d.DoesMachines.class));
        cards.add(new SetCardInfo("Don & Leo, Problem Solvers", 143, Rarity.RARE, mage.cards.d.DonAndLeoProblemSolvers.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Don & Leo, Problem Solvers", 242, Rarity.RARE, mage.cards.d.DonAndLeoProblemSolvers.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Don & Raph, Hard Science", 144, Rarity.RARE, mage.cards.d.DonAndRaphHardScience.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Don & Raph, Hard Science", 205, Rarity.RARE, mage.cards.d.DonAndRaphHardScience.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Don & Raph, Hard Science", 243, Rarity.RARE, mage.cards.d.DonAndRaphHardScience.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Donatello's Technique", 228, Rarity.UNCOMMON, mage.cards.d.DonatellosTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Donatello's Technique", 39, Rarity.UNCOMMON, mage.cards.d.DonatellosTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Donatello, Gadget Master", 212, Rarity.RARE, mage.cards.d.DonatelloGadgetMaster.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Donatello, Gadget Master", 283, Rarity.MYTHIC, mage.cards.d.DonatelloGadgetMaster.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Donatello, Gadget Master", 293, Rarity.MYTHIC, mage.cards.d.DonatelloGadgetMaster.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Donatello, Gadget Master", 35, Rarity.RARE, mage.cards.d.DonatelloGadgetMaster.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Donatello, Mutant Mechanic", 216, Rarity.MYTHIC, mage.cards.d.DonatelloMutantMechanic.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Donatello, Mutant Mechanic", 302, Rarity.MYTHIC, mage.cards.d.DonatelloMutantMechanic.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Donatello, Mutant Mechanic", 36, Rarity.MYTHIC, mage.cards.d.DonatelloMutantMechanic.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Donatello, Way with Machines", 197, Rarity.UNCOMMON, mage.cards.d.DonatelloWayWithMachines.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Donatello, Way with Machines", 38, Rarity.UNCOMMON, mage.cards.d.DonatelloWayWithMachines.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Dream Beavers", 62, Rarity.UNCOMMON, mage.cards.d.DreamBeavers.class));
        cards.add(new SetCardInfo("EPF Point Squad", 145, Rarity.COMMON, mage.cards.e.EPFPointSquad.class));
        cards.add(new SetCardInfo("East Wind Avatar", 5, Rarity.COMMON, mage.cards.e.EastWindAvatar.class));
        cards.add(new SetCardInfo("Escape Tunnel", 184, Rarity.COMMON, mage.cards.e.EscapeTunnel.class));
        cards.add(new SetCardInfo("Everything Pizza", 173, Rarity.UNCOMMON, mage.cards.e.EverythingPizza.class));
        cards.add(new SetCardInfo("Featherbrained Filcher", 6, Rarity.UNCOMMON, mage.cards.f.FeatherbrainedFilcher.class));
        cards.add(new SetCardInfo("Foot Elite", 146, Rarity.COMMON, mage.cards.f.FootElite.class));
        cards.add(new SetCardInfo("Foot Headquarters", 185, Rarity.COMMON, mage.cards.f.FootHeadquarters.class));
        cards.add(new SetCardInfo("Foot Mystic", 63, Rarity.COMMON, mage.cards.f.FootMystic.class));
        cards.add(new SetCardInfo("Foot Ninjas", 147, Rarity.COMMON, mage.cards.f.FootNinjas.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Foot Ninjas", 209, Rarity.COMMON, mage.cards.f.FootNinjas.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 195, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 257, Rarity.LAND, mage.cards.basiclands.Forest.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Forest", 309, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 314, Rarity.LAND, mage.cards.basiclands.Forest.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Forest", 319, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Frog Butler", 114, Rarity.COMMON, mage.cards.f.FrogButler.class));
        cards.add(new SetCardInfo("General Traag, Heart of Stone", 90, Rarity.UNCOMMON, mage.cards.g.GeneralTraagHeartOfStone.class));
        cards.add(new SetCardInfo("Genghis Frog", 148, Rarity.UNCOMMON, mage.cards.g.GenghisFrog.class));
        cards.add(new SetCardInfo("Go Ninja Go", 149, Rarity.UNCOMMON, mage.cards.g.GoNinjaGo.class));
        cards.add(new SetCardInfo("Groundchuck & Dirtbag", 115, Rarity.RARE, mage.cards.g.GroundchuckAndDirtbag.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Groundchuck & Dirtbag", 238, Rarity.RARE, mage.cards.g.GroundchuckAndDirtbag.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Grounded for Life", 7, Rarity.COMMON, mage.cards.g.GroundedForLife.class));
        cards.add(new SetCardInfo("Guac & Marshmallow Pizza", 116, Rarity.COMMON, mage.cards.g.GuacAndMarshmallowPizza.class));
        cards.add(new SetCardInfo("Hamato Guardian Stance", 8, Rarity.COMMON, mage.cards.h.HamatoGuardianStance.class));
        cards.add(new SetCardInfo("Hard-Won Jitte", 91, Rarity.UNCOMMON, mage.cards.h.HardWonJitte.class));
        cards.add(new SetCardInfo("Henchbots", 174, Rarity.UNCOMMON, mage.cards.h.Henchbots.class));
        cards.add(new SetCardInfo("High-Flying Ace", 9, Rarity.COMMON, mage.cards.h.HighFlyingAce.class));
        cards.add(new SetCardInfo("Ice Cream Kitty", 150, Rarity.COMMON, mage.cards.i.IceCreamKitty.class));
        cards.add(new SetCardInfo("Illegitimate Business", 186, Rarity.COMMON, mage.cards.i.IllegitimateBusiness.class));
        cards.add(new SetCardInfo("Improvised Arsenal", 270, Rarity.RARE, mage.cards.i.ImprovisedArsenal.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Improvised Arsenal", 92, Rarity.RARE, mage.cards.i.ImprovisedArsenal.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Insectoid Exterminator", 64, Rarity.COMMON, mage.cards.i.InsectoidExterminator.class));
        cards.add(new SetCardInfo("Island", 192, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Island", 254, Rarity.LAND, mage.cards.basiclands.Island.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Island", 306, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Island", 311, Rarity.LAND, mage.cards.basiclands.Island.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Island", 316, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Jennika's Technique", 236, Rarity.UNCOMMON, mage.cards.j.JennikasTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Jennika's Technique", 93, Rarity.UNCOMMON, mage.cards.j.JennikasTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Jennika, Bad Apple Big Sister", 10, Rarity.COMMON, mage.cards.j.JennikaBadAppleBigSister.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Jennika, Bad Apple Big Sister", 203, Rarity.COMMON, mage.cards.j.JennikaBadAppleBigSister.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Kitsune's Technique", 229, Rarity.RARE, mage.cards.k.KitsunesTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Kitsune's Technique", 42, Rarity.RARE, mage.cards.k.KitsunesTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Kitsune, Dragon's Daughter", 262, Rarity.RARE, mage.cards.k.KitsuneDragonsDaughter.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Kitsune, Dragon's Daughter", 41, Rarity.RARE, mage.cards.k.KitsuneDragonsDaughter.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Krang & Shredder", 153, Rarity.RARE, mage.cards.k.KrangAndShredder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Krang & Shredder", 201, Rarity.RARE, mage.cards.k.KrangAndShredder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Krang & Shredder", 245, Rarity.RARE, mage.cards.k.KrangAndShredder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Krang, Master Mind", 230, Rarity.RARE, mage.cards.k.KrangMasterMind.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Krang, Master Mind", 43, Rarity.RARE, mage.cards.k.KrangMasterMind.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Krang, Utrom Warlord", 175, Rarity.MYTHIC, mage.cards.k.KrangUtromWarlord.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Krang, Utrom Warlord", 221, Rarity.MYTHIC, mage.cards.k.KrangUtromWarlord.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Krang, Utrom Warlord", 290, Rarity.MYTHIC, mage.cards.k.KrangUtromWarlord.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Krang, Utrom Warlord", 300, Rarity.MYTHIC, mage.cards.k.KrangUtromWarlord.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Leader's Talent", 13, Rarity.RARE, mage.cards.l.LeadersTalent.class));
        cards.add(new SetCardInfo("Leatherhead, Swamp Stalker", 117, Rarity.RARE, mage.cards.l.LeatherheadSwampStalker.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Leatherhead, Swamp Stalker", 272, Rarity.RARE, mage.cards.l.LeatherheadSwampStalker.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Leonardo's Technique", 18, Rarity.RARE, mage.cards.l.LeonardosTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Leonardo's Technique", 224, Rarity.RARE, mage.cards.l.LeonardosTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Leonardo, Big Brother", 14, Rarity.COMMON, mage.cards.l.LeonardoBigBrother.class));
        cards.add(new SetCardInfo("Leonardo, Cutting Edge", 15, Rarity.RARE, mage.cards.l.LeonardoCuttingEdge.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Leonardo, Cutting Edge", 211, Rarity.RARE, mage.cards.l.LeonardoCuttingEdge.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Leonardo, Cutting Edge", 281, Rarity.MYTHIC, mage.cards.l.LeonardoCuttingEdge.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Leonardo, Cutting Edge", 291, Rarity.MYTHIC, mage.cards.l.LeonardoCuttingEdge.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Leonardo, Sewer Samurai", 17, Rarity.MYTHIC, mage.cards.l.LeonardoSewerSamurai.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Leonardo, Sewer Samurai", 215, Rarity.MYTHIC, mage.cards.l.LeonardoSewerSamurai.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Leonardo, Sewer Samurai", 301, Rarity.MYTHIC, mage.cards.l.LeonardoSewerSamurai.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Lessons from Life", 155, Rarity.UNCOMMON, mage.cards.l.LessonsFromLife.class));
        cards.add(new SetCardInfo("Lita, Little Orphan Amphibian", 19, Rarity.UNCOMMON, mage.cards.l.LitaLittleOrphanAmphibian.class));
        cards.add(new SetCardInfo("Lord Dregg, Insect Invader", 65, Rarity.UNCOMMON, mage.cards.l.LordDreggInsectInvader.class));
        cards.add(new SetCardInfo("Madame Null, Power Broker", 265, Rarity.RARE, mage.cards.m.MadameNullPowerBroker.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Madame Null, Power Broker", 66, Rarity.RARE, mage.cards.m.MadameNullPowerBroker.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Make Your Move", 20, Rarity.COMMON, mage.cards.m.MakeYourMove.class));
        cards.add(new SetCardInfo("Mechanized Ninja Cavalry", 156, Rarity.COMMON, mage.cards.m.MechanizedNinjaCavalry.class));
        cards.add(new SetCardInfo("Metalhead", 44, Rarity.UNCOMMON, mage.cards.m.Metalhead.class));
        cards.add(new SetCardInfo("Michelangelo's Technique", 122, Rarity.RARE, mage.cards.m.MichelangelosTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Michelangelo's Technique", 239, Rarity.RARE, mage.cards.m.MichelangelosTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Michelangelo, Improviser", 119, Rarity.MYTHIC, mage.cards.m.MichelangeloImproviser.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Michelangelo, Improviser", 219, Rarity.MYTHIC, mage.cards.m.MichelangeloImproviser.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Michelangelo, Improviser", 304, Rarity.MYTHIC, mage.cards.m.MichelangeloImproviser.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Michelangelo, Weirdness to 11", 121, Rarity.RARE, mage.cards.m.MichelangeloWeirdnessTo11.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Michelangelo, Weirdness to 11", 214, Rarity.RARE, mage.cards.m.MichelangeloWeirdnessTo11.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Michelangelo, Weirdness to 11", 288, Rarity.MYTHIC, mage.cards.m.MichelangeloWeirdnessTo11.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Michelangelo, Weirdness to 11", 298, Rarity.MYTHIC, mage.cards.m.MichelangeloWeirdnessTo11.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mighty Mutanimals", 21, Rarity.UNCOMMON, mage.cards.m.MightyMutanimals.class));
        cards.add(new SetCardInfo("Mikey & Leo, Chaos & Order", 158, Rarity.RARE, mage.cards.m.MikeyAndLeoChaosAndOrder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mikey & Leo, Chaos & Order", 200, Rarity.RARE, mage.cards.m.MikeyAndLeoChaosAndOrder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mikey & Leo, Chaos & Order", 247, Rarity.RARE, mage.cards.m.MikeyAndLeoChaosAndOrder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mind Transfer Protocol", 45, Rarity.COMMON, mage.cards.m.MindTransferProtocol.class));
        cards.add(new SetCardInfo("Mona Lisa, Science Geek", 123, Rarity.UNCOMMON, mage.cards.m.MonaLisaScienceGeek.class));
        cards.add(new SetCardInfo("Mondo Gecko", 231, Rarity.MYTHIC, mage.cards.m.MondoGecko.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mondo Gecko", 46, Rarity.MYTHIC, mage.cards.m.MondoGecko.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 194, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 256, Rarity.LAND, mage.cards.basiclands.Mountain.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 308, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 313, Rarity.LAND, mage.cards.basiclands.Mountain.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 318, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mouser Attack!", 95, Rarity.COMMON, mage.cards.m.MouserAttack.class));
        cards.add(new SetCardInfo("Mouser Foundry", 96, Rarity.COMMON, mage.cards.m.MouserFoundry.class));
        cards.add(new SetCardInfo("Mouser Mark III", 159, Rarity.COMMON, mage.cards.m.MouserMarkIII.class));
        cards.add(new SetCardInfo("Mutagen Man, Living Ooze", 124, Rarity.RARE, mage.cards.m.MutagenManLivingOoze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mutagen Man, Living Ooze", 273, Rarity.RARE, mage.cards.m.MutagenManLivingOoze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mutant Chain Reaction", 125, Rarity.COMMON, mage.cards.m.MutantChainReaction.class));
        cards.add(new SetCardInfo("Mutant Town", 187, Rarity.COMMON, mage.cards.m.MutantTown.class));
        cards.add(new SetCardInfo("Mutant Town Musicians", 97, Rarity.COMMON, mage.cards.m.MutantTownMusicians.class));
        cards.add(new SetCardInfo("Negate", 47, Rarity.COMMON, mage.cards.n.Negate.class));
        cards.add(new SetCardInfo("New Generation's Technique", 126, Rarity.UNCOMMON, mage.cards.n.NewGenerationsTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("New Generation's Technique", 240, Rarity.UNCOMMON, mage.cards.n.NewGenerationsTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Ninja Teen", 67, Rarity.RARE, mage.cards.n.NinjaTeen.class));
        cards.add(new SetCardInfo("Nobody", 161, Rarity.COMMON, mage.cards.n.Nobody.class));
        cards.add(new SetCardInfo("North Wind Avatar", 162, Rarity.MYTHIC, mage.cards.n.NorthWindAvatar.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("North Wind Avatar", 248, Rarity.MYTHIC, mage.cards.n.NorthWindAvatar.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Northampton Farm", 188, Rarity.RARE, mage.cards.n.NorthamptonFarm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Northampton Farm", 280, Rarity.RARE, mage.cards.n.NorthamptonFarm.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Null Group Biological Assets", 98, Rarity.COMMON, mage.cards.n.NullGroupBiologicalAssets.class));
        cards.add(new SetCardInfo("Omni-Cheese Pizza", 176, Rarity.COMMON, mage.cards.o.OmniCheesePizza.class));
        cards.add(new SetCardInfo("Ooze Spill", 48, Rarity.UNCOMMON, mage.cards.o.OozeSpill.class));
        cards.add(new SetCardInfo("Pain 101", 69, Rarity.COMMON, mage.cards.p.Pain101.class));
        cards.add(new SetCardInfo("Oroku Saki, Shredder Rising", 68, Rarity.COMMON, mage.cards.o.OrokuSakiShredderRising.class));
        cards.add(new SetCardInfo("Party Dude", 128, Rarity.RARE, mage.cards.p.PartyDude.class));
        cards.add(new SetCardInfo("Plains", 191, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Plains", 253, Rarity.LAND, mage.cards.basiclands.Plains.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Plains", 305, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Plains", 310, Rarity.LAND, mage.cards.basiclands.Plains.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Plains", 315, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Prehistoric Pet", 22, Rarity.RARE, mage.cards.p.PrehistoricPet.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Prehistoric Pet", 259, Rarity.RARE, mage.cards.p.PrehistoricPet.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Primordial Pachyderm", 129, Rarity.COMMON, mage.cards.p.PrimordialPachyderm.class));
        cards.add(new SetCardInfo("Punk Frogs", 164, Rarity.COMMON, mage.cards.p.PunkFrogs.class));
        cards.add(new SetCardInfo("Purple Dragon Punks", 100, Rarity.COMMON, mage.cards.p.PurpleDragonPunks.class));
        cards.add(new SetCardInfo("Putrid Pals", 165, Rarity.COMMON, mage.cards.p.PutridPals.class));
        cards.add(new SetCardInfo("Ragamuffin Raptor", 130, Rarity.COMMON, mage.cards.r.RagamuffinRaptor.class));
        cards.add(new SetCardInfo("Raph & Leo, Sibling Rivals", 166, Rarity.RARE, mage.cards.r.RaphAndLeoSiblingRivals.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raph & Leo, Sibling Rivals", 249, Rarity.RARE, mage.cards.r.RaphAndLeoSiblingRivals.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raph & Mikey, Troublemakers", 167, Rarity.RARE, mage.cards.r.RaphAndMikeyTroublemakers.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raph & Mikey, Troublemakers", 250, Rarity.RARE, mage.cards.r.RaphAndMikeyTroublemakers.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raphael's Technique", 105, Rarity.RARE, mage.cards.r.RaphaelsTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raphael's Technique", 237, Rarity.RARE, mage.cards.r.RaphaelsTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raphael, Ninja Destroyer", 102, Rarity.MYTHIC, mage.cards.r.RaphaelNinjaDestroyer.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raphael, Ninja Destroyer", 218, Rarity.MYTHIC, mage.cards.r.RaphaelNinjaDestroyer.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raphael, Ninja Destroyer", 303, Rarity.MYTHIC, mage.cards.r.RaphaelNinjaDestroyer.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raphael, Tough Turtle", 104, Rarity.COMMON, mage.cards.r.RaphaelToughTurtle.class));
        cards.add(new SetCardInfo("Raphael, the Nightwatcher", 103, Rarity.RARE, mage.cards.r.RaphaelTheNightwatcher.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raphael, the Nightwatcher", 213, Rarity.RARE, mage.cards.r.RaphaelTheNightwatcher.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raphael, the Nightwatcher", 287, Rarity.MYTHIC, mage.cards.r.RaphaelTheNightwatcher.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Raphael, the Nightwatcher", 297, Rarity.MYTHIC, mage.cards.r.RaphaelTheNightwatcher.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Rat King, Verminister", 266, Rarity.RARE, mage.cards.r.RatKingVerminister.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Rat King, Verminister", 71, Rarity.RARE, mage.cards.r.RatKingVerminister.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Ravenous Robots", 106, Rarity.RARE, mage.cards.r.RavenousRobots.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Ravenous Robots", 271, Rarity.RARE, mage.cards.r.RavenousRobots.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Ray Fillet, Man Ray", 49, Rarity.UNCOMMON, mage.cards.r.RayFilletManRay.class));
        cards.add(new SetCardInfo("Renet, Temporal Apprentice", 202, Rarity.RARE, mage.cards.r.RenetTemporalApprentice.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Renet, Temporal Apprentice", 50, Rarity.RARE, mage.cards.r.RenetTemporalApprentice.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Retro-Mutation", 51, Rarity.COMMON, mage.cards.r.RetroMutation.class));
        cards.add(new SetCardInfo("Return to the Sewers", 52, Rarity.COMMON, mage.cards.r.ReturnToTheSewers.class));
        cards.add(new SetCardInfo("Rock Soldiers", 107, Rarity.COMMON, mage.cards.r.RockSoldiers.class));
        cards.add(new SetCardInfo("Sally Pride, Lioness Leader", 225, Rarity.RARE, mage.cards.s.SallyPrideLionessLeader.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Sally Pride, Lioness Leader", 24, Rarity.RARE, mage.cards.s.SallyPrideLionessLeader.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Savanti Romero, Time's Exile", 267, Rarity.RARE, mage.cards.s.SavantiRomeroTimesExile.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Savanti Romero, Time's Exile", 72, Rarity.RARE, mage.cards.s.SavantiRomeroTimesExile.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Saved by the Shell", 132, Rarity.UNCOMMON, mage.cards.s.SavedByTheShell.class));
        cards.add(new SetCardInfo("Sewer-veillance Cam", 53, Rarity.COMMON, mage.cards.s.SewerVeillanceCam.class));
        cards.add(new SetCardInfo("Shark Shredder, Killer Clone", 268, Rarity.RARE, mage.cards.s.SharkShredderKillerClone.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shark Shredder, Killer Clone", 320, Rarity.RARE, mage.cards.s.SharkShredderKillerClone.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shark Shredder, Killer Clone", 73, Rarity.RARE, mage.cards.s.SharkShredderKillerClone.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shredder's Revenge", 76, Rarity.COMMON, mage.cards.s.ShreddersRevenge.class));
        cards.add(new SetCardInfo("Shredder's Technique", 232, Rarity.UNCOMMON, mage.cards.s.ShreddersTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shredder's Technique", 77, Rarity.UNCOMMON, mage.cards.s.ShreddersTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shredder, Unrelenting", 210, Rarity.UNCOMMON, mage.cards.s.ShredderUnrelenting.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Shredder, Unrelenting", 74, Rarity.UNCOMMON, mage.cards.s.ShredderUnrelenting.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Skateboard", 178, Rarity.UNCOMMON, mage.cards.s.Skateboard.class));
        cards.add(new SetCardInfo("Slash, Reptile Rampager", 108, Rarity.RARE, mage.cards.s.SlashReptileRampager.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Slash, Reptile Rampager", 208, Rarity.RARE, mage.cards.s.SlashReptileRampager.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Slithering Cryptid", 168, Rarity.COMMON, mage.cards.s.SlitheringCryptid.class));
        cards.add(new SetCardInfo("Slash, Reptile Rampager", 108, Rarity.RARE, mage.cards.s.SlashReptileRampager.class));
        cards.add(new SetCardInfo("South Wind Avatar", 269, Rarity.RARE, mage.cards.s.SouthWindAvatar.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("South Wind Avatar", 78, Rarity.RARE, mage.cards.s.SouthWindAvatar.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Spicy Oatmeal Pizza", 109, Rarity.UNCOMMON, mage.cards.s.SpicyOatmealPizza.class));
        cards.add(new SetCardInfo("Splinter's Technique", 233, Rarity.RARE, mage.cards.s.SplintersTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Splinter's Technique", 80, Rarity.RARE, mage.cards.s.SplintersTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Splinter, Hamato Yoshi", 79, Rarity.UNCOMMON, mage.cards.s.SplinterHamatoYoshi.class));
        cards.add(new SetCardInfo("Splinter, Radical Rat", 169, Rarity.RARE, mage.cards.s.SplinterRadicalRat.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Splinter, Radical Rat", 251, Rarity.RARE, mage.cards.s.SplinterRadicalRat.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Squirrelanoids", 81, Rarity.COMMON, mage.cards.s.Squirrelanoids.class));
        cards.add(new SetCardInfo("Stockman, Mad Fly-entist", 54, Rarity.COMMON, mage.cards.s.StockmanMadFlyEntist.class));
        cards.add(new SetCardInfo("Stomped by the Foot", 82, Rarity.COMMON, mage.cards.s.StompedByTheFoot.class));
        cards.add(new SetCardInfo("Super Shredder", 217, Rarity.MYTHIC, mage.cards.s.SuperShredder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Super Shredder", 285, Rarity.MYTHIC, mage.cards.s.SuperShredder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Super Shredder", 295, Rarity.MYTHIC, mage.cards.s.SuperShredder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Super Shredder", 83, Rarity.MYTHIC, mage.cards.s.SuperShredder.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 193, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 255, Rarity.LAND, mage.cards.basiclands.Swamp.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 307, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 312, Rarity.LAND, mage.cards.basiclands.Swamp.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 317, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("TCRI Building", 189, Rarity.COMMON, mage.cards.t.TCRIBuilding.class));
        cards.add(new SetCardInfo("Tainted Treats", 170, Rarity.UNCOMMON, mage.cards.t.TaintedTreats.class));
        cards.add(new SetCardInfo("Technodrome", 179, Rarity.MYTHIC, mage.cards.t.Technodrome.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Technodrome", 222, Rarity.MYTHIC, mage.cards.t.Technodrome.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Tenderize", 133, Rarity.COMMON, mage.cards.t.Tenderize.class));
        cards.add(new SetCardInfo("The Cloning of Shredder", 60, Rarity.MYTHIC, mage.cards.t.TheCloningOfShredder.class));
        cards.add(new SetCardInfo("The Last Ronin", 154, Rarity.MYTHIC, mage.cards.t.TheLastRonin.class));
        cards.add(new SetCardInfo("The Last Ronin's Technique", 12, Rarity.UNCOMMON, mage.cards.t.TheLastRoninsTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("The Last Ronin's Technique", 223, Rarity.UNCOMMON, mage.cards.t.TheLastRoninsTechnique.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("The Ooze", 177, Rarity.RARE, mage.cards.t.TheOoze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("The Ooze", 277, Rarity.RARE, mage.cards.t.TheOoze.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Tokka & Rahzar, Terrible Twos", 171, Rarity.RARE, mage.cards.t.TokkaAndRahzarTerribleTwos.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Tokka & Rahzar, Terrible Twos", 252, Rarity.RARE, mage.cards.t.TokkaAndRahzarTerribleTwos.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Transdimensional Bovine", 134, Rarity.RARE, mage.cards.t.TransdimensionalBovine.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Transdimensional Bovine", 274, Rarity.RARE, mage.cards.t.TransdimensionalBovine.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Triceraton Commander", 226, Rarity.MYTHIC, mage.cards.t.TriceratonCommander.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Triceraton Commander", 25, Rarity.MYTHIC, mage.cards.t.TriceratonCommander.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Tunnel Rats", 84, Rarity.COMMON, mage.cards.t.TunnelRats.class));
        cards.add(new SetCardInfo("Turncoat Kunoichi", 26, Rarity.RARE, mage.cards.t.TurncoatKunoichi.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Turncoat Kunoichi", 260, Rarity.RARE, mage.cards.t.TurncoatKunoichi.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Turtle Blimp", 180, Rarity.UNCOMMON, mage.cards.t.TurtleBlimp.class));
        cards.add(new SetCardInfo("Turtle Lair", 190, Rarity.UNCOMMON, mage.cards.t.TurtleLair.class));
        cards.add(new SetCardInfo("Turtle Power!", 135, Rarity.RARE, mage.cards.t.TurtlePower.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Turtle Power!", 275, Rarity.RARE, mage.cards.t.TurtlePower.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Turtle Van", 181, Rarity.RARE, mage.cards.t.TurtleVan.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Turtle Van", 278, Rarity.RARE, mage.cards.t.TurtleVan.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Turtles in Time", 263, Rarity.MYTHIC, mage.cards.t.TurtlesInTime.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Turtles in Time", 284, Rarity.MYTHIC, mage.cards.t.TurtlesInTime.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Turtles in Time", 294, Rarity.MYTHIC, mage.cards.t.TurtlesInTime.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Turtles in Time", 55, Rarity.MYTHIC, mage.cards.t.TurtlesInTime.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Uneasy Alliance", 28, Rarity.COMMON, mage.cards.u.UneasyAlliance.class));
        cards.add(new SetCardInfo("Utrom Scientists", 56, Rarity.COMMON, mage.cards.u.UtromScientists.class));
        cards.add(new SetCardInfo("Weather Maker", 182, Rarity.RARE, mage.cards.w.WeatherMaker.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Weather Maker", 279, Rarity.RARE, mage.cards.w.WeatherMaker.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Zog, Triceraton Castaway", 111, Rarity.COMMON, mage.cards.z.ZogTriceratonCastaway.class));
        cards.add(new SetCardInfo("Zoo Escapees", 138, Rarity.COMMON, mage.cards.z.ZooEscapees.class));
    }
}
