package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * https://scryfall.com/sets/slz
 */
public class TheZetaSet extends ExpansionSet {

    private static final TheZetaSet instance = new TheZetaSet();

    public static TheZetaSet getInstance() {
        return instance;
    }

    private TheZetaSet() {
        super("The Zeta Set", "SLZ", ExpansionSet.buildDate(2026, 9, 2), SetType.PROMOTIONAL);
        this.hasBoosters = false;
        this.hasBasicLands = false;

        cards.add(new SetCardInfo("All That Glitters", 1, Rarity.COMMON, mage.cards.a.AllThatGlitters.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("All That Glitters", 122, Rarity.COMMON, mage.cards.a.AllThatGlitters.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("All That Glitters", 243, Rarity.COMMON, mage.cards.a.AllThatGlitters.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("An Offer You Can't Refuse", 148, Rarity.COMMON, mage.cards.a.AnOfferYouCantRefuse.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("An Offer You Can't Refuse", 269, Rarity.COMMON, mage.cards.a.AnOfferYouCantRefuse.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("An Offer You Can't Refuse", 27, Rarity.COMMON, mage.cards.a.AnOfferYouCantRefuse.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Anger", 175, Rarity.UNCOMMON, mage.cards.a.Anger.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Anger", 296, Rarity.UNCOMMON, mage.cards.a.Anger.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Anger", 54, Rarity.UNCOMMON, mage.cards.a.Anger.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Animate Dead", 155, Rarity.UNCOMMON, mage.cards.a.AnimateDead.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Animate Dead", 276, Rarity.UNCOMMON, mage.cards.a.AnimateDead.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Animate Dead", 34, Rarity.UNCOMMON, mage.cards.a.AnimateDead.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Arcane Signet", 215, Rarity.COMMON, mage.cards.a.ArcaneSignet.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Arcane Signet", 336, Rarity.COMMON, mage.cards.a.ArcaneSignet.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Arcane Signet", 94, Rarity.COMMON, mage.cards.a.ArcaneSignet.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ashnod's Altar", 216, Rarity.RARE, mage.cards.a.AshnodsAltar.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ashnod's Altar", 337, Rarity.RARE, mage.cards.a.AshnodsAltar.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ashnod's Altar", 95, Rarity.RARE, mage.cards.a.AshnodsAltar.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Baleful Strix", 209, Rarity.COMMON, mage.cards.b.BalefulStrix.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Baleful Strix", 330, Rarity.COMMON, mage.cards.b.BalefulStrix.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Baleful Strix", 88, Rarity.COMMON, mage.cards.b.BalefulStrix.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Birds of Paradise", 192, Rarity.RARE, mage.cards.b.BirdsOfParadise.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Birds of Paradise", 313, Rarity.RARE, mage.cards.b.BirdsOfParadise.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Birds of Paradise", 71, Rarity.RARE, mage.cards.b.BirdsOfParadise.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Brainstorm", 13, Rarity.COMMON, mage.cards.b.Brainstorm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Brainstorm", 134, Rarity.COMMON, mage.cards.b.Brainstorm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Brainstorm", 255, Rarity.COMMON, mage.cards.b.Brainstorm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cathartic Reunion", 176, Rarity.COMMON, mage.cards.c.CatharticReunion.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cathartic Reunion", 297, Rarity.COMMON, mage.cards.c.CatharticReunion.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cathartic Reunion", 55, Rarity.COMMON, mage.cards.c.CatharticReunion.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cauldron Familiar", 156, Rarity.COMMON, mage.cards.c.CauldronFamiliar.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cauldron Familiar", 277, Rarity.COMMON, mage.cards.c.CauldronFamiliar.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cauldron Familiar", 35, Rarity.COMMON, mage.cards.c.CauldronFamiliar.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chain of Vapor", 135, Rarity.UNCOMMON, mage.cards.c.ChainOfVapor.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chain of Vapor", 14, Rarity.UNCOMMON, mage.cards.c.ChainOfVapor.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chain of Vapor", 256, Rarity.UNCOMMON, mage.cards.c.ChainOfVapor.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chatterstorm", 193, Rarity.COMMON, mage.cards.c.Chatterstorm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chatterstorm", 314, Rarity.COMMON, mage.cards.c.Chatterstorm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chatterstorm", 72, Rarity.COMMON, mage.cards.c.Chatterstorm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chromatic Lantern", 217, Rarity.RARE, mage.cards.c.ChromaticLantern.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chromatic Lantern", 338, Rarity.RARE, mage.cards.c.ChromaticLantern.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chromatic Lantern", 96, Rarity.RARE, mage.cards.c.ChromaticLantern.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chromatic Orrery", 218, Rarity.MYTHIC, mage.cards.c.ChromaticOrrery.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chromatic Orrery", 339, Rarity.MYTHIC, mage.cards.c.ChromaticOrrery.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chromatic Orrery", 97, Rarity.MYTHIC, mage.cards.c.ChromaticOrrery.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chrome Mox", 219, Rarity.MYTHIC, mage.cards.c.ChromeMox.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chrome Mox", 340, Rarity.MYTHIC, mage.cards.c.ChromeMox.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Chrome Mox", 98, Rarity.MYTHIC, mage.cards.c.ChromeMox.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Clone", 136, Rarity.UNCOMMON, mage.cards.c.Clone.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Clone", 15, Rarity.UNCOMMON, mage.cards.c.Clone.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Clone", 257, Rarity.UNCOMMON, mage.cards.c.Clone.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cloud Key", 220, Rarity.UNCOMMON, mage.cards.c.CloudKey.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cloud Key", 341, Rarity.UNCOMMON, mage.cards.c.CloudKey.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cloud Key", 99, Rarity.UNCOMMON, mage.cards.c.CloudKey.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Clown Car", 100, Rarity.UNCOMMON, mage.cards.c.ClownCar.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Clown Car", 221, Rarity.UNCOMMON, mage.cards.c.ClownCar.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Clown Car", 342, Rarity.UNCOMMON, mage.cards.c.ClownCar.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Colossal Dreadmaw", 194, Rarity.COMMON, mage.cards.c.ColossalDreadmaw.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Colossal Dreadmaw", 315, Rarity.COMMON, mage.cards.c.ColossalDreadmaw.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Colossal Dreadmaw", 73, Rarity.COMMON, mage.cards.c.ColossalDreadmaw.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Command Tower", 118, Rarity.COMMON, mage.cards.c.CommandTower.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Command Tower", 239, Rarity.COMMON, mage.cards.c.CommandTower.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Command Tower", 360, Rarity.COMMON, mage.cards.c.CommandTower.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Copper Tablet", 101, Rarity.MYTHIC, mage.cards.c.CopperTablet.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Copper Tablet", 222, Rarity.MYTHIC, mage.cards.c.CopperTablet.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Copper Tablet", 343, Rarity.MYTHIC, mage.cards.c.CopperTablet.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cruel Reality", 157, Rarity.UNCOMMON, mage.cards.c.CruelReality.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cruel Reality", 278, Rarity.UNCOMMON, mage.cards.c.CruelReality.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cruel Reality", 36, Rarity.UNCOMMON, mage.cards.c.CruelReality.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cultivate", 195, Rarity.COMMON, mage.cards.c.Cultivate.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cultivate", 316, Rarity.COMMON, mage.cards.c.Cultivate.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cultivate", 74, Rarity.COMMON, mage.cards.c.Cultivate.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cut Down", 158, Rarity.COMMON, mage.cards.c.CutDown.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cut Down", 279, Rarity.COMMON, mage.cards.c.CutDown.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Cut Down", 37, Rarity.COMMON, mage.cards.c.CutDown.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dark Ritual", 159, Rarity.UNCOMMON, mage.cards.d.DarkRitual.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dark Ritual", 280, Rarity.UNCOMMON, mage.cards.d.DarkRitual.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dark Ritual", 38, Rarity.UNCOMMON, mage.cards.d.DarkRitual.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Darksteel Monolith", 102, Rarity.RARE, mage.cards.d.DarksteelMonolith.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Darksteel Monolith", 223, Rarity.RARE, mage.cards.d.DarksteelMonolith.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Darksteel Monolith", 344, Rarity.RARE, mage.cards.d.DarksteelMonolith.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dig Through Time", 137, Rarity.UNCOMMON, mage.cards.d.DigThroughTime.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dig Through Time", 16, Rarity.UNCOMMON, mage.cards.d.DigThroughTime.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dig Through Time", 258, Rarity.UNCOMMON, mage.cards.d.DigThroughTime.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Disintegrate", 177, Rarity.COMMON, mage.cards.d.Disintegrate.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Disintegrate", 298, Rarity.COMMON, mage.cards.d.Disintegrate.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Disintegrate", 56, Rarity.COMMON, mage.cards.d.Disintegrate.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dispatch", 123, Rarity.COMMON, mage.cards.d.Dispatch.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dispatch", 2, Rarity.COMMON, mage.cards.d.Dispatch.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dispatch", 244, Rarity.COMMON, mage.cards.d.Dispatch.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Doomsday", 160, Rarity.UNCOMMON, mage.cards.d.Doomsday.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Doomsday", 281, Rarity.UNCOMMON, mage.cards.d.Doomsday.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Doomsday", 39, Rarity.UNCOMMON, mage.cards.d.Doomsday.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dueling Grounds", 210, Rarity.RARE, mage.cards.d.DuelingGrounds.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dueling Grounds", 331, Rarity.RARE, mage.cards.d.DuelingGrounds.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Dueling Grounds", 89, Rarity.RARE, mage.cards.d.DuelingGrounds.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Duress", 161, Rarity.COMMON, mage.cards.d.Duress.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Duress", 282, Rarity.COMMON, mage.cards.d.Duress.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Duress", 40, Rarity.COMMON, mage.cards.d.Duress.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Eerie Interlude", 124, Rarity.RARE, mage.cards.e.EerieInterlude.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Eerie Interlude", 245, Rarity.RARE, mage.cards.e.EerieInterlude.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Eerie Interlude", 3, Rarity.RARE, mage.cards.e.EerieInterlude.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Eternity Vessel", 103, Rarity.RARE, mage.cards.e.EternityVessel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Eternity Vessel", 224, Rarity.RARE, mage.cards.e.EternityVessel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Eternity Vessel", 345, Rarity.RARE, mage.cards.e.EternityVessel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Feed the Swarm", 162, Rarity.COMMON, mage.cards.f.FeedTheSwarm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Feed the Swarm", 283, Rarity.COMMON, mage.cards.f.FeedTheSwarm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Feed the Swarm", 41, Rarity.COMMON, mage.cards.f.FeedTheSwarm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Fireball", 178, Rarity.COMMON, mage.cards.f.Fireball.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Fireball", 299, Rarity.COMMON, mage.cards.f.Fireball.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Fireball", 57, Rarity.COMMON, mage.cards.f.Fireball.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Foundry Inspector", 104, Rarity.UNCOMMON, mage.cards.f.FoundryInspector.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Foundry Inspector", 225, Rarity.UNCOMMON, mage.cards.f.FoundryInspector.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Foundry Inspector", 346, Rarity.UNCOMMON, mage.cards.f.FoundryInspector.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Garth One-Eye", 211, Rarity.UNCOMMON, mage.cards.g.GarthOneEye.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Garth One-Eye", 332, Rarity.UNCOMMON, mage.cards.g.GarthOneEye.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Garth One-Eye", 90, Rarity.UNCOMMON, mage.cards.g.GarthOneEye.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Generous Gift", 125, Rarity.COMMON, mage.cards.g.GenerousGift.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Generous Gift", 246, Rarity.COMMON, mage.cards.g.GenerousGift.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Generous Gift", 4, Rarity.COMMON, mage.cards.g.GenerousGift.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ghostly Flicker", 138, Rarity.COMMON, mage.cards.g.GhostlyFlicker.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ghostly Flicker", 17, Rarity.COMMON, mage.cards.g.GhostlyFlicker.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ghostly Flicker", 259, Rarity.COMMON, mage.cards.g.GhostlyFlicker.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Giant Spider", 196, Rarity.COMMON, mage.cards.g.GiantSpider.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Giant Spider", 317, Rarity.COMMON, mage.cards.g.GiantSpider.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Giant Spider", 75, Rarity.COMMON, mage.cards.g.GiantSpider.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Gigantosaurus", 197, Rarity.COMMON, mage.cards.g.Gigantosaurus.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Gigantosaurus", 318, Rarity.COMMON, mage.cards.g.Gigantosaurus.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Gigantosaurus", 76, Rarity.COMMON, mage.cards.g.Gigantosaurus.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Glimpse the Impossible", 179, Rarity.UNCOMMON, mage.cards.g.GlimpseTheImpossible.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Glimpse the Impossible", 300, Rarity.UNCOMMON, mage.cards.g.GlimpseTheImpossible.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Glimpse the Impossible", 58, Rarity.UNCOMMON, mage.cards.g.GlimpseTheImpossible.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Go for the Throat", 163, Rarity.COMMON, mage.cards.g.GoForTheThroat.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Go for the Throat", 284, Rarity.COMMON, mage.cards.g.GoForTheThroat.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Go for the Throat", 42, Rarity.COMMON, mage.cards.g.GoForTheThroat.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Gray Merchant of Asphodel", 164, Rarity.COMMON, mage.cards.g.GrayMerchantOfAsphodel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Gray Merchant of Asphodel", 285, Rarity.COMMON, mage.cards.g.GrayMerchantOfAsphodel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Gray Merchant of Asphodel", 43, Rarity.COMMON, mage.cards.g.GrayMerchantOfAsphodel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Grizzly Bears", 198, Rarity.COMMON, mage.cards.g.GrizzlyBears.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Grizzly Bears", 319, Rarity.COMMON, mage.cards.g.GrizzlyBears.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Grizzly Bears", 77, Rarity.COMMON, mage.cards.g.GrizzlyBears.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Gut Shot", 180, Rarity.COMMON, mage.cards.g.GutShot.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Gut Shot", 301, Rarity.COMMON, mage.cards.g.GutShot.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Gut Shot", 59, Rarity.COMMON, mage.cards.g.GutShot.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Guttersnipe", 181, Rarity.COMMON, mage.cards.g.Guttersnipe.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Guttersnipe", 302, Rarity.COMMON, mage.cards.g.Guttersnipe.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Guttersnipe", 60, Rarity.COMMON, mage.cards.g.Guttersnipe.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("High Tide", 139, Rarity.COMMON, mage.cards.h.HighTide.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("High Tide", 18, Rarity.COMMON, mage.cards.h.HighTide.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("High Tide", 260, Rarity.COMMON, mage.cards.h.HighTide.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Hornet Queen", 199, Rarity.UNCOMMON, mage.cards.h.HornetQueen.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Hornet Queen", 320, Rarity.UNCOMMON, mage.cards.h.HornetQueen.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Hornet Queen", 78, Rarity.UNCOMMON, mage.cards.h.HornetQueen.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Hullbreaker Horror", 140, Rarity.RARE, mage.cards.h.HullbreakerHorror.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Hullbreaker Horror", 19, Rarity.RARE, mage.cards.h.HullbreakerHorror.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Hullbreaker Horror", 261, Rarity.RARE, mage.cards.h.HullbreakerHorror.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Hypnotic Specter", 165, Rarity.UNCOMMON, mage.cards.h.HypnoticSpecter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Hypnotic Specter", 286, Rarity.UNCOMMON, mage.cards.h.HypnoticSpecter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Hypnotic Specter", 44, Rarity.UNCOMMON, mage.cards.h.HypnoticSpecter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Imp's Mischief", 166, Rarity.RARE, mage.cards.i.ImpsMischief.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Imp's Mischief", 287, Rarity.RARE, mage.cards.i.ImpsMischief.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Imp's Mischief", 45, Rarity.RARE, mage.cards.i.ImpsMischief.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Imperial Recruiter", 182, Rarity.RARE, mage.cards.i.ImperialRecruiter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Imperial Recruiter", 303, Rarity.RARE, mage.cards.i.ImperialRecruiter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Imperial Recruiter", 61, Rarity.RARE, mage.cards.i.ImperialRecruiter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Imprisoned in the Moon", 141, Rarity.UNCOMMON, mage.cards.i.ImprisonedInTheMoon.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Imprisoned in the Moon", 20, Rarity.UNCOMMON, mage.cards.i.ImprisonedInTheMoon.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Imprisoned in the Moon", 262, Rarity.UNCOMMON, mage.cards.i.ImprisonedInTheMoon.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Invigorate", 200, Rarity.COMMON, mage.cards.i.Invigorate.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Invigorate", 321, Rarity.COMMON, mage.cards.i.Invigorate.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Invigorate", 79, Rarity.COMMON, mage.cards.i.Invigorate.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Jester's Cap", 105, Rarity.UNCOMMON, mage.cards.j.JestersCap.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Jester's Cap", 226, Rarity.UNCOMMON, mage.cards.j.JestersCap.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Jester's Cap", 347, Rarity.UNCOMMON, mage.cards.j.JestersCap.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Kazuul, Tyrant of the Cliffs", 183, Rarity.UNCOMMON, mage.cards.k.KazuulTyrantOfTheCliffs.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Kazuul, Tyrant of the Cliffs", 304, Rarity.UNCOMMON, mage.cards.k.KazuulTyrantOfTheCliffs.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Kazuul, Tyrant of the Cliffs", 62, Rarity.UNCOMMON, mage.cards.k.KazuulTyrantOfTheCliffs.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Laboratory Maniac", 142, Rarity.UNCOMMON, mage.cards.l.LaboratoryManiac.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Laboratory Maniac", 21, Rarity.UNCOMMON, mage.cards.l.LaboratoryManiac.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Laboratory Maniac", 263, Rarity.UNCOMMON, mage.cards.l.LaboratoryManiac.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Land Tax", 126, Rarity.RARE, mage.cards.l.LandTax.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Land Tax", 247, Rarity.RARE, mage.cards.l.LandTax.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Land Tax", 5, Rarity.RARE, mage.cards.l.LandTax.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Life from the Loam", 201, Rarity.RARE, mage.cards.l.LifeFromTheLoam.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Life from the Loam", 322, Rarity.RARE, mage.cards.l.LifeFromTheLoam.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Life from the Loam", 80, Rarity.RARE, mage.cards.l.LifeFromTheLoam.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Lightning Bolt", 184, Rarity.COMMON, mage.cards.l.LightningBolt.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Lightning Bolt", 305, Rarity.COMMON, mage.cards.l.LightningBolt.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Lightning Bolt", 63, Rarity.COMMON, mage.cards.l.LightningBolt.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Llanowar Elves", 202, Rarity.COMMON, mage.cards.l.LlanowarElves.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Llanowar Elves", 323, Rarity.COMMON, mage.cards.l.LlanowarElves.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Llanowar Elves", 81, Rarity.COMMON, mage.cards.l.LlanowarElves.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Lord Skitter, Sewer King", 167, Rarity.UNCOMMON, mage.cards.l.LordSkitterSewerKing.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Lord Skitter, Sewer King", 288, Rarity.UNCOMMON, mage.cards.l.LordSkitterSewerKing.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Lord Skitter, Sewer King", 46, Rarity.UNCOMMON, mage.cards.l.LordSkitterSewerKing.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mana Echoes", 185, Rarity.MYTHIC, mage.cards.m.ManaEchoes.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mana Echoes", 306, Rarity.MYTHIC, mage.cards.m.ManaEchoes.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mana Echoes", 64, Rarity.MYTHIC, mage.cards.m.ManaEchoes.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Manifold Key", 106, Rarity.UNCOMMON, mage.cards.m.ManifoldKey.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Manifold Key", 227, Rarity.UNCOMMON, mage.cards.m.ManifoldKey.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Manifold Key", 348, Rarity.UNCOMMON, mage.cards.m.ManifoldKey.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mental Misstep", 143, Rarity.UNCOMMON, mage.cards.m.MentalMisstep.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mental Misstep", 22, Rarity.UNCOMMON, mage.cards.m.MentalMisstep.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mental Misstep", 264, Rarity.UNCOMMON, mage.cards.m.MentalMisstep.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Merchant Scroll", 144, Rarity.UNCOMMON, mage.cards.m.MerchantScroll.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Merchant Scroll", 23, Rarity.UNCOMMON, mage.cards.m.MerchantScroll.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Merchant Scroll", 265, Rarity.UNCOMMON, mage.cards.m.MerchantScroll.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Merfolk of the Pearl Trident", 145, Rarity.COMMON, mage.cards.m.MerfolkOfThePearlTrident.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Merfolk of the Pearl Trident", 24, Rarity.COMMON, mage.cards.m.MerfolkOfThePearlTrident.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Merfolk of the Pearl Trident", 266, Rarity.COMMON, mage.cards.m.MerfolkOfThePearlTrident.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mortuary", 168, Rarity.MYTHIC, mage.cards.m.Mortuary.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mortuary", 289, Rarity.MYTHIC, mage.cards.m.Mortuary.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mortuary", 47, Rarity.MYTHIC, mage.cards.m.Mortuary.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mother of Runes", 127, Rarity.UNCOMMON, mage.cards.m.MotherOfRunes.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mother of Runes", 248, Rarity.UNCOMMON, mage.cards.m.MotherOfRunes.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mother of Runes", 6, Rarity.UNCOMMON, mage.cards.m.MotherOfRunes.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mox Tantalite", 107, Rarity.MYTHIC, mage.cards.m.MoxTantalite.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mox Tantalite", 228, Rarity.MYTHIC, mage.cards.m.MoxTantalite.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mox Tantalite", 349, Rarity.MYTHIC, mage.cards.m.MoxTantalite.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mulldrifter", 146, Rarity.COMMON, mage.cards.m.Mulldrifter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mulldrifter", 25, Rarity.COMMON, mage.cards.m.Mulldrifter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mulldrifter", 267, Rarity.COMMON, mage.cards.m.Mulldrifter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mycosynth Golem", 108, Rarity.RARE, mage.cards.m.MycosynthGolem.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mycosynth Golem", 229, Rarity.RARE, mage.cards.m.MycosynthGolem.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Mycosynth Golem", 350, Rarity.RARE, mage.cards.m.MycosynthGolem.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Narcomoeba", 147, Rarity.COMMON, mage.cards.n.Narcomoeba.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Narcomoeba", 26, Rarity.COMMON, mage.cards.n.Narcomoeba.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Narcomoeba", 268, Rarity.COMMON, mage.cards.n.Narcomoeba.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Nature's Claim", 203, Rarity.COMMON, mage.cards.n.NaturesClaim.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Nature's Claim", 324, Rarity.COMMON, mage.cards.n.NaturesClaim.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Nature's Claim", 82, Rarity.COMMON, mage.cards.n.NaturesClaim.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Night's Whisper", 169, Rarity.COMMON, mage.cards.n.NightsWhisper.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Night's Whisper", 290, Rarity.COMMON, mage.cards.n.NightsWhisper.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Night's Whisper", 48, Rarity.COMMON, mage.cards.n.NightsWhisper.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Obeka, Brute Chronologist", 213, Rarity.UNCOMMON, mage.cards.o.ObekaBruteChronologist.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Obeka, Brute Chronologist", 334, Rarity.UNCOMMON, mage.cards.o.ObekaBruteChronologist.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Obeka, Brute Chronologist", 92, Rarity.UNCOMMON, mage.cards.o.ObekaBruteChronologist.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Oboro, Palace in the Clouds", 119, Rarity.RARE, mage.cards.o.OboroPalaceInTheClouds.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Oboro, Palace in the Clouds", 240, Rarity.RARE, mage.cards.o.OboroPalaceInTheClouds.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Oboro, Palace in the Clouds", 361, Rarity.RARE, mage.cards.o.OboroPalaceInTheClouds.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ornithopter", 109, Rarity.COMMON, mage.cards.o.Ornithopter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ornithopter", 230, Rarity.COMMON, mage.cards.o.Ornithopter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ornithopter", 351, Rarity.COMMON, mage.cards.o.Ornithopter.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Panoptic Mirror", 110, Rarity.MYTHIC, mage.cards.p.PanopticMirror.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Panoptic Mirror", 231, Rarity.MYTHIC, mage.cards.p.PanopticMirror.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Panoptic Mirror", 352, Rarity.MYTHIC, mage.cards.p.PanopticMirror.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Path to Exile", 128, Rarity.UNCOMMON, mage.cards.p.PathToExile.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Path to Exile", 249, Rarity.UNCOMMON, mage.cards.p.PathToExile.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Path to Exile", 7, Rarity.UNCOMMON, mage.cards.p.PathToExile.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Power Sink", 149, Rarity.COMMON, mage.cards.p.PowerSink.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Power Sink", 270, Rarity.COMMON, mage.cards.p.PowerSink.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Power Sink", 28, Rarity.COMMON, mage.cards.p.PowerSink.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Price of Progress", 186, Rarity.COMMON, mage.cards.p.PriceOfProgress.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Price of Progress", 307, Rarity.COMMON, mage.cards.p.PriceOfProgress.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Price of Progress", 65, Rarity.COMMON, mage.cards.p.PriceOfProgress.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Pyroblast", 187, Rarity.UNCOMMON, mage.cards.p.Pyroblast.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Pyroblast", 308, Rarity.UNCOMMON, mage.cards.p.Pyroblast.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Pyroblast", 66, Rarity.UNCOMMON, mage.cards.p.Pyroblast.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Pyrokinesis", 188, Rarity.UNCOMMON, mage.cards.p.Pyrokinesis.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Pyrokinesis", 309, Rarity.UNCOMMON, mage.cards.p.Pyrokinesis.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Pyrokinesis", 67, Rarity.UNCOMMON, mage.cards.p.Pyrokinesis.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Quicksilver Elemental", 150, Rarity.MYTHIC, mage.cards.q.QuicksilverElemental.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Quicksilver Elemental", 271, Rarity.MYTHIC, mage.cards.q.QuicksilverElemental.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Quicksilver Elemental", 29, Rarity.MYTHIC, mage.cards.q.QuicksilverElemental.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Raffine, Scheming Seer", 214, Rarity.UNCOMMON, mage.cards.r.RaffineSchemingSeer.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Raffine, Scheming Seer", 335, Rarity.UNCOMMON, mage.cards.r.RaffineSchemingSeer.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Raffine, Scheming Seer", 93, Rarity.UNCOMMON, mage.cards.r.RaffineSchemingSeer.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Reliquary Tower", 120, Rarity.UNCOMMON, mage.cards.r.ReliquaryTower.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Reliquary Tower", 241, Rarity.UNCOMMON, mage.cards.r.ReliquaryTower.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Reliquary Tower", 362, Rarity.UNCOMMON, mage.cards.r.ReliquaryTower.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Return to Dust", 129, Rarity.COMMON, mage.cards.r.ReturnToDust.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Return to Dust", 250, Rarity.COMMON, mage.cards.r.ReturnToDust.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Return to Dust", 8, Rarity.COMMON, mage.cards.r.ReturnToDust.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Rogue's Gloves", 111, Rarity.UNCOMMON, mage.cards.r.RoguesGloves.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Rogue's Gloves", 232, Rarity.UNCOMMON, mage.cards.r.RoguesGloves.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Rogue's Gloves", 353, Rarity.UNCOMMON, mage.cards.r.RoguesGloves.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ruxa, Patient Professor", 204, Rarity.UNCOMMON, mage.cards.r.RuxaPatientProfessor.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ruxa, Patient Professor", 325, Rarity.UNCOMMON, mage.cards.r.RuxaPatientProfessor.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ruxa, Patient Professor", 83, Rarity.UNCOMMON, mage.cards.r.RuxaPatientProfessor.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Savannah Lions", 130, Rarity.COMMON, mage.cards.s.SavannahLions.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Savannah Lions", 251, Rarity.COMMON, mage.cards.s.SavannahLions.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Savannah Lions", 9, Rarity.COMMON, mage.cards.s.SavannahLions.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Scute Swarm", 205, Rarity.RARE, mage.cards.s.ScuteSwarm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Scute Swarm", 326, Rarity.RARE, mage.cards.s.ScuteSwarm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Scute Swarm", 84, Rarity.RARE, mage.cards.s.ScuteSwarm.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Scythecat Cub", 206, Rarity.MYTHIC, mage.cards.s.ScythecatCub.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Scythecat Cub", 327, Rarity.MYTHIC, mage.cards.s.ScythecatCub.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Scythecat Cub", 85, Rarity.MYTHIC, mage.cards.s.ScythecatCub.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Sengir Vampire", 170, Rarity.COMMON, mage.cards.s.SengirVampire.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Sengir Vampire", 291, Rarity.COMMON, mage.cards.s.SengirVampire.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Sengir Vampire", 49, Rarity.COMMON, mage.cards.s.SengirVampire.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Sensei's Divining Top", 112, Rarity.RARE, mage.cards.s.SenseisDiviningTop.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Sensei's Divining Top", 233, Rarity.RARE, mage.cards.s.SenseisDiviningTop.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Sensei's Divining Top", 354, Rarity.RARE, mage.cards.s.SenseisDiviningTop.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Serra Angel", 10, Rarity.COMMON, mage.cards.s.SerraAngel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Serra Angel", 131, Rarity.COMMON, mage.cards.s.SerraAngel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Serra Angel", 252, Rarity.COMMON, mage.cards.s.SerraAngel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Simian Spirit Guide", 189, Rarity.COMMON, mage.cards.s.SimianSpiritGuide.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Simian Spirit Guide", 310, Rarity.COMMON, mage.cards.s.SimianSpiritGuide.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Simian Spirit Guide", 68, Rarity.COMMON, mage.cards.s.SimianSpiritGuide.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Skullclamp", 113, Rarity.RARE, mage.cards.s.Skullclamp.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Skullclamp", 234, Rarity.RARE, mage.cards.s.Skullclamp.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Skullclamp", 355, Rarity.RARE, mage.cards.s.Skullclamp.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Sol Ring", 114, Rarity.UNCOMMON, mage.cards.s.SolRing.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Sol Ring", 235, Rarity.UNCOMMON, mage.cards.s.SolRing.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Sol Ring", 356, Rarity.UNCOMMON, mage.cards.s.SolRing.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Soul-Guide Lantern", 115, Rarity.COMMON, mage.cards.s.SoulGuideLantern.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Soul-Guide Lantern", 236, Rarity.COMMON, mage.cards.s.SoulGuideLantern.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Soul-Guide Lantern", 357, Rarity.COMMON, mage.cards.s.SoulGuideLantern.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Spell Pierce", 151, Rarity.COMMON, mage.cards.s.SpellPierce.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Spell Pierce", 272, Rarity.COMMON, mage.cards.s.SpellPierce.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Spell Pierce", 30, Rarity.COMMON, mage.cards.s.SpellPierce.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Split Up", 11, Rarity.RARE, mage.cards.s.SplitUp.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Split Up", 132, Rarity.RARE, mage.cards.s.SplitUp.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Split Up", 253, Rarity.RARE, mage.cards.s.SplitUp.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("The Jolly Balloon Man", 212, Rarity.UNCOMMON, mage.cards.t.TheJollyBalloonMan.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("The Jolly Balloon Man", 333, Rarity.UNCOMMON, mage.cards.t.TheJollyBalloonMan.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("The Jolly Balloon Man", 91, Rarity.UNCOMMON, mage.cards.t.TheJollyBalloonMan.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Thought Scour", 152, Rarity.COMMON, mage.cards.t.ThoughtScour.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Thought Scour", 273, Rarity.COMMON, mage.cards.t.ThoughtScour.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Thought Scour", 31, Rarity.COMMON, mage.cards.t.ThoughtScour.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Thought Vessel", 116, Rarity.COMMON, mage.cards.t.ThoughtVessel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Thought Vessel", 237, Rarity.COMMON, mage.cards.t.ThoughtVessel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Thought Vessel", 358, Rarity.COMMON, mage.cards.t.ThoughtVessel.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Thrummingbird", 153, Rarity.UNCOMMON, mage.cards.t.Thrummingbird.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Thrummingbird", 274, Rarity.UNCOMMON, mage.cards.t.Thrummingbird.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Thrummingbird", 32, Rarity.UNCOMMON, mage.cards.t.Thrummingbird.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Tragic Slip", 171, Rarity.COMMON, mage.cards.t.TragicSlip.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Tragic Slip", 292, Rarity.COMMON, mage.cards.t.TragicSlip.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Tragic Slip", 50, Rarity.COMMON, mage.cards.t.TragicSlip.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Unearth", 172, Rarity.COMMON, mage.cards.u.Unearth.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Unearth", 293, Rarity.COMMON, mage.cards.u.Unearth.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Unearth", 51, Rarity.COMMON, mage.cards.u.Unearth.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Urborg, Tomb of Yawgmoth", 121, Rarity.MYTHIC, mage.cards.u.UrborgTombOfYawgmoth.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Urborg, Tomb of Yawgmoth", 242, Rarity.MYTHIC, mage.cards.u.UrborgTombOfYawgmoth.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Urborg, Tomb of Yawgmoth", 363, Rarity.MYTHIC, mage.cards.u.UrborgTombOfYawgmoth.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Vandalblast", 190, Rarity.COMMON, mage.cards.v.Vandalblast.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Vandalblast", 311, Rarity.COMMON, mage.cards.v.Vandalblast.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Vandalblast", 69, Rarity.COMMON, mage.cards.v.Vandalblast.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Vito, Thorn of the Dusk Rose", 173, Rarity.RARE, mage.cards.v.VitoThornOfTheDuskRose.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Vito, Thorn of the Dusk Rose", 294, Rarity.RARE, mage.cards.v.VitoThornOfTheDuskRose.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Vito, Thorn of the Dusk Rose", 52, Rarity.RARE, mage.cards.v.VitoThornOfTheDuskRose.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ward of Bones", 117, Rarity.RARE, mage.cards.w.WardOfBones.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ward of Bones", 238, Rarity.RARE, mage.cards.w.WardOfBones.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Ward of Bones", 359, Rarity.RARE, mage.cards.w.WardOfBones.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Wheel of Misfortune", 191, Rarity.UNCOMMON, mage.cards.w.WheelOfMisfortune.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Wheel of Misfortune", 312, Rarity.UNCOMMON, mage.cards.w.WheelOfMisfortune.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Wheel of Misfortune", 70, Rarity.UNCOMMON, mage.cards.w.WheelOfMisfortune.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("White Sun's Zenith", 12, Rarity.UNCOMMON, mage.cards.w.WhiteSunsZenith.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("White Sun's Zenith", 133, Rarity.UNCOMMON, mage.cards.w.WhiteSunsZenith.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("White Sun's Zenith", 254, Rarity.UNCOMMON, mage.cards.w.WhiteSunsZenith.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Wild Growth", 207, Rarity.COMMON, mage.cards.w.WildGrowth.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Wild Growth", 328, Rarity.COMMON, mage.cards.w.WildGrowth.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Wild Growth", 86, Rarity.COMMON, mage.cards.w.WildGrowth.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Wild Nacatl", 208, Rarity.COMMON, mage.cards.w.WildNacatl.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Wild Nacatl", 329, Rarity.COMMON, mage.cards.w.WildNacatl.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Wild Nacatl", 87, Rarity.COMMON, mage.cards.w.WildNacatl.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Windfall", 154, Rarity.UNCOMMON, mage.cards.w.Windfall.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Windfall", 275, Rarity.UNCOMMON, mage.cards.w.Windfall.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Windfall", 33, Rarity.UNCOMMON, mage.cards.w.Windfall.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Yargle, Glutton of Urborg", 174, Rarity.UNCOMMON, mage.cards.y.YargleGluttonOfUrborg.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Yargle, Glutton of Urborg", 295, Rarity.UNCOMMON, mage.cards.y.YargleGluttonOfUrborg.class, FULL_ART_USE_VARIOUS));
        cards.add(new SetCardInfo("Yargle, Glutton of Urborg", 53, Rarity.UNCOMMON, mage.cards.y.YargleGluttonOfUrborg.class, FULL_ART_USE_VARIOUS));
    }
}
