services:
  server:
    build: .
    image: ghcr.io/magefree/mage
    ports:
      - '17171:17171'
      - '17179:17179'
    extra_hosts:
      # Adjust this to configure the server for your deployment URL (`localhost` -> `yourDomain.com`)
      - 'localhost:0.0.0.0'
    environment:
      # Adjust this to configure the server for your deployment URL (`localhost` -> `yourDomain.com`)
      - MAGE_SERVER_ADDRESS=localhost
      # Give the server a name, if you want to
      - MAGE_SERVER_NAME=mage-server
      - MAGE_MAX_SECONDS_IDLE=6000
      - MAGE_AUTHENTICATION_ACTIVATED=false
    volumes:
      - xmage-db:/xmage/db
      - xmage-saved:/xmage/saved
volumes:
  xmage-db:
  xmage-saved:
