package mage.deck;

/**
 * @author LevelX2
 */
public class DuelCommander extends Commander {

    public DuelCommander() {
        super("Duel Commander");
        banned.add("Ancestral Recall");
        banned.add("Ancient Tomb");
        banned.add("Back to Basics");
        banned.add("Bazaar of Baghdad");
        banned.add("Black Lotus");
        banned.add("Capture of Jingzhou");
        banned.add("Cavern of Souls");
        banned.add("Channel");
        banned.add("Chrome Mox");
        banned.add("Deflecting Swat");
        banned.add("Dig Through Time");
        banned.add("Eidolon of the Great Revel");
        banned.add("Emrakul, the Aeons Torn");
        banned.add("Entomb");
        banned.add("Fastbond");
        banned.add("Field of the Dead");
        banned.add("Fierce Guardianship");
        banned.add("Food Chain");
        banned.add("Gaea's Cradle");
        banned.add("Genesis Storm");
        banned.add("Gifts Ungiven");
        banned.add("Grim Monolith");
        banned.add("Hermit Druid");
        banned.add("High Tide");
        banned.add("Humility");
        banned.add("Imperial Seal");
        banned.add("Jeweled Lotus");
        banned.add("Karakas");
        banned.add("Library of Alexandria");
        banned.add("Lion's Eye Diamond");
        banned.add("Loyal Retainers");
        banned.add("Lutri, the Spellchaser");
        banned.add("Maddening Hex");
        banned.add("Mana Crypt");
        banned.add("Mana Drain");
        banned.add("Mana Vault");
        banned.add("Mishra's Workshop");
        banned.add("Mox Diamond");
        banned.add("Mox Emerald");
        banned.add("Mox Jet");
        banned.add("Mox Opal");
        banned.add("Mox Pearl");
        banned.add("Mox Ruby");
        banned.add("Mox Sapphire");
        banned.add("Mystical Tutor");
        banned.add("Natural Order");
        banned.add("Necrotic Ooze");
        banned.add("Oath of Druids");
        banned.add("Polymorph");
        banned.add("Price of Progress");
        banned.add("Protean Hulk");
        banned.add("Ragavan, Nimble Pilferer");
        banned.add("Scapeshift");
        banned.add("Sensei's Divining Top");
        banned.add("Serra's Sanctum");
        banned.add("Sol Ring");
        banned.add("Strip Mine");
        banned.add("Temporal Manipulation");
        banned.add("Thassa's Oracle");
        banned.add("The Tabernacle at Pendrell Vale");
        banned.add("Timetwister");
        banned.add("Time Vault");
        banned.add("Time Walk");
        banned.add("Time Warp");
        banned.add("Tinker");
        banned.add("Tolarian Academy");
        banned.add("Treasure Cruise");
        banned.add("Uro, Titan of Nature's Wrath");
        banned.add("Vampiric Tutor");
        banned.add("Wasteland");

        bannedCommander.add("Akiri, Line-Slinger");
        bannedCommander.add("Arahbo, Roar of the World");
        bannedCommander.add("Ardenn, Intrepid Archaeologist");
        bannedCommander.add("Asmoranomardicadaistinaculdacar");
        bannedCommander.add("Baral, Chief of Compliance");
        bannedCommander.add("Breya, Etherium Shaper");
        bannedCommander.add("Derevi, Empyrial Tactician");
        bannedCommander.add("Edgar Markov");
        bannedCommander.add("Edric, Spymaster of Trest");
        bannedCommander.add("Emry, Lurker of the Loch");
        bannedCommander.add("Esior, Wardwing Familiar");
        bannedCommander.add("Geist of Saint Traft");
        bannedCommander.add("Inalla, Archmage Ritualist");
        bannedCommander.add("Krark, the Thumbless");
        bannedCommander.add("Minsc & Boo, Timeless Heroes");
        bannedCommander.add("Najeela, the Blade-Blossom");
        bannedCommander.add("Oloro, Ageless Ascetic");
        bannedCommander.add("Omnath, Locus of Creation");
        bannedCommander.add("Prime Speaker Vannifar");
        bannedCommander.add("Rofellos, Llanowar Emissary");
        bannedCommander.add("Shorikai, Genesis Engine");
        bannedCommander.add("Tasigur, the Golden Fang");
        bannedCommander.add("Thrasios, Triton Hero");
        bannedCommander.add("Urza, Lord High Artificer");
        bannedCommander.add("Vial Smasher the Fierce");
        bannedCommander.add("Winota, Joiner of Forces");
        bannedCommander.add("Yuriko, the Tiger's Shadow");
        bannedCommander.add("Zurgo Bellstriker");
    }
}
