# default-config.yaml

goes_first: random  # player_a, player_b, random

player_a:
  deckPath: decks/UWTempo.dck
  type: mcts
  #output_file: data/playerA/AvsB.hdf5

  priors:
    priority: false
    target: false
    binary: false
    opponent: false
    prior_temperature: 1.5

  noise:
    enabled: false
    dirichlet_noise: 0.15 #does nothing
    selection_temperature: 2 #does nothing

  mcts:
    search_budget: 1000
    timeout_ms: 4000
    td_discount: 0.85
    offline_mode: false

  gameplay:
    mulligans_enabled: false
    manual_tapping: false


  hidden_info:
    see_opponent_hand: true

player_b:
  deckPath: decks/Standard-MonoR.dck
  type: mcts
  #output_file: data/playerB/BvsA.hdf5

  priors:
    priority: false
    target: false
    binary: false
    opponent: false
    prior_temperature: 1.5

  noise:
    enabled: false
    dirichlet_noise: 0.15 #does nothing
    selection_temperature: 2 #does nothing

  mcts:
    search_budget: 1000
    timeout_ms: 4000
    td_discount: 0.85
    offline_mode: false

  gameplay:
    mulligans_enabled: false
    manual_tapping: false


  hidden_info:
    see_opponent_hand: true

training:
  games: 100
  threads: 4
  max_turns: 50 #does nothing

server:
  host: localhost
  port: 50052 #50052
  opponent_port: 50053 #50053

logging:
  sparse: false #does nothing
  all_threads: true
  log_feature_hash: false
  save_final_wr: true
  show_mcts_info: true #does nothing
