/*
* Copyright 2010 BetaSteward_at_googlemail.com. All rights reserved.
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*    1. Redistributions of source code must retain the above copyright notice, this list of
*       conditions and the following disclaimer.
*
*    2. Redistributions in binary form must reproduce the above copyright notice, this list
*       of conditions and the following disclaimer in the documentation and/or other materials
*       provided with the distribution.
*
* THIS SOFTWARE IS PROVIDED BY BetaSteward_at_googlemail.com ``AS IS'' AND ANY EXPRESS OR IMPLIED
* WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
* FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL BetaSteward_at_googlemail.com OR
* CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
* ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
* The views and conclusions contained in the software and documentation are those of the
* authors and should not be interpreted as representing official policies, either expressed
* or implied, of BetaSteward_at_googlemail.com.
*/
package mage.tournament.cubes;

import mage.game.draft.DraftCube;

/**
 *
 * @author LevelX2
 */
public class CubeTutor720 extends DraftCube {

    public CubeTutor720() {
        super("Cube Tutor 720");

        cubeCards.add(new CardIdentity("Elite Vanguard",""));
        cubeCards.add(new CardIdentity("Gideon's Lawkeeper",""));
        cubeCards.add(new CardIdentity("Isamaru, Hound of Konda",""));
        cubeCards.add(new CardIdentity("Loam Lion",""));
        cubeCards.add(new CardIdentity("Mother of Runes",""));
        cubeCards.add(new CardIdentity("Savannah Lions",""));
        cubeCards.add(new CardIdentity("Soldier of the Pantheon",""));
        cubeCards.add(new CardIdentity("Steppe Lynx",""));
        cubeCards.add(new CardIdentity("Student of Warfare",""));
        cubeCards.add(new CardIdentity("Weathered Wayfarer",""));
        cubeCards.add(new CardIdentity("Accorder Paladin",""));
        cubeCards.add(new CardIdentity("Cloistered Youth",""));
        cubeCards.add(new CardIdentity("Eight-and-a-Half-Tails",""));
        cubeCards.add(new CardIdentity("Imposing Sovereign",""));
        cubeCards.add(new CardIdentity("Knight of Glory",""));
        cubeCards.add(new CardIdentity("Knight of Meadowgrain",""));
        cubeCards.add(new CardIdentity("Kor Skyfisher",""));
        cubeCards.add(new CardIdentity("Leonin Relic-Warder",""));
        cubeCards.add(new CardIdentity("Lone Missionary",""));
        cubeCards.add(new CardIdentity("Precinct Captain",""));
        cubeCards.add(new CardIdentity("Soltari Monk",""));
        cubeCards.add(new CardIdentity("Soltari Priest",""));
        cubeCards.add(new CardIdentity("Soltari Trooper",""));
        cubeCards.add(new CardIdentity("Stoneforge Mystic",""));
        cubeCards.add(new CardIdentity("Thalia, Guardian of Thraben",""));
        cubeCards.add(new CardIdentity("Wall of Omens",""));
        cubeCards.add(new CardIdentity("Banisher Priest",""));
        cubeCards.add(new CardIdentity("Blade Splicer",""));
        cubeCards.add(new CardIdentity("Fiend Hunter",""));
        cubeCards.add(new CardIdentity("Flickerwisp",""));
        cubeCards.add(new CardIdentity("Frontline Medic",""));
        cubeCards.add(new CardIdentity("Kor Sanctifiers",""));
        cubeCards.add(new CardIdentity("Mentor of the Meek",""));
        cubeCards.add(new CardIdentity("Mirran Crusader",""));
        cubeCards.add(new CardIdentity("Mirror Entity",""));
        cubeCards.add(new CardIdentity("Silverblade Paladin",""));
        cubeCards.add(new CardIdentity("Soltari Champion",""));
        cubeCards.add(new CardIdentity("Stonecloaker",""));
        cubeCards.add(new CardIdentity("Emeria Angel",""));
        cubeCards.add(new CardIdentity("Hero of Bladehold",""));
        cubeCards.add(new CardIdentity("Ranger of Eos",""));
        cubeCards.add(new CardIdentity("Restoration Angel",""));
        cubeCards.add(new CardIdentity("Sublime Archangel",""));
        cubeCards.add(new CardIdentity("Baneslayer Angel",""));
        cubeCards.add(new CardIdentity("Cloudgoat Ranger",""));
        cubeCards.add(new CardIdentity("Geist-Honored Monk",""));
        cubeCards.add(new CardIdentity("Karmic Guide",""));
        cubeCards.add(new CardIdentity("Reveillark",""));
        cubeCards.add(new CardIdentity("Exalted Angel",""));
        cubeCards.add(new CardIdentity("Mikaeus, the Lunarch",""));
        cubeCards.add(new CardIdentity("Sun Titan",""));
        cubeCards.add(new CardIdentity("Yosei, the Morning Star",""));
        cubeCards.add(new CardIdentity("Angel of Serenity",""));
        cubeCards.add(new CardIdentity("Elesh Norn, Grand Cenobite",""));
        cubeCards.add(new CardIdentity("Eternal Dragon",""));
        cubeCards.add(new CardIdentity("Akroma, Angel of Wrath",""));
        cubeCards.add(new CardIdentity("Ajani, Caller of the Pride",""));
        cubeCards.add(new CardIdentity("Ajani Goldmane",""));
        cubeCards.add(new CardIdentity("Elspeth, Knight-Errant",""));
        cubeCards.add(new CardIdentity("Elspeth Tirel",""));
        cubeCards.add(new CardIdentity("Gideon Jura",""));
        cubeCards.add(new CardIdentity("Elspeth, Sun's Champion",""));
        cubeCards.add(new CardIdentity("Porcelain Legionnaire",""));
        cubeCards.add(new CardIdentity("Condemn",""));
        cubeCards.add(new CardIdentity("Enlightened Tutor",""));
        cubeCards.add(new CardIdentity("Mana Tithe",""));
        cubeCards.add(new CardIdentity("Path to Exile",""));
        cubeCards.add(new CardIdentity("Swords to Plowshares",""));
        cubeCards.add(new CardIdentity("Disenchant",""));
        cubeCards.add(new CardIdentity("Momentary Blink",""));
        cubeCards.add(new CardIdentity("Balance",""));
        cubeCards.add(new CardIdentity("Lingering Souls",""));
        cubeCards.add(new CardIdentity("Spectral Procession",""));
        cubeCards.add(new CardIdentity("Armageddon",""));
        cubeCards.add(new CardIdentity("Day of Judgment",""));
        cubeCards.add(new CardIdentity("Wrath of God",""));
        cubeCards.add(new CardIdentity("Akroma's Vengeance",""));
        cubeCards.add(new CardIdentity("Catastrophe",""));
        cubeCards.add(new CardIdentity("Terminus",""));
        cubeCards.add(new CardIdentity("Martial Coup",""));
        cubeCards.add(new CardIdentity("Entreat the Angels",""));
        cubeCards.add(new CardIdentity("Decree of Justice",""));
        cubeCards.add(new CardIdentity("Land Tax",""));
        cubeCards.add(new CardIdentity("Honor of the Pure",""));
        cubeCards.add(new CardIdentity("Journey to Nowhere",""));
        cubeCards.add(new CardIdentity("Pacifism",""));
        cubeCards.add(new CardIdentity("Seal of Cleansing",""));
        cubeCards.add(new CardIdentity("Glorious Anthem",""));
        cubeCards.add(new CardIdentity("Oblivion Ring",""));
        cubeCards.add(new CardIdentity("Angelic Destiny",""));
        cubeCards.add(new CardIdentity("Faith's Fetters",""));
        cubeCards.add(new CardIdentity("Parallax Wave",""));
        cubeCards.add(new CardIdentity("Spear of Heliod",""));
        cubeCards.add(new CardIdentity("Delver of Secrets",""));
        cubeCards.add(new CardIdentity("Enclave Cryptologist",""));
        cubeCards.add(new CardIdentity("Augur of Bolas",""));
        cubeCards.add(new CardIdentity("Gilded Drake",""));
        cubeCards.add(new CardIdentity("Looter il-Kor",""));
        cubeCards.add(new CardIdentity("Merfolk Looter",""));
        cubeCards.add(new CardIdentity("Phantasmal Image",""));
        cubeCards.add(new CardIdentity("Snapcaster Mage",""));
        cubeCards.add(new CardIdentity("Waterfront Bouncer",""));
        cubeCards.add(new CardIdentity("Willbender",""));
        cubeCards.add(new CardIdentity("Aether Adept",""));
        cubeCards.add(new CardIdentity("Kira, Great Glass-Spinner",""));
        cubeCards.add(new CardIdentity("Man-o'-War",""));
        cubeCards.add(new CardIdentity("Pestermite",""));
        cubeCards.add(new CardIdentity("Sea Gate Oracle",""));
        cubeCards.add(new CardIdentity("Serendib Efreet",""));
        cubeCards.add(new CardIdentity("Trinket Mage",""));
        cubeCards.add(new CardIdentity("Vendilion Clique",""));
        cubeCards.add(new CardIdentity("Clone",""));
        cubeCards.add(new CardIdentity("Dungeon Geists",""));
        cubeCards.add(new CardIdentity("Glen Elendra Archmage",""));
        cubeCards.add(new CardIdentity("Ninja of the Deep Hours",""));
        cubeCards.add(new CardIdentity("Sower of Temptation",""));
        cubeCards.add(new CardIdentity("Talrand, Sky Summoner",""));
        cubeCards.add(new CardIdentity("Venser, Shaper Savant",""));
        cubeCards.add(new CardIdentity("Meloku the Clouded Mirror",""));
        cubeCards.add(new CardIdentity("Mulldrifter",""));
        cubeCards.add(new CardIdentity("Riftwing Cloudskate",""));
        cubeCards.add(new CardIdentity("Teferi, Mage of Zhalfir",""));
        cubeCards.add(new CardIdentity("Aetherling",""));
        cubeCards.add(new CardIdentity("Consecrated Sphinx",""));
        cubeCards.add(new CardIdentity("Frost Titan",""));
        cubeCards.add(new CardIdentity("Keiga, the Tide Star",""));
        cubeCards.add(new CardIdentity("Sphinx of Jwar Isle",""));
        cubeCards.add(new CardIdentity("Jace Beleren",""));
        cubeCards.add(new CardIdentity("Jace, Architect of Thought",""));
        cubeCards.add(new CardIdentity("Jace, the Mind Sculptor",""));
        cubeCards.add(new CardIdentity("Tamiyo, the Moon Sage",""));
        cubeCards.add(new CardIdentity("Tezzeret the Seeker",""));
        cubeCards.add(new CardIdentity("Phyrexian Metamorph",""));
        cubeCards.add(new CardIdentity("Inkwell Leviathan",""));
        cubeCards.add(new CardIdentity("Ancestral Recall",""));
        cubeCards.add(new CardIdentity("Brainstorm",""));
        cubeCards.add(new CardIdentity("Force Spike",""));
        cubeCards.add(new CardIdentity("Mystical Tutor",""));
        cubeCards.add(new CardIdentity("Spell Pierce",""));
        cubeCards.add(new CardIdentity("Arcane Denial",""));
        cubeCards.add(new CardIdentity("Counterspell",""));
        cubeCards.add(new CardIdentity("Cyclonic Rift",""));
        cubeCards.add(new CardIdentity("Daze",""));
        cubeCards.add(new CardIdentity("Impulse",""));
        cubeCards.add(new CardIdentity("Into the Roil",""));
        cubeCards.add(new CardIdentity("Mana Drain",""));
        cubeCards.add(new CardIdentity("Mana Leak",""));
        cubeCards.add(new CardIdentity("Memory Lapse",""));
        cubeCards.add(new CardIdentity("Miscalculation",""));
        cubeCards.add(new CardIdentity("Negate",""));
        cubeCards.add(new CardIdentity("Remand",""));
        cubeCards.add(new CardIdentity("Capsize",""));
        cubeCards.add(new CardIdentity("Dissipate",""));
        cubeCards.add(new CardIdentity("Forbid",""));
        cubeCards.add(new CardIdentity("Forbidden Alchemy",""));
        cubeCards.add(new CardIdentity("Frantic Search",""));
        cubeCards.add(new CardIdentity("Psionic Blast",""));
        cubeCards.add(new CardIdentity("Thirst for Knowledge",""));
        cubeCards.add(new CardIdentity("Cryptic Command",""));
        cubeCards.add(new CardIdentity("Fact or Fiction",""));
        cubeCards.add(new CardIdentity("Gifts Ungiven",""));
        cubeCards.add(new CardIdentity("Force of Will",""));
        cubeCards.add(new CardIdentity("Pact of Negation",""));
        cubeCards.add(new CardIdentity("Condescend",""));
        cubeCards.add(new CardIdentity("Repeal",""));
        cubeCards.add(new CardIdentity("Ancestral Vision",""));
        cubeCards.add(new CardIdentity("Ponder",""));
        cubeCards.add(new CardIdentity("Preordain",""));
        cubeCards.add(new CardIdentity("Time Walk",""));
        cubeCards.add(new CardIdentity("Compulsive Research",""));
        cubeCards.add(new CardIdentity("Show and Tell",""));
        cubeCards.add(new CardIdentity("Tinker",""));
        cubeCards.add(new CardIdentity("Deep Analysis",""));
        cubeCards.add(new CardIdentity("Bribery",""));
        cubeCards.add(new CardIdentity("Time Warp",""));
        cubeCards.add(new CardIdentity("Time Spiral",""));
        cubeCards.add(new CardIdentity("Upheaval",""));
        cubeCards.add(new CardIdentity("Control Magic",""));
        cubeCards.add(new CardIdentity("Opposition",""));
        cubeCards.add(new CardIdentity("Treachery",""));
        cubeCards.add(new CardIdentity("Thassa, God of the Sea",""));
        cubeCards.add(new CardIdentity("Carnophage",""));
        cubeCards.add(new CardIdentity("Carrion Feeder",""));
        cubeCards.add(new CardIdentity("Diregraf Ghoul",""));
        cubeCards.add(new CardIdentity("Gravecrawler",""));
        cubeCards.add(new CardIdentity("Tormented Hero",""));
        cubeCards.add(new CardIdentity("Vampire Lacerator",""));
        cubeCards.add(new CardIdentity("Blood Artist",""));
        cubeCards.add(new CardIdentity("Blood Scrivener",""));
        cubeCards.add(new CardIdentity("Bloodghast",""));
        cubeCards.add(new CardIdentity("Dark Confidant",""));
        cubeCards.add(new CardIdentity("Dauthi Horror",""));
        cubeCards.add(new CardIdentity("Gatekeeper of Malakir",""));
        cubeCards.add(new CardIdentity("Knight of Infamy",""));
        cubeCards.add(new CardIdentity("Nantuko Shade",""));
        cubeCards.add(new CardIdentity("Nezumi Graverobber",""));
        cubeCards.add(new CardIdentity("Oona's Prowler",""));
        cubeCards.add(new CardIdentity("Pack Rat",""));
        cubeCards.add(new CardIdentity("Reassembling Skeleton",""));
        cubeCards.add(new CardIdentity("Vampire Hexmage",""));
        cubeCards.add(new CardIdentity("Bone Shredder",""));
        cubeCards.add(new CardIdentity("Fleshbag Marauder",""));
        cubeCards.add(new CardIdentity("Geralf's Messenger",""));
        cubeCards.add(new CardIdentity("Hypnotic Specter",""));
        cubeCards.add(new CardIdentity("Phyrexian Rager",""));
        cubeCards.add(new CardIdentity("Vampire Nighthawk",""));
        cubeCards.add(new CardIdentity("Abyssal Persecutor",""));
        cubeCards.add(new CardIdentity("Bane of the Living",""));
        cubeCards.add(new CardIdentity("Bloodline Keeper",""));
        cubeCards.add(new CardIdentity("Braids, Cabal Minion",""));
        cubeCards.add(new CardIdentity("Crypt Ghast",""));
        cubeCards.add(new CardIdentity("Desecration Demon",""));
        cubeCards.add(new CardIdentity("Disciple of Bolas",""));
        cubeCards.add(new CardIdentity("Graveborn Muse",""));
        cubeCards.add(new CardIdentity("Nekrataal",""));
        cubeCards.add(new CardIdentity("Skinrender",""));
        cubeCards.add(new CardIdentity("Bloodgift Demon",""));
        cubeCards.add(new CardIdentity("Shriekmaw",""));
        cubeCards.add(new CardIdentity("Grave Titan",""));
        cubeCards.add(new CardIdentity("Ink-Eyes, Servant of Oni",""));
        cubeCards.add(new CardIdentity("Kokusho, the Evening Star",""));
        cubeCards.add(new CardIdentity("Massacre Wurm",""));
        cubeCards.add(new CardIdentity("Sheoldred, Whispering One",""));
        cubeCards.add(new CardIdentity("Griselbrand",""));
        cubeCards.add(new CardIdentity("Tombstalker",""));
        cubeCards.add(new CardIdentity("Liliana of the Veil",""));
        cubeCards.add(new CardIdentity("Liliana Vess",""));
        cubeCards.add(new CardIdentity("Sorin Markov",""));
        cubeCards.add(new CardIdentity("Dark Ritual",""));
        cubeCards.add(new CardIdentity("Entomb",""));
        cubeCards.add(new CardIdentity("Tragic Slip",""));
        cubeCards.add(new CardIdentity("Vampiric Tutor",""));
        cubeCards.add(new CardIdentity("Diabolic Edict",""));
        cubeCards.add(new CardIdentity("Doom Blade",""));
        cubeCards.add(new CardIdentity("Go for the Throat",""));
        cubeCards.add(new CardIdentity("Ultimate Price",""));
        cubeCards.add(new CardIdentity("Dismember",""));
        cubeCards.add(new CardIdentity("Hero's Downfall",""));
        cubeCards.add(new CardIdentity("Slaughter Pact",""));
        cubeCards.add(new CardIdentity("Makeshift Mannequin",""));
        cubeCards.add(new CardIdentity("Snuff Out",""));
        cubeCards.add(new CardIdentity("Duress",""));
        cubeCards.add(new CardIdentity("Innocent Blood",""));
        cubeCards.add(new CardIdentity("Inquisition of Kozilek",""));
        cubeCards.add(new CardIdentity("Reanimate",""));
        cubeCards.add(new CardIdentity("Thoughtseize",""));
        cubeCards.add(new CardIdentity("Chainer's Edict",""));
        cubeCards.add(new CardIdentity("Demonic Tutor",""));
        cubeCards.add(new CardIdentity("Exhume",""));
        cubeCards.add(new CardIdentity("Hymn to Tourach",""));
        cubeCards.add(new CardIdentity("Night's Whisper",""));
        cubeCards.add(new CardIdentity("Sign in Blood",""));
        cubeCards.add(new CardIdentity("Sinkhole",""));
        cubeCards.add(new CardIdentity("Smallpox",""));
        cubeCards.add(new CardIdentity("Buried Alive",""));
        cubeCards.add(new CardIdentity("Yawgmoth's Will",""));
        cubeCards.add(new CardIdentity("Barter in Blood",""));
        cubeCards.add(new CardIdentity("Consuming Vapors",""));
        cubeCards.add(new CardIdentity("Damnation",""));
        cubeCards.add(new CardIdentity("Living Death",""));
        cubeCards.add(new CardIdentity("Unburial Rites",""));
        cubeCards.add(new CardIdentity("Mind Twist",""));
        cubeCards.add(new CardIdentity("Black Sun's Zenith",""));
        cubeCards.add(new CardIdentity("Profane Command",""));
        cubeCards.add(new CardIdentity("Sarcomancy",""));
        cubeCards.add(new CardIdentity("Animate Dead",""));
        cubeCards.add(new CardIdentity("Bitterblossom",""));
        cubeCards.add(new CardIdentity("Necromancy",""));
        cubeCards.add(new CardIdentity("Necropotence",""));
        cubeCards.add(new CardIdentity("Phyrexian Arena",""));
        cubeCards.add(new CardIdentity("Recurring Nightmare",""));
        cubeCards.add(new CardIdentity("Diabolic Servitude",""));
        cubeCards.add(new CardIdentity("Firedrinker Satyr",""));
        cubeCards.add(new CardIdentity("Goblin Guide",""));
        cubeCards.add(new CardIdentity("Goblin Welder",""));
        cubeCards.add(new CardIdentity("Grim Lavamancer",""));
        cubeCards.add(new CardIdentity("Jackal Pup",""));
        cubeCards.add(new CardIdentity("Kird Ape",""));
        cubeCards.add(new CardIdentity("Legion Loyalist",""));
        cubeCards.add(new CardIdentity("Mogg Fanatic",""));
        cubeCards.add(new CardIdentity("Reckless Waif",""));
        cubeCards.add(new CardIdentity("Spikeshot Elder",""));
        cubeCards.add(new CardIdentity("Stromkirk Noble",""));
        cubeCards.add(new CardIdentity("Ash Zealot",""));
        cubeCards.add(new CardIdentity("Ember Hauler",""));
        cubeCards.add(new CardIdentity("Gore-House Chainwalker",""));
        cubeCards.add(new CardIdentity("Hellspark Elemental",""));
        cubeCards.add(new CardIdentity("Kargan Dragonlord",""));
        cubeCards.add(new CardIdentity("Keldon Marauders",""));
        cubeCards.add(new CardIdentity("Lightning Mauler",""));
        cubeCards.add(new CardIdentity("Mogg War Marshal",""));
        cubeCards.add(new CardIdentity("Plated Geopede",""));
        cubeCards.add(new CardIdentity("Stormblood Berserker",""));
        cubeCards.add(new CardIdentity("Torch Fiend",""));
        cubeCards.add(new CardIdentity("Young Pyromancer",""));
        cubeCards.add(new CardIdentity("Ball Lightning",""));
        cubeCards.add(new CardIdentity("Chandra's Phoenix",""));
        cubeCards.add(new CardIdentity("Countryside Crusher",""));
        cubeCards.add(new CardIdentity("Goblin Ruinblaster",""));
        cubeCards.add(new CardIdentity("Guttersnipe",""));
        cubeCards.add(new CardIdentity("Hell's Thunder",""));
        cubeCards.add(new CardIdentity("Manic Vandal",""));
        cubeCards.add(new CardIdentity("Squee, Goblin Nabob",""));
        cubeCards.add(new CardIdentity("Zo-Zu the Punisher",""));
        cubeCards.add(new CardIdentity("Avalanche Riders",""));
        cubeCards.add(new CardIdentity("Blistering Firecat",""));
        cubeCards.add(new CardIdentity("Flametongue Kavu",""));
        cubeCards.add(new CardIdentity("Hellrider",""));
        cubeCards.add(new CardIdentity("Hero of Oxid Ridge",""));
        cubeCards.add(new CardIdentity("Keldon Champion",""));
        cubeCards.add(new CardIdentity("Kiki-Jiki, Mirror Breaker",""));
        cubeCards.add(new CardIdentity("Siege-Gang Commander",""));
        cubeCards.add(new CardIdentity("Thundermaw Hellkite",""));
        cubeCards.add(new CardIdentity("Zealous Conscripts",""));
        cubeCards.add(new CardIdentity("Inferno Titan",""));
        cubeCards.add(new CardIdentity("Bogardan Hellkite",""));
        cubeCards.add(new CardIdentity("Greater Gargadon",""));
        cubeCards.add(new CardIdentity("Chandra, Pyromaster",""));
        cubeCards.add(new CardIdentity("Chandra, the Firebrand",""));
        cubeCards.add(new CardIdentity("Koth of the Hammer",""));
        cubeCards.add(new CardIdentity("Chandra Nalaar",""));
        cubeCards.add(new CardIdentity("Burst Lightning",""));
        cubeCards.add(new CardIdentity("Lightning Bolt",""));
        cubeCards.add(new CardIdentity("Ancient Grudge",""));
        cubeCards.add(new CardIdentity("Incinerate",""));
        cubeCards.add(new CardIdentity("Lightning Strike",""));
        cubeCards.add(new CardIdentity("Magma Jet",""));
        cubeCards.add(new CardIdentity("Searing Blaze",""));
        cubeCards.add(new CardIdentity("Searing Spear",""));
        cubeCards.add(new CardIdentity("Smash to Smithereens",""));
        cubeCards.add(new CardIdentity("Brimstone Volley",""));
        cubeCards.add(new CardIdentity("Chaos Warp",""));
        cubeCards.add(new CardIdentity("Char",""));
        cubeCards.add(new CardIdentity("Flame Javelin",""));
        cubeCards.add(new CardIdentity("Staggershock",""));
        cubeCards.add(new CardIdentity("Fireblast",""));
        cubeCards.add(new CardIdentity("Chain Lightning",""));
        cubeCards.add(new CardIdentity("Faithless Looting",""));
        cubeCards.add(new CardIdentity("Firebolt",""));
        cubeCards.add(new CardIdentity("Reckless Charge",""));
        cubeCards.add(new CardIdentity("Arc Trail",""));
        cubeCards.add(new CardIdentity("Mizzium Mortars",""));
        cubeCards.add(new CardIdentity("Pyroclasm",""));
        cubeCards.add(new CardIdentity("Arc Lightning",""));
        cubeCards.add(new CardIdentity("Flames of the Firebrand",""));
        cubeCards.add(new CardIdentity("Molten Rain",""));
        cubeCards.add(new CardIdentity("Pillage",""));
        cubeCards.add(new CardIdentity("Rift Bolt",""));
        cubeCards.add(new CardIdentity("Slagstorm",""));
        cubeCards.add(new CardIdentity("Stone Rain",""));
        cubeCards.add(new CardIdentity("Wheel of Fortune",""));
        cubeCards.add(new CardIdentity("Banefire",""));
        cubeCards.add(new CardIdentity("Devil's Play",""));
        cubeCards.add(new CardIdentity("Earthquake",""));
        cubeCards.add(new CardIdentity("Fireball",""));
        cubeCards.add(new CardIdentity("Wildfire",""));
        cubeCards.add(new CardIdentity("Bonfire of the Damned",""));
        cubeCards.add(new CardIdentity("Sulfuric Vortex",""));
        cubeCards.add(new CardIdentity("Sneak Attack",""));
        cubeCards.add(new CardIdentity("Arbor Elf",""));
        cubeCards.add(new CardIdentity("Avacyn's Pilgrim",""));
        cubeCards.add(new CardIdentity("Birds of Paradise",""));
        cubeCards.add(new CardIdentity("Elves of Deep Shadow",""));
        cubeCards.add(new CardIdentity("Elvish Mystic",""));
        cubeCards.add(new CardIdentity("Experiment One",""));
        cubeCards.add(new CardIdentity("Fyndhorn Elves",""));
        cubeCards.add(new CardIdentity("Joraga Treespeaker",""));
        cubeCards.add(new CardIdentity("Llanowar Elves",""));
        cubeCards.add(new CardIdentity("Noble Hierarch",""));
        cubeCards.add(new CardIdentity("Ulvenwald Tracker",""));
        cubeCards.add(new CardIdentity("Wild Nacatl",""));
        cubeCards.add(new CardIdentity("Fauna Shaman",""));
        cubeCards.add(new CardIdentity("Lotus Cobra",""));
        cubeCards.add(new CardIdentity("Mayor of Avabruck",""));
        cubeCards.add(new CardIdentity("River Boa",""));
        cubeCards.add(new CardIdentity("Rofellos, Llanowar Emissary",""));
        cubeCards.add(new CardIdentity("Sakura-Tribe Elder",""));
        cubeCards.add(new CardIdentity("Scavenging Ooze",""));
        cubeCards.add(new CardIdentity("Strangleroot Geist",""));
        cubeCards.add(new CardIdentity("Sylvan Caryatid",""));
        cubeCards.add(new CardIdentity("Tarmogoyf",""));
        cubeCards.add(new CardIdentity("Wall of Blossoms",""));
        cubeCards.add(new CardIdentity("Wall of Roots",""));
        cubeCards.add(new CardIdentity("Wild Mongrel",""));
        cubeCards.add(new CardIdentity("Eternal Witness",""));
        cubeCards.add(new CardIdentity("Ohran Viper",""));
        cubeCards.add(new CardIdentity("Troll Ascetic",""));
        cubeCards.add(new CardIdentity("Uktabi Orangutan",""));
        cubeCards.add(new CardIdentity("Viridian Shaman",""));
        cubeCards.add(new CardIdentity("Wolfir Avenger",""));
        cubeCards.add(new CardIdentity("Yavimaya Elder",""));
        cubeCards.add(new CardIdentity("Blastoderm",""));
        cubeCards.add(new CardIdentity("Chameleon Colossus",""));
        cubeCards.add(new CardIdentity("Deadbridge Goliath",""));
        cubeCards.add(new CardIdentity("Master of the Wild Hunt",""));
        cubeCards.add(new CardIdentity("Obstinate Baloth",""));
        cubeCards.add(new CardIdentity("Oracle of Mul Daya",""));
        cubeCards.add(new CardIdentity("Polukranos, World Eater",""));
        cubeCards.add(new CardIdentity("Thrun, the Last Troll",""));
        cubeCards.add(new CardIdentity("Vengevine",""));
        cubeCards.add(new CardIdentity("Wickerbough Elder",""));
        cubeCards.add(new CardIdentity("Acidic Slime",""));
        cubeCards.add(new CardIdentity("Deranged Hermit",""));
        cubeCards.add(new CardIdentity("Genesis",""));
        cubeCards.add(new CardIdentity("Indrik Stomphowler",""));
        cubeCards.add(new CardIdentity("Kalonian Hydra",""));
        cubeCards.add(new CardIdentity("Thragtusk",""));
        cubeCards.add(new CardIdentity("Vorapede",""));
        cubeCards.add(new CardIdentity("Wolfir Silverheart",""));
        cubeCards.add(new CardIdentity("Primeval Titan",""));
        cubeCards.add(new CardIdentity("Rampaging Baloths",""));
        cubeCards.add(new CardIdentity("Avenger of Zendikar",""));
        cubeCards.add(new CardIdentity("Hornet Queen",""));
        cubeCards.add(new CardIdentity("Krosan Tusker",""));
        cubeCards.add(new CardIdentity("Craterhoof Behemoth",""));
        cubeCards.add(new CardIdentity("Terastodon",""));
        cubeCards.add(new CardIdentity("Woodfall Primus",""));
        cubeCards.add(new CardIdentity("Garruk Relentless",""));
        cubeCards.add(new CardIdentity("Garruk Wildspeaker",""));
        cubeCards.add(new CardIdentity("Garruk, Primal Hunter",""));
        cubeCards.add(new CardIdentity("Birthing Pod",""));
        cubeCards.add(new CardIdentity("Giant Growth",""));
        cubeCards.add(new CardIdentity("Vines of Vastwood",""));
        cubeCards.add(new CardIdentity("Worldly Tutor",""));
        cubeCards.add(new CardIdentity("Naturalize",""));
        cubeCards.add(new CardIdentity("Beast Within",""));
        cubeCards.add(new CardIdentity("Harrow",""));
        cubeCards.add(new CardIdentity("Krosan Grip",""));
        cubeCards.add(new CardIdentity("Channel",""));
        cubeCards.add(new CardIdentity("Explore",""));
        cubeCards.add(new CardIdentity("Farseek",""));
        cubeCards.add(new CardIdentity("Life from the Loam",""));
        cubeCards.add(new CardIdentity("Rampant Growth",""));
        cubeCards.add(new CardIdentity("Regrowth",""));
        cubeCards.add(new CardIdentity("Call of the Herd",""));
        cubeCards.add(new CardIdentity("Cultivate",""));
        cubeCards.add(new CardIdentity("Kodama's Reach",""));
        cubeCards.add(new CardIdentity("Search for Tomorrow",""));
        cubeCards.add(new CardIdentity("Harmonize",""));
        cubeCards.add(new CardIdentity("Natural Order",""));
        cubeCards.add(new CardIdentity("Overrun",""));
        cubeCards.add(new CardIdentity("Plow Under",""));
        cubeCards.add(new CardIdentity("Primal Command",""));
        cubeCards.add(new CardIdentity("Green Sun's Zenith",""));
        cubeCards.add(new CardIdentity("Tooth and Nail",""));
        cubeCards.add(new CardIdentity("Rancor",""));
        cubeCards.add(new CardIdentity("Survival of the Fittest",""));
        cubeCards.add(new CardIdentity("Sylvan Library",""));
        cubeCards.add(new CardIdentity("Awakening Zone",""));
        cubeCards.add(new CardIdentity("Boon Satyr",""));
        cubeCards.add(new CardIdentity("Geist of Saint Traft",""));
        cubeCards.add(new CardIdentity("Grand Arbiter Augustin IV",""));
        cubeCards.add(new CardIdentity("Venser, the Sojourner",""));
        cubeCards.add(new CardIdentity("Azorius Charm",""));
        cubeCards.add(new CardIdentity("Sphinx's Revelation",""));
        cubeCards.add(new CardIdentity("Supreme Verdict",""));
        cubeCards.add(new CardIdentity("Detention Sphere",""));
        cubeCards.add(new CardIdentity("Psychatog",""));
        cubeCards.add(new CardIdentity("Shadowmage Infiltrator",""));
        cubeCards.add(new CardIdentity("Duskmantle Seer",""));
        cubeCards.add(new CardIdentity("Oona, Queen of the Fae",""));
        cubeCards.add(new CardIdentity("Tezzeret, Agent of Bolas",""));
        cubeCards.add(new CardIdentity("Baleful Strix",""));
        cubeCards.add(new CardIdentity("Far // Away",""));
        cubeCards.add(new CardIdentity("Rakdos Cackler",""));
        cubeCards.add(new CardIdentity("Spike Jester",""));
        cubeCards.add(new CardIdentity("Falkenrath Aristocrat",""));
        cubeCards.add(new CardIdentity("Murderous Redcap",""));
        cubeCards.add(new CardIdentity("Olivia Voldaren",""));
        cubeCards.add(new CardIdentity("Terminate",""));
        cubeCards.add(new CardIdentity("Bituminous Blast",""));
        cubeCards.add(new CardIdentity("Dreadbore",""));
        cubeCards.add(new CardIdentity("Blightning",""));
        cubeCards.add(new CardIdentity("Burning-Tree Emissary",""));
        cubeCards.add(new CardIdentity("Boggart Ram-Gang",""));
        cubeCards.add(new CardIdentity("Bloodbraid Elf",""));
        cubeCards.add(new CardIdentity("Ghor-Clan Rampager",""));
        cubeCards.add(new CardIdentity("Huntmaster of the Fells",""));
        cubeCards.add(new CardIdentity("Domri Rade",""));
        cubeCards.add(new CardIdentity("Sarkhan Vol",""));
        cubeCards.add(new CardIdentity("Xenagos, the Reveler",""));
        cubeCards.add(new CardIdentity("Dryad Militant",""));
        cubeCards.add(new CardIdentity("Qasali Pridemage",""));
        cubeCards.add(new CardIdentity("Voice of Resurgence",""));
        cubeCards.add(new CardIdentity("Kitchen Finks",""));
        cubeCards.add(new CardIdentity("Knight of the Reliquary",""));
        cubeCards.add(new CardIdentity("Loxodon Smiter",""));
        cubeCards.add(new CardIdentity("Armada Wurm",""));
        cubeCards.add(new CardIdentity("Selesnya Charm",""));
        cubeCards.add(new CardIdentity("Mirari's Wake",""));
        cubeCards.add(new CardIdentity("Obzedat, Ghost Council",""));
        cubeCards.add(new CardIdentity("Angel of Despair",""));
        cubeCards.add(new CardIdentity("Sorin, Lord of Innistrad",""));
        cubeCards.add(new CardIdentity("Tidehollow Sculler",""));
        cubeCards.add(new CardIdentity("Mortify",""));
        cubeCards.add(new CardIdentity("Vindicate",""));
        cubeCards.add(new CardIdentity("Deathrite Shaman",""));
        cubeCards.add(new CardIdentity("Lotleth Troll",""));
        cubeCards.add(new CardIdentity("Putrid Leech",""));
        cubeCards.add(new CardIdentity("Dreg Mangler",""));
        cubeCards.add(new CardIdentity("Varolz, the Scar-Striped",""));
        cubeCards.add(new CardIdentity("Vraska the Unseen",""));
        cubeCards.add(new CardIdentity("Abrupt Decay",""));
        cubeCards.add(new CardIdentity("Putrefy",""));
        cubeCards.add(new CardIdentity("Maelstrom Pulse",""));
        cubeCards.add(new CardIdentity("Pernicious Deed",""));
        cubeCards.add(new CardIdentity("Coiling Oracle",""));
        cubeCards.add(new CardIdentity("Edric, Spymaster of Trest",""));
        cubeCards.add(new CardIdentity("Trygon Predator",""));
        cubeCards.add(new CardIdentity("Mystic Snake",""));
        cubeCards.add(new CardIdentity("Prime Speaker Zegana",""));
        cubeCards.add(new CardIdentity("Simic Sky Swallower",""));
        cubeCards.add(new CardIdentity("Shardless Agent",""));
        cubeCards.add(new CardIdentity("Simic Charm",""));
        cubeCards.add(new CardIdentity("Niv-Mizzet, Dracogenius",""));
        cubeCards.add(new CardIdentity("Ral Zarek",""));
        cubeCards.add(new CardIdentity("Fire // Ice",""));
        cubeCards.add(new CardIdentity("Izzet Charm",""));
        cubeCards.add(new CardIdentity("Turn // Burn",""));
        cubeCards.add(new CardIdentity("Electrolyze",""));
        cubeCards.add(new CardIdentity("Steam Augury",""));
        cubeCards.add(new CardIdentity("Prophetic Bolt",""));
        cubeCards.add(new CardIdentity("Figure of Destiny",""));
        cubeCards.add(new CardIdentity("Boros Reckoner",""));
        cubeCards.add(new CardIdentity("Ajani Vengeant",""));
        cubeCards.add(new CardIdentity("Boros Charm",""));
        cubeCards.add(new CardIdentity("Lightning Helix",""));
        cubeCards.add(new CardIdentity("Assemble the Legion",""));
        cubeCards.add(new CardIdentity("Sphinx of the Steel Wind",""));
        cubeCards.add(new CardIdentity("Nicol Bolas, Planeswalker",""));
        cubeCards.add(new CardIdentity("Kozilek, Butcher of Truth",""));
        cubeCards.add(new CardIdentity("Ulamog, the Infinite Gyre",""));
        cubeCards.add(new CardIdentity("Karn Liberated",""));
        cubeCards.add(new CardIdentity("Epochrasite",""));
        cubeCards.add(new CardIdentity("Perilous Myr",""));
        cubeCards.add(new CardIdentity("Phyrexian Revoker",""));
        cubeCards.add(new CardIdentity("Spellskite",""));
        cubeCards.add(new CardIdentity("Palladium Myr",""));
        cubeCards.add(new CardIdentity("Lodestone Golem",""));
        cubeCards.add(new CardIdentity("Masticore",""));
        cubeCards.add(new CardIdentity("Molten-Tail Masticore",""));
        cubeCards.add(new CardIdentity("Solemn Simulacrum",""));
        cubeCards.add(new CardIdentity("Precursor Golem",""));
        cubeCards.add(new CardIdentity("Razormane Masticore",""));
        cubeCards.add(new CardIdentity("Duplicant",""));
        cubeCards.add(new CardIdentity("Steel Hellkite",""));
        cubeCards.add(new CardIdentity("Triskelion",""));
        cubeCards.add(new CardIdentity("Wurmcoil Engine",""));
        cubeCards.add(new CardIdentity("Myr Battlesphere",""));
        cubeCards.add(new CardIdentity("Sundering Titan",""));
        cubeCards.add(new CardIdentity("Black Lotus",""));
        cubeCards.add(new CardIdentity("Chrome Mox",""));
        cubeCards.add(new CardIdentity("Everflowing Chalice",""));
        cubeCards.add(new CardIdentity("Lotus Bloom",""));
        cubeCards.add(new CardIdentity("Mana Crypt",""));
        cubeCards.add(new CardIdentity("Mox Diamond",""));
        cubeCards.add(new CardIdentity("Mox Emerald",""));
        cubeCards.add(new CardIdentity("Mox Jet",""));
        cubeCards.add(new CardIdentity("Mox Pearl",""));
        cubeCards.add(new CardIdentity("Mox Ruby",""));
        cubeCards.add(new CardIdentity("Mox Sapphire",""));
        cubeCards.add(new CardIdentity("Aether Vial",""));
        cubeCards.add(new CardIdentity("Basilisk Collar",""));
        cubeCards.add(new CardIdentity("Black Vise",""));
        cubeCards.add(new CardIdentity("Bonesplitter",""));
        cubeCards.add(new CardIdentity("Cursed Scroll",""));
        cubeCards.add(new CardIdentity("Mana Vault",""));
        cubeCards.add(new CardIdentity("Pithing Needle",""));
        cubeCards.add(new CardIdentity("Relic of Progenitus",""));
        cubeCards.add(new CardIdentity("Sensei's Divining Top",""));
        cubeCards.add(new CardIdentity("Skullclamp",""));
        cubeCards.add(new CardIdentity("Sol Ring",""));
        cubeCards.add(new CardIdentity("Ankh of Mishra",""));
        cubeCards.add(new CardIdentity("Azorius Signet",""));
        cubeCards.add(new CardIdentity("Boros Signet",""));
        cubeCards.add(new CardIdentity("Coldsteel Heart",""));
        cubeCards.add(new CardIdentity("Dimir Signet",""));
        cubeCards.add(new CardIdentity("Golgari Signet",""));
        cubeCards.add(new CardIdentity("Grim Monolith",""));
        cubeCards.add(new CardIdentity("Gruul Signet",""));
        cubeCards.add(new CardIdentity("Isochron Scepter",""));
        cubeCards.add(new CardIdentity("Izzet Signet",""));
        cubeCards.add(new CardIdentity("Lightning Greaves",""));
        cubeCards.add(new CardIdentity("Mind Stone",""));
        cubeCards.add(new CardIdentity("Mortarpod",""));
        cubeCards.add(new CardIdentity("Orzhov Signet",""));
        cubeCards.add(new CardIdentity("Rakdos Signet",""));
        cubeCards.add(new CardIdentity("Ratchet Bomb",""));
        cubeCards.add(new CardIdentity("Scroll Rack",""));
        cubeCards.add(new CardIdentity("Selesnya Signet",""));
        cubeCards.add(new CardIdentity("Shrine of Burning Rage",""));
        cubeCards.add(new CardIdentity("Simic Signet",""));
        cubeCards.add(new CardIdentity("Sphere of the Suns",""));
        cubeCards.add(new CardIdentity("Umezawa's Jitte",""));
        cubeCards.add(new CardIdentity("Winter Orb",""));
        cubeCards.add(new CardIdentity("Basalt Monolith",""));
        cubeCards.add(new CardIdentity("Chromatic Lantern",""));
        cubeCards.add(new CardIdentity("Coalition Relic",""));
        cubeCards.add(new CardIdentity("Crucible of Worlds",""));
        cubeCards.add(new CardIdentity("Crystal Shard",""));
        cubeCards.add(new CardIdentity("Darksteel Ingot",""));
        cubeCards.add(new CardIdentity("Grafted Wargear",""));
        cubeCards.add(new CardIdentity("Loxodon Warhammer",""));
        cubeCards.add(new CardIdentity("Mimic Vat",""));
        cubeCards.add(new CardIdentity("Oblivion Stone",""));
        cubeCards.add(new CardIdentity("Sword of Body and Mind",""));
        cubeCards.add(new CardIdentity("Sword of Feast and Famine",""));
        cubeCards.add(new CardIdentity("Sword of Fire and Ice",""));
        cubeCards.add(new CardIdentity("Sword of Light and Shadow",""));
        cubeCards.add(new CardIdentity("Sword of War and Peace",""));
        cubeCards.add(new CardIdentity("Tangle Wire",""));
        cubeCards.add(new CardIdentity("Vedalken Shackles",""));
        cubeCards.add(new CardIdentity("Worn Powerstone",""));
        cubeCards.add(new CardIdentity("Erratic Portal",""));
        cubeCards.add(new CardIdentity("Icy Manipulator",""));
        cubeCards.add(new CardIdentity("Nevinyrral's Disk",""));
        cubeCards.add(new CardIdentity("Smokestack",""));
        cubeCards.add(new CardIdentity("Thran Dynamo",""));
        cubeCards.add(new CardIdentity("Batterskull",""));
        cubeCards.add(new CardIdentity("Engineered Explosives",""));
        cubeCards.add(new CardIdentity("Gilded Lotus",""));
        cubeCards.add(new CardIdentity("Memory Jar",""));
        cubeCards.add(new CardIdentity("Mindslaver",""));
        cubeCards.add(new CardIdentity("All Is Dust",""));
        cubeCards.add(new CardIdentity("Academy Ruins",""));
        cubeCards.add(new CardIdentity("Ancient Tomb",""));
        cubeCards.add(new CardIdentity("Arcane Sanctum",""));
        cubeCards.add(new CardIdentity("Arid Mesa",""));
        cubeCards.add(new CardIdentity("Azorius Chancery",""));
        cubeCards.add(new CardIdentity("Badlands",""));
        cubeCards.add(new CardIdentity("Battlefield Forge",""));
        cubeCards.add(new CardIdentity("Bayou",""));
        cubeCards.add(new CardIdentity("Blood Crypt",""));
        cubeCards.add(new CardIdentity("Bloodstained Mire",""));
        cubeCards.add(new CardIdentity("Boros Garrison",""));
        cubeCards.add(new CardIdentity("Breeding Pool",""));
        cubeCards.add(new CardIdentity("Cascade Bluffs",""));
        cubeCards.add(new CardIdentity("Caves of Koilos",""));
        cubeCards.add(new CardIdentity("Celestial Colonnade",""));
        cubeCards.add(new CardIdentity("City of Brass",""));
        cubeCards.add(new CardIdentity("Clifftop Retreat",""));
        cubeCards.add(new CardIdentity("Creeping Tar Pit",""));
        cubeCards.add(new CardIdentity("Crumbling Necropolis",""));
        cubeCards.add(new CardIdentity("Dimir Aqueduct",""));
        cubeCards.add(new CardIdentity("Dragonskull Summit",""));
        cubeCards.add(new CardIdentity("Drowned Catacomb",""));
        cubeCards.add(new CardIdentity("Evolving Wilds",""));
        cubeCards.add(new CardIdentity("Faerie Conclave",""));
        cubeCards.add(new CardIdentity("Fetid Heath",""));
        cubeCards.add(new CardIdentity("Flooded Strand",""));
        cubeCards.add(new CardIdentity("Gaea's Cradle",""));
        cubeCards.add(new CardIdentity("Gavony Township",""));
        cubeCards.add(new CardIdentity("Gemstone Mine",""));
        cubeCards.add(new CardIdentity("Glacial Fortress",""));
        cubeCards.add(new CardIdentity("Godless Shrine",""));
        cubeCards.add(new CardIdentity("Golgari Rot Farm",""));
        cubeCards.add(new CardIdentity("Grand Coliseum",""));
        cubeCards.add(new CardIdentity("Gruul Turf",""));
        cubeCards.add(new CardIdentity("Hallowed Fountain",""));
        cubeCards.add(new CardIdentity("Hinterland Harbor",""));
        cubeCards.add(new CardIdentity("Isolated Chapel",""));
        cubeCards.add(new CardIdentity("Izzet Boilerworks",""));
        cubeCards.add(new CardIdentity("Jungle Shrine",""));
        cubeCards.add(new CardIdentity("Kessig Wolf Run",""));
        cubeCards.add(new CardIdentity("Lavaclaw Reaches",""));
        cubeCards.add(new CardIdentity("Library of Alexandria",""));
        cubeCards.add(new CardIdentity("Llanowar Wastes",""));
        cubeCards.add(new CardIdentity("Marsh Flats",""));
        cubeCards.add(new CardIdentity("Maze of Ith",""));
        cubeCards.add(new CardIdentity("Mishra's Factory",""));
        cubeCards.add(new CardIdentity("Misty Rainforest",""));
        cubeCards.add(new CardIdentity("Mutavault",""));
        cubeCards.add(new CardIdentity("Orzhov Basilica",""));
        cubeCards.add(new CardIdentity("Overgrown Tomb",""));
        cubeCards.add(new CardIdentity("Plateau",""));
        cubeCards.add(new CardIdentity("Polluted Delta",""));
        cubeCards.add(new CardIdentity("Raging Ravine",""));
        cubeCards.add(new CardIdentity("Rakdos Carnarium",""));
        cubeCards.add(new CardIdentity("Reflecting Pool",""));
        cubeCards.add(new CardIdentity("Rishadan Port",""));
        cubeCards.add(new CardIdentity("Rootbound Crag",""));
        cubeCards.add(new CardIdentity("Rugged Prairie",""));
        cubeCards.add(new CardIdentity("Sacred Foundry",""));
        cubeCards.add(new CardIdentity("Savage Lands",""));
        cubeCards.add(new CardIdentity("Savannah",""));
        cubeCards.add(new CardIdentity("Scalding Tarn",""));
        cubeCards.add(new CardIdentity("Scrubland",""));
        cubeCards.add(new CardIdentity("Seaside Citadel",""));
        cubeCards.add(new CardIdentity("Selesnya Sanctuary",""));
        cubeCards.add(new CardIdentity("Shelldock Isle",""));
        cubeCards.add(new CardIdentity("Simic Growth Chamber",""));
        cubeCards.add(new CardIdentity("Steam Vents",""));
        cubeCards.add(new CardIdentity("Stirring Wildwood",""));
        cubeCards.add(new CardIdentity("Stomping Ground",""));
        cubeCards.add(new CardIdentity("Strip Mine",""));
        cubeCards.add(new CardIdentity("Sulfur Falls",""));
        cubeCards.add(new CardIdentity("Sunpetal Grove",""));
        cubeCards.add(new CardIdentity("Taiga",""));
        cubeCards.add(new CardIdentity("Tectonic Edge",""));
        cubeCards.add(new CardIdentity("Temple Garden",""));
        cubeCards.add(new CardIdentity("Terramorphic Expanse",""));
        cubeCards.add(new CardIdentity("Treetop Village",""));
        cubeCards.add(new CardIdentity("Tropical Island",""));
        cubeCards.add(new CardIdentity("Tundra",""));
        cubeCards.add(new CardIdentity("Twilight Mire",""));
        cubeCards.add(new CardIdentity("Underground Sea",""));
        cubeCards.add(new CardIdentity("Verdant Catacombs",""));
        cubeCards.add(new CardIdentity("Vivid Crag",""));
        cubeCards.add(new CardIdentity("Vivid Creek",""));
        cubeCards.add(new CardIdentity("Vivid Grove",""));
        cubeCards.add(new CardIdentity("Vivid Marsh",""));
        cubeCards.add(new CardIdentity("Vivid Meadow",""));
        cubeCards.add(new CardIdentity("Volcanic Island",""));
        cubeCards.add(new CardIdentity("Volrath's Stronghold",""));
        cubeCards.add(new CardIdentity("Wasteland",""));
        cubeCards.add(new CardIdentity("Watery Grave",""));
        cubeCards.add(new CardIdentity("Windswept Heath",""));
        cubeCards.add(new CardIdentity("Wooded Foothills",""));
        cubeCards.add(new CardIdentity("Woodland Cemetery",""));
        cubeCards.add(new CardIdentity("Yavimaya Coast",""));

    }
}
