/*
 *  Copyright 2010 BetaSteward_at_googlemail.com. All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without modification, are
 *  permitted provided that the following conditions are met:
 *
 *     1. Redistributions of source code must retain the above copyright notice, this list of
 *        conditions and the following disclaimer.
 *
 *     2. Redistributions in binary form must reproduce the above copyright notice, this list
 *        of conditions and the following disclaimer in the documentation and/or other materials
 *        provided with the distribution.
 *
 *  THIS SOFTWARE IS PROVIDED BY BetaSteward_at_googlemail.com ``AS IS'' AND ANY EXPRESS OR IMPLIED
 *  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 *  FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL BetaSteward_at_googlemail.com OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 *  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 *  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 *  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 *  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *  The views and conclusions contained in the software and documentation are those of the
 *  authors and should not be interpreted as representing official policies, either expressed
 *  or implied, of BetaSteward_at_googlemail.com.
 */
package mage.tournament.cubes;

import mage.game.draft.DraftCube;

/**
 *
 * @author fireshoes
 */

public class LegacyCubeApril2017 extends DraftCube {

    public LegacyCubeApril2017() {
        super("MTGO Legacy Cube April 2017 (600 cards)");
        cubeCards.add(new DraftCube.CardIdentity("Abbot of Keral Keep",""));
        cubeCards.add(new DraftCube.CardIdentity("Abrupt Decay",""));
        cubeCards.add(new DraftCube.CardIdentity("Abyssal Persecutor",""));
        cubeCards.add(new DraftCube.CardIdentity("Accorder Paladin",""));
        cubeCards.add(new DraftCube.CardIdentity("Acidic Slime",""));
        cubeCards.add(new DraftCube.CardIdentity("Act of Aggression",""));
        cubeCards.add(new DraftCube.CardIdentity("Ajani Goldmane",""));
        cubeCards.add(new DraftCube.CardIdentity("Ajani Vengeant",""));
        cubeCards.add(new DraftCube.CardIdentity("Ajani, Caller of the Pride",""));
        cubeCards.add(new DraftCube.CardIdentity("Anafenza, Kin-Tree Spirit",""));
        cubeCards.add(new DraftCube.CardIdentity("Ancestral Vision",""));
        cubeCards.add(new DraftCube.CardIdentity("Ancient Tomb",""));
        cubeCards.add(new DraftCube.CardIdentity("Angel of Invention",""));
        cubeCards.add(new DraftCube.CardIdentity("Angel of Serenity",""));
        cubeCards.add(new DraftCube.CardIdentity("Anger of the Gods",""));
        cubeCards.add(new DraftCube.CardIdentity("Anguished Unmaking",""));
        cubeCards.add(new DraftCube.CardIdentity("Animate Dead",""));
        cubeCards.add(new DraftCube.CardIdentity("Arbor Elf",""));
        cubeCards.add(new DraftCube.CardIdentity("Arc Trail",""));
        cubeCards.add(new DraftCube.CardIdentity("Archangel Avacyn",""));
        cubeCards.add(new DraftCube.CardIdentity("Arid Mesa",""));
        cubeCards.add(new DraftCube.CardIdentity("Armageddon",""));
        cubeCards.add(new DraftCube.CardIdentity("Ashiok, Nightmare Weaver",""));
        cubeCards.add(new DraftCube.CardIdentity("Assemble the Legion",""));
        cubeCards.add(new DraftCube.CardIdentity("Augur of Bolas",""));
        cubeCards.add(new DraftCube.CardIdentity("Avacyn's Pilgrim",""));
        cubeCards.add(new DraftCube.CardIdentity("Avalanche Riders",""));
        cubeCards.add(new DraftCube.CardIdentity("Avenger of Zendikar",""));
        cubeCards.add(new DraftCube.CardIdentity("Badlands",""));
        cubeCards.add(new DraftCube.CardIdentity("Baleful Strix",""));
        cubeCards.add(new DraftCube.CardIdentity("Banefire",""));
        cubeCards.add(new DraftCube.CardIdentity("Baneslayer Angel",""));
        cubeCards.add(new DraftCube.CardIdentity("Banisher Priest",""));
        cubeCards.add(new DraftCube.CardIdentity("Banishing Light",""));
	cubeCards.add(new DraftCube.CardIdentity("Baral, Chief of Compliance",""));
        cubeCards.add(new DraftCube.CardIdentity("Batterskull",""));
        cubeCards.add(new DraftCube.CardIdentity("Bayou",""));
        cubeCards.add(new DraftCube.CardIdentity("Beast Within",""));
        cubeCards.add(new DraftCube.CardIdentity("Bedlam Reveler",""));
        cubeCards.add(new DraftCube.CardIdentity("Beetleback Chief",""));
        cubeCards.add(new DraftCube.CardIdentity("Birds of Paradise",""));
        cubeCards.add(new DraftCube.CardIdentity("Birthing Pod",""));
        cubeCards.add(new DraftCube.CardIdentity("Bitterblossom",""));
	cubeCards.add(new DraftCube.CardIdentity("Blackcleave Cliffs",""));
        cubeCards.add(new DraftCube.CardIdentity("Blade Splicer",""));
        cubeCards.add(new DraftCube.CardIdentity("Blood Artist",""));
        cubeCards.add(new DraftCube.CardIdentity("Blood Crypt",""));
        cubeCards.add(new DraftCube.CardIdentity("Bloodbraid Elf",""));
        cubeCards.add(new DraftCube.CardIdentity("Bloodghast",""));
        cubeCards.add(new DraftCube.CardIdentity("Bloodstained Mire",""));
        cubeCards.add(new DraftCube.CardIdentity("Bloom Tender",""));
	cubeCards.add(new DraftCube.CardIdentity("Blooming Marsh",""));
        cubeCards.add(new DraftCube.CardIdentity("Bogardan Hellkite",""));
	cubeCards.add(new DraftCube.CardIdentity("Bomat Courier",""));
        cubeCards.add(new DraftCube.CardIdentity("Bone Shredder",""));
        cubeCards.add(new DraftCube.CardIdentity("Bonfire of the Damned",""));
        cubeCards.add(new DraftCube.CardIdentity("Boros Charm",""));
        cubeCards.add(new DraftCube.CardIdentity("Boros Reckoner",""));
	cubeCards.add(new DraftCube.CardIdentity("Botanical Sanctum",""));
        cubeCards.add(new DraftCube.CardIdentity("Brainstorm",""));
        cubeCards.add(new DraftCube.CardIdentity("Breeding Pool",""));
        cubeCards.add(new DraftCube.CardIdentity("Brimaz, King of Oreskos",""));
        cubeCards.add(new DraftCube.CardIdentity("Brimstone Volley",""));
        cubeCards.add(new DraftCube.CardIdentity("Bruna, the Fading Light",""));
        cubeCards.add(new DraftCube.CardIdentity("Buried Alive",""));
        cubeCards.add(new DraftCube.CardIdentity("Burst Lightning",""));
        cubeCards.add(new DraftCube.CardIdentity("Careful Consideration",""));
        cubeCards.add(new DraftCube.CardIdentity("Careful Study",""));
        cubeCards.add(new DraftCube.CardIdentity("Cathartic Reunion",""));
        cubeCards.add(new DraftCube.CardIdentity("Celestial Colonnade",""));
        cubeCards.add(new DraftCube.CardIdentity("Chain Lightning",""));
        cubeCards.add(new DraftCube.CardIdentity("Chainer's Edict",""));
        cubeCards.add(new DraftCube.CardIdentity("Champion of the Parish",""));
	cubeCards.add(new DraftCube.CardIdentity("Chandra's Phoenix",""));
        cubeCards.add(new DraftCube.CardIdentity("Chandra, Fire of Kaladesh",""));
        cubeCards.add(new DraftCube.CardIdentity("Chandra, Flamecaller",""));
        cubeCards.add(new DraftCube.CardIdentity("Chandra, Pyromaster",""));
        cubeCards.add(new DraftCube.CardIdentity("Chandra, Torch of Defiance",""));
        cubeCards.add(new DraftCube.CardIdentity("Char",""));
        cubeCards.add(new DraftCube.CardIdentity("Chord of Calling",""));
        cubeCards.add(new DraftCube.CardIdentity("Chromatic Lantern",""));
        cubeCards.add(new DraftCube.CardIdentity("City of Brass",""));
        cubeCards.add(new DraftCube.CardIdentity("Clifftop Retreat",""));
        cubeCards.add(new DraftCube.CardIdentity("Cloudgoat Ranger",""));
	cubeCards.add(new DraftCube.CardIdentity("Coalition Relic",""));
	cubeCards.add(new DraftCube.CardIdentity("Coldsteel Heart",""));
        cubeCards.add(new DraftCube.CardIdentity("Collective Brutality",""));
        cubeCards.add(new DraftCube.CardIdentity("Collective Defiance",""));
        cubeCards.add(new DraftCube.CardIdentity("Collective Effort",""));
        cubeCards.add(new DraftCube.CardIdentity("Compulsive Research",""));
	cubeCards.add(new DraftCube.CardIdentity("Concealed Courtyard",""));
        cubeCards.add(new DraftCube.CardIdentity("Condemn",""));
        cubeCards.add(new DraftCube.CardIdentity("Consecrated Sphinx",""));
        cubeCards.add(new DraftCube.CardIdentity("Control Magic",""));
	cubeCards.add(new DraftCube.CardIdentity("Copperline Gorge",""));
        cubeCards.add(new DraftCube.CardIdentity("Council's Judgment",""));
        cubeCards.add(new DraftCube.CardIdentity("Counterspell",""));
        cubeCards.add(new DraftCube.CardIdentity("Courser of Kruphix",""));
        cubeCards.add(new DraftCube.CardIdentity("Crater's Claws",""));
        cubeCards.add(new DraftCube.CardIdentity("Craterhoof Behemoth",""));
        cubeCards.add(new DraftCube.CardIdentity("Creeping Tar Pit",""));
        cubeCards.add(new DraftCube.CardIdentity("Crux of Fate",""));
        cubeCards.add(new DraftCube.CardIdentity("Cryptic Command",""));
        cubeCards.add(new DraftCube.CardIdentity("Cultivate",""));
        cubeCards.add(new DraftCube.CardIdentity("Cunning Sparkmage",""));
        cubeCards.add(new DraftCube.CardIdentity("Cyclonic Rift",""));
        cubeCards.add(new DraftCube.CardIdentity("Damnation",""));
        cubeCards.add(new DraftCube.CardIdentity("Dark Confidant",""));
        cubeCards.add(new DraftCube.CardIdentity("Dark Petition",""));
        cubeCards.add(new DraftCube.CardIdentity("Dark Ritual",""));
	cubeCards.add(new DraftCube.CardIdentity("Darkslick Shores",""));
        cubeCards.add(new DraftCube.CardIdentity("Day of Judgment",""));
        cubeCards.add(new DraftCube.CardIdentity("Daze",""));
        cubeCards.add(new DraftCube.CardIdentity("Deathrite Shaman",""));
        cubeCards.add(new DraftCube.CardIdentity("Deceiver Exarch",""));
        cubeCards.add(new DraftCube.CardIdentity("Declaration in Stone",""));
        cubeCards.add(new DraftCube.CardIdentity("Deep Analysis",""));
        cubeCards.add(new DraftCube.CardIdentity("Delver of Secrets",""));
        cubeCards.add(new DraftCube.CardIdentity("Den Protector",""));
        cubeCards.add(new DraftCube.CardIdentity("Deranged Hermit",""));
        cubeCards.add(new DraftCube.CardIdentity("Desecration Demon",""));
        cubeCards.add(new DraftCube.CardIdentity("Devil's Play",""));
        cubeCards.add(new DraftCube.CardIdentity("Devoted Druid",""));
	cubeCards.add(new DraftCube.CardIdentity("Disallow",""));
        cubeCards.add(new DraftCube.CardIdentity("Disfigure",""));
        cubeCards.add(new DraftCube.CardIdentity("Dismember",""));
        cubeCards.add(new DraftCube.CardIdentity("Dismiss",""));
        cubeCards.add(new DraftCube.CardIdentity("Dissipate",""));
        cubeCards.add(new DraftCube.CardIdentity("Dissolve",""));
        cubeCards.add(new DraftCube.CardIdentity("Distended Mindbender",""));
        cubeCards.add(new DraftCube.CardIdentity("Domri Rade",""));
        cubeCards.add(new DraftCube.CardIdentity("Doom Blade",""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonlord Atarka",""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonlord Dromoka",""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonlord Ojutai",""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonlord Silumgar",""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonskull Summit",""));
        cubeCards.add(new DraftCube.CardIdentity("Drana, Liberator of Malakir",""));
        cubeCards.add(new DraftCube.CardIdentity("Dread Return",""));
        cubeCards.add(new DraftCube.CardIdentity("Dreadbore",""));
        cubeCards.add(new DraftCube.CardIdentity("Dromoka's Command",""));
        cubeCards.add(new DraftCube.CardIdentity("Drowned Catacomb",""));
        cubeCards.add(new DraftCube.CardIdentity("Dualcaster Mage",""));
        cubeCards.add(new DraftCube.CardIdentity("Dungeon Geists",""));
        cubeCards.add(new DraftCube.CardIdentity("Duplicant",""));
        cubeCards.add(new DraftCube.CardIdentity("Duress",""));
        cubeCards.add(new DraftCube.CardIdentity("Duskwatch Recruiter",""));
        cubeCards.add(new DraftCube.CardIdentity("Edric, Spymaster of Trest",""));
        cubeCards.add(new DraftCube.CardIdentity("Elder Deep-Fiend",""));
        cubeCards.add(new DraftCube.CardIdentity("Electrolyze",""));
        cubeCards.add(new DraftCube.CardIdentity("Elesh Norn, Grand Cenobite",""));
        cubeCards.add(new DraftCube.CardIdentity("Elspeth Tirel",""));
        cubeCards.add(new DraftCube.CardIdentity("Elspeth, Knight-Errant",""));
        cubeCards.add(new DraftCube.CardIdentity("Elspeth, Sun's Champion",""));
        cubeCards.add(new DraftCube.CardIdentity("Elves of Deep Shadow",""));
        cubeCards.add(new DraftCube.CardIdentity("Elvish Mystic",""));
        cubeCards.add(new DraftCube.CardIdentity("Emeria Angel",""));
	cubeCards.add(new DraftCube.CardIdentity("Emrakul, the Aeons Torn",""));
        cubeCards.add(new DraftCube.CardIdentity("Emrakul, the Promised End",""));
	cubeCards.add(new DraftCube.CardIdentity("Engineered Explosives",""));
        cubeCards.add(new DraftCube.CardIdentity("Entomb",""));
        cubeCards.add(new DraftCube.CardIdentity("Entreat the Angels",""));
        cubeCards.add(new DraftCube.CardIdentity("Erebos, God of the Dead",""));
        cubeCards.add(new DraftCube.CardIdentity("Eternal Witness",""));
        cubeCards.add(new DraftCube.CardIdentity("Ever After",""));
        cubeCards.add(new DraftCube.CardIdentity("Exhume",""));
        cubeCards.add(new DraftCube.CardIdentity("Explore",""));
        cubeCards.add(new DraftCube.CardIdentity("Exquisite Firecraft",""));
        cubeCards.add(new DraftCube.CardIdentity("Fact or Fiction",""));
        cubeCards.add(new DraftCube.CardIdentity("Faith's Fetters",""));
        cubeCards.add(new DraftCube.CardIdentity("Falkenrath Gorger",""));
        cubeCards.add(new DraftCube.CardIdentity("Far // Away",""));
        cubeCards.add(new DraftCube.CardIdentity("Farseek",""));
	cubeCards.add(new DraftCube.CardIdentity("Fatal Push",""));
        cubeCards.add(new DraftCube.CardIdentity("Fauna Shaman",""));
        cubeCards.add(new DraftCube.CardIdentity("Fertile Ground",""));
        cubeCards.add(new DraftCube.CardIdentity("Fiend Hunter",""));
        cubeCards.add(new DraftCube.CardIdentity("Fiery Confluence",""));
        cubeCards.add(new DraftCube.CardIdentity("Fire // Ice",""));
        cubeCards.add(new DraftCube.CardIdentity("Firebolt",""));
        cubeCards.add(new DraftCube.CardIdentity("Firefist Striker",""));
        cubeCards.add(new DraftCube.CardIdentity("Flame Slash",""));
        cubeCards.add(new DraftCube.CardIdentity("Flametongue Kavu",""));
        cubeCards.add(new DraftCube.CardIdentity("Flickerwisp",""));
        cubeCards.add(new DraftCube.CardIdentity("Flooded Strand",""));
        cubeCards.add(new DraftCube.CardIdentity("Forbid",""));
        cubeCards.add(new DraftCube.CardIdentity("Force of Will",""));
        cubeCards.add(new DraftCube.CardIdentity("Force Spike",""));
        cubeCards.add(new DraftCube.CardIdentity("Forked Bolt",""));
        cubeCards.add(new DraftCube.CardIdentity("Frost Titan",""));
        cubeCards.add(new DraftCube.CardIdentity("Future Sight",""));
        cubeCards.add(new DraftCube.CardIdentity("Fyndhorn Elves",""));
        cubeCards.add(new DraftCube.CardIdentity("Gaea's Cradle",""));
        cubeCards.add(new DraftCube.CardIdentity("Garruk Relentless",""));
        cubeCards.add(new DraftCube.CardIdentity("Garruk Wildspeaker",""));
        cubeCards.add(new DraftCube.CardIdentity("Garruk, Apex Predator",""));
        cubeCards.add(new DraftCube.CardIdentity("Garruk, Primal Hunter",""));
        cubeCards.add(new DraftCube.CardIdentity("Gatekeeper of Malakir",""));
        cubeCards.add(new DraftCube.CardIdentity("Geist of Saint Traft",""));
        cubeCards.add(new DraftCube.CardIdentity("Genesis Wave",""));
        cubeCards.add(new DraftCube.CardIdentity("Geralf's Messenger",""));
	cubeCards.add(new DraftCube.CardIdentity("Ghor-Clan Rampager",""));
        cubeCards.add(new DraftCube.CardIdentity("Gideon Jura",""));
        cubeCards.add(new DraftCube.CardIdentity("Gideon, Ally of Zendikar",""));
	cubeCards.add(new DraftCube.CardIdentity("Gifted Aetherborn",""));
        cubeCards.add(new DraftCube.CardIdentity("Gifts Ungiven",""));
        cubeCards.add(new DraftCube.CardIdentity("Gilded Lotus",""));
        cubeCards.add(new DraftCube.CardIdentity("Gilt-Leaf Winnower",""));
        cubeCards.add(new DraftCube.CardIdentity("Gisela, the Broken Blade",""));
        cubeCards.add(new DraftCube.CardIdentity("Gitaxian Probe",""));
        cubeCards.add(new DraftCube.CardIdentity("Glacial Fortress",""));
        cubeCards.add(new DraftCube.CardIdentity("Glen Elendra Archmage",""));
        cubeCards.add(new DraftCube.CardIdentity("Glorious Anthem",""));
        cubeCards.add(new DraftCube.CardIdentity("Go for the Throat",""));
        cubeCards.add(new DraftCube.CardIdentity("Goblin Bombardment",""));
        cubeCards.add(new DraftCube.CardIdentity("Goblin Dark-Dwellers",""));
        cubeCards.add(new DraftCube.CardIdentity("Goblin Guide",""));
        cubeCards.add(new DraftCube.CardIdentity("Goblin Rabblemaster",""));
        cubeCards.add(new DraftCube.CardIdentity("Godless Shrine",""));
        cubeCards.add(new DraftCube.CardIdentity("Gonti, Lord of Luxury",""));
        cubeCards.add(new DraftCube.CardIdentity("Gore-House Chainwalker",""));
	cubeCards.add(new DraftCube.CardIdentity("Grafted Wargear",""));
        cubeCards.add(new DraftCube.CardIdentity("Grave Titan",""));
        cubeCards.add(new DraftCube.CardIdentity("Gray Merchant of Asphodel",""));
        cubeCards.add(new DraftCube.CardIdentity("Greater Gargadon",""));
        cubeCards.add(new DraftCube.CardIdentity("Green Sun's Zenith",""));
        cubeCards.add(new DraftCube.CardIdentity("Greenwarden of Murasa",""));
        cubeCards.add(new DraftCube.CardIdentity("Grim Lavamancer",""));
        cubeCards.add(new DraftCube.CardIdentity("Griselbrand",""));
	cubeCards.add(new DraftCube.CardIdentity("Gurmag Angler",""));
        cubeCards.add(new DraftCube.CardIdentity("Hallowed Fountain",""));
        cubeCards.add(new DraftCube.CardIdentity("Hallowed Spiritkeeper",""));
        cubeCards.add(new DraftCube.CardIdentity("Hangarback Walker",""));
        cubeCards.add(new DraftCube.CardIdentity("Harbinger of the Tides",""));
        cubeCards.add(new DraftCube.CardIdentity("Harmonize",""));
        cubeCards.add(new DraftCube.CardIdentity("Hellrider",""));
        cubeCards.add(new DraftCube.CardIdentity("Hero of Bladehold",""));
        cubeCards.add(new DraftCube.CardIdentity("Hero's Downfall",""));
        cubeCards.add(new DraftCube.CardIdentity("Hidden Dragonslayer",""));
        cubeCards.add(new DraftCube.CardIdentity("Hinterland Harbor",""));
        cubeCards.add(new DraftCube.CardIdentity("Hissing Quagmire",""));
        cubeCards.add(new DraftCube.CardIdentity("Honor of the Pure",""));
        cubeCards.add(new DraftCube.CardIdentity("Hordeling Outburst",""));
        cubeCards.add(new DraftCube.CardIdentity("Hornet Queen",""));
        cubeCards.add(new DraftCube.CardIdentity("Huntmaster of the Fells",""));
        cubeCards.add(new DraftCube.CardIdentity("Hymn to Tourach",""));
        cubeCards.add(new DraftCube.CardIdentity("Hypnotic Specter",""));
        cubeCards.add(new DraftCube.CardIdentity("Icefall Regent",""));
        cubeCards.add(new DraftCube.CardIdentity("Imperial Recruiter",""));
        cubeCards.add(new DraftCube.CardIdentity("Impulse",""));
        cubeCards.add(new DraftCube.CardIdentity("Incendiary Flow",""));
        cubeCards.add(new DraftCube.CardIdentity("Incinerate",""));
        cubeCards.add(new DraftCube.CardIdentity("Inferno Titan",""));
        cubeCards.add(new DraftCube.CardIdentity("Inquisition of Kozilek",""));
	cubeCards.add(new DraftCube.CardIdentity("Inspiring Vantage",""));
        cubeCards.add(new DraftCube.CardIdentity("Into the Roil",""));
        cubeCards.add(new DraftCube.CardIdentity("Ire Shaman",""));
        cubeCards.add(new DraftCube.CardIdentity("Isamaru, Hound of Konda",""));
        cubeCards.add(new DraftCube.CardIdentity("Isolated Chapel",""));
        cubeCards.add(new DraftCube.CardIdentity("Izzet Charm",""));
        cubeCards.add(new DraftCube.CardIdentity("Jace Beleren",""));
        cubeCards.add(new DraftCube.CardIdentity("Jace, Architect of Thought",""));
        cubeCards.add(new DraftCube.CardIdentity("Jace, the Mind Sculptor",""));
        cubeCards.add(new DraftCube.CardIdentity("Jace, Vryn's Prodigy",""));
        cubeCards.add(new DraftCube.CardIdentity("Jackal Pup",""));
        cubeCards.add(new DraftCube.CardIdentity("Joraga Treespeaker",""));
        cubeCards.add(new DraftCube.CardIdentity("Journey to Nowhere",""));
        cubeCards.add(new DraftCube.CardIdentity("Kalitas, Traitor of Ghet",""));
        cubeCards.add(new DraftCube.CardIdentity("Karmic Guide",""));
        cubeCards.add(new DraftCube.CardIdentity("Karn Liberated",""));
        cubeCards.add(new DraftCube.CardIdentity("Keiga, the Tide Star",""));
        cubeCards.add(new DraftCube.CardIdentity("Keranos, God of Storms",""));
        cubeCards.add(new DraftCube.CardIdentity("Kiki-Jiki, Mirror Breaker",""));
        cubeCards.add(new DraftCube.CardIdentity("Kiln Fiend",""));
        cubeCards.add(new DraftCube.CardIdentity("Kiora's Follower",""));
        cubeCards.add(new DraftCube.CardIdentity("Kiora, the Crashing Wave",""));
        cubeCards.add(new DraftCube.CardIdentity("Kira, Great Glass-Spinner",""));
        cubeCards.add(new DraftCube.CardIdentity("Kitchen Finks",""));
	cubeCards.add(new DraftCube.CardIdentity("Knight of the Reliquary",""));
        cubeCards.add(new DraftCube.CardIdentity("Kodama's Reach",""));
        cubeCards.add(new DraftCube.CardIdentity("Kokusho, the Evening Star",""));
        cubeCards.add(new DraftCube.CardIdentity("Kolaghan's Command",""));
        cubeCards.add(new DraftCube.CardIdentity("Koth of the Hammer",""));
        cubeCards.add(new DraftCube.CardIdentity("Kytheon, Hero of Akros",""));
        cubeCards.add(new DraftCube.CardIdentity("Land Tax",""));
        cubeCards.add(new DraftCube.CardIdentity("Languish",""));
        cubeCards.add(new DraftCube.CardIdentity("Lavaclaw Reaches",""));
        cubeCards.add(new DraftCube.CardIdentity("Legacy's Allure",""));
        cubeCards.add(new DraftCube.CardIdentity("Leonin Relic-Warder",""));
        cubeCards.add(new DraftCube.CardIdentity("Lightning Bolt",""));
        cubeCards.add(new DraftCube.CardIdentity("Lightning Greaves",""));
        cubeCards.add(new DraftCube.CardIdentity("Lightning Helix",""));
        cubeCards.add(new DraftCube.CardIdentity("Lightning Mauler",""));
        cubeCards.add(new DraftCube.CardIdentity("Lightning Strike",""));
        cubeCards.add(new DraftCube.CardIdentity("Liliana of the Veil",""));
        cubeCards.add(new DraftCube.CardIdentity("Liliana Vess",""));
        cubeCards.add(new DraftCube.CardIdentity("Liliana, Heretical Healer",""));
        cubeCards.add(new DraftCube.CardIdentity("Liliana, the Last Hope",""));
        cubeCards.add(new DraftCube.CardIdentity("Lingering Souls",""));
        cubeCards.add(new DraftCube.CardIdentity("Linvala, Keeper of Silence",""));
        cubeCards.add(new DraftCube.CardIdentity("Linvala, the Preserver",""));
        cubeCards.add(new DraftCube.CardIdentity("Living Death",""));
        cubeCards.add(new DraftCube.CardIdentity("Llanowar Elves",""));
        cubeCards.add(new DraftCube.CardIdentity("Looter il-Kor",""));
        cubeCards.add(new DraftCube.CardIdentity("Lotus Cobra",""));
        cubeCards.add(new DraftCube.CardIdentity("Lumbering Falls",""));
        cubeCards.add(new DraftCube.CardIdentity("Maelstrom Pulse",""));
        cubeCards.add(new DraftCube.CardIdentity("Magma Jet",""));
	cubeCards.add(new DraftCube.CardIdentity("Magus of the Wheel",""));
        cubeCards.add(new DraftCube.CardIdentity("Makeshift Mannequin",""));
        cubeCards.add(new DraftCube.CardIdentity("Malicious Affliction",""));
        cubeCards.add(new DraftCube.CardIdentity("Man-o'-War",""));
        cubeCards.add(new DraftCube.CardIdentity("Mana Confluence",""));
        cubeCards.add(new DraftCube.CardIdentity("Mana Tithe",""));
        cubeCards.add(new DraftCube.CardIdentity("Managorger Hydra",""));
        cubeCards.add(new DraftCube.CardIdentity("Manic Vandal",""));
        cubeCards.add(new DraftCube.CardIdentity("Marsh Flats",""));
        cubeCards.add(new DraftCube.CardIdentity("Martial Coup",""));
        cubeCards.add(new DraftCube.CardIdentity("Massacre Wurm",""));
        cubeCards.add(new DraftCube.CardIdentity("Master of the Wild Hunt",""));
        cubeCards.add(new DraftCube.CardIdentity("Master of Waves",""));
	cubeCards.add(new DraftCube.CardIdentity("Maze of Ith",""));
        cubeCards.add(new DraftCube.CardIdentity("Meloku the Clouded Mirror",""));
        cubeCards.add(new DraftCube.CardIdentity("Mentor of the Meek",""));
        cubeCards.add(new DraftCube.CardIdentity("Merfolk Looter",""));
        cubeCards.add(new DraftCube.CardIdentity("Mimic Vat",""));
	cubeCards.add(new DraftCube.CardIdentity("Mind Stone",""));
        cubeCards.add(new DraftCube.CardIdentity("Mirari's Wake",""));
        cubeCards.add(new DraftCube.CardIdentity("Mirran Crusader",""));
        cubeCards.add(new DraftCube.CardIdentity("Mirror Entity",""));
        cubeCards.add(new DraftCube.CardIdentity("Miscalculation",""));
        cubeCards.add(new DraftCube.CardIdentity("Mishra's Factory",""));
        cubeCards.add(new DraftCube.CardIdentity("Misty Rainforest",""));
        cubeCards.add(new DraftCube.CardIdentity("Mizzium Mortars",""));
        cubeCards.add(new DraftCube.CardIdentity("Mogg War Marshal",""));
        cubeCards.add(new DraftCube.CardIdentity("Monastery Mentor",""));
        cubeCards.add(new DraftCube.CardIdentity("Monastery Swiftspear",""));
        cubeCards.add(new DraftCube.CardIdentity("Mother of Runes",""));
        cubeCards.add(new DraftCube.CardIdentity("Mulldrifter",""));
        cubeCards.add(new DraftCube.CardIdentity("Murderous Cut",""));
	cubeCards.add(new DraftCube.CardIdentity("Murderous Redcap",""));
        cubeCards.add(new DraftCube.CardIdentity("Mutavault",""));
        cubeCards.add(new DraftCube.CardIdentity("Myr Battlesphere",""));
        cubeCards.add(new DraftCube.CardIdentity("Mystic Snake",""));
        cubeCards.add(new DraftCube.CardIdentity("Nahiri, the Harbinger",""));
	cubeCards.add(new DraftCube.CardIdentity("Natural Order",""));
        cubeCards.add(new DraftCube.CardIdentity("Nature's Lore",""));
        cubeCards.add(new DraftCube.CardIdentity("Necromancy",""));
        cubeCards.add(new DraftCube.CardIdentity("Needle Spires",""));
        cubeCards.add(new DraftCube.CardIdentity("Negate",""));
        cubeCards.add(new DraftCube.CardIdentity("Nekrataal",""));
        cubeCards.add(new DraftCube.CardIdentity("Nevinyrral's Disk",""));
        cubeCards.add(new DraftCube.CardIdentity("Nicol Bolas, Planeswalker",""));
        cubeCards.add(new DraftCube.CardIdentity("Nightveil Specter",""));
        cubeCards.add(new DraftCube.CardIdentity("Nissa, Vastwood Seer",""));
	cubeCards.add(new DraftCube.CardIdentity("Nissa, Vital Force",""));
        cubeCards.add(new DraftCube.CardIdentity("Nissa, Voice of Zendikar",""));
        cubeCards.add(new DraftCube.CardIdentity("Nissa, Worldwaker",""));
        cubeCards.add(new DraftCube.CardIdentity("Noble Hierarch",""));
        cubeCards.add(new DraftCube.CardIdentity("Noxious Gearhulk",""));
        cubeCards.add(new DraftCube.CardIdentity("Nykthos, Shrine to Nyx",""));
        cubeCards.add(new DraftCube.CardIdentity("Oath of Nissa",""));
        cubeCards.add(new DraftCube.CardIdentity("Ob Nixilis Reignited",""));
        cubeCards.add(new DraftCube.CardIdentity("Oblivion Ring",""));
        cubeCards.add(new DraftCube.CardIdentity("Oblivion Stone",""));
        cubeCards.add(new DraftCube.CardIdentity("Obstinate Baloth",""));
        cubeCards.add(new DraftCube.CardIdentity("Old Man of the Sea",""));
        cubeCards.add(new DraftCube.CardIdentity("Olivia Voldaren",""));
        cubeCards.add(new DraftCube.CardIdentity("Oona's Prowler",""));
        cubeCards.add(new DraftCube.CardIdentity("Ophiomancer",""));
        cubeCards.add(new DraftCube.CardIdentity("Opposition",""));
        cubeCards.add(new DraftCube.CardIdentity("Oracle of Mul Daya",""));
        cubeCards.add(new DraftCube.CardIdentity("Oust",""));
        cubeCards.add(new DraftCube.CardIdentity("Outpost Siege",""));
        cubeCards.add(new DraftCube.CardIdentity("Overgrown Battlement",""));
        cubeCards.add(new DraftCube.CardIdentity("Overgrown Tomb",""));
        cubeCards.add(new DraftCube.CardIdentity("Pack Rat",""));
        cubeCards.add(new DraftCube.CardIdentity("Pact of Negation",""));
        cubeCards.add(new DraftCube.CardIdentity("Panharmonicon",""));
        cubeCards.add(new DraftCube.CardIdentity("Parallax Wave",""));
        cubeCards.add(new DraftCube.CardIdentity("Part the Waterveil",""));
        cubeCards.add(new DraftCube.CardIdentity("Path to Exile",""));
	cubeCards.add(new DraftCube.CardIdentity("Pernicious Deed",""));
        cubeCards.add(new DraftCube.CardIdentity("Pestermite",""));
        cubeCards.add(new DraftCube.CardIdentity("Phantasmal Image",""));
        cubeCards.add(new DraftCube.CardIdentity("Phyrexian Arena",""));
        cubeCards.add(new DraftCube.CardIdentity("Phyrexian Metamorph",""));
        cubeCards.add(new DraftCube.CardIdentity("Phyrexian Obliterator",""));
        cubeCards.add(new DraftCube.CardIdentity("Phyrexian Rager",""));
        cubeCards.add(new DraftCube.CardIdentity("Phyrexian Revoker",""));
        cubeCards.add(new DraftCube.CardIdentity("Pia and Kiran Nalaar",""));
        cubeCards.add(new DraftCube.CardIdentity("Pillar of Flame",""));
        cubeCards.add(new DraftCube.CardIdentity("Plateau",""));
        cubeCards.add(new DraftCube.CardIdentity("Polluted Delta",""));
        cubeCards.add(new DraftCube.CardIdentity("Polukranos, World Eater",""));
        cubeCards.add(new DraftCube.CardIdentity("Ponder",""));
        cubeCards.add(new DraftCube.CardIdentity("Porcelain Legionnaire",""));
        cubeCards.add(new DraftCube.CardIdentity("Precinct Captain",""));
        cubeCards.add(new DraftCube.CardIdentity("Preordain",""));
        cubeCards.add(new DraftCube.CardIdentity("Primal Command",""));
        cubeCards.add(new DraftCube.CardIdentity("Primeval Titan",""));
        cubeCards.add(new DraftCube.CardIdentity("Profane Command",""));
        cubeCards.add(new DraftCube.CardIdentity("Purphoros, God of the Forge",""));
        cubeCards.add(new DraftCube.CardIdentity("Pyroclasm",""));
        cubeCards.add(new DraftCube.CardIdentity("Qasali Pridemage",""));
        cubeCards.add(new DraftCube.CardIdentity("Quarantine Field",""));
        cubeCards.add(new DraftCube.CardIdentity("Raging Ravine",""));
        cubeCards.add(new DraftCube.CardIdentity("Raise the Alarm",""));
        cubeCards.add(new DraftCube.CardIdentity("Rakdos's Return",""));
        cubeCards.add(new DraftCube.CardIdentity("Ral Zarek",""));
        cubeCards.add(new DraftCube.CardIdentity("Rampaging Baloths",""));
        cubeCards.add(new DraftCube.CardIdentity("Rampant Growth",""));
        cubeCards.add(new DraftCube.CardIdentity("Ranger of Eos",""));
        cubeCards.add(new DraftCube.CardIdentity("Ratchet Bomb",""));
        cubeCards.add(new DraftCube.CardIdentity("Ravages of War",""));
	cubeCards.add(new DraftCube.CardIdentity("Razorverge Thicket",""));
        cubeCards.add(new DraftCube.CardIdentity("Read the Bones",""));
        cubeCards.add(new DraftCube.CardIdentity("Reanimate",""));
        cubeCards.add(new DraftCube.CardIdentity("Reckless Bushwhacker",""));
        cubeCards.add(new DraftCube.CardIdentity("Reclamation Sage",""));
        cubeCards.add(new DraftCube.CardIdentity("Recruiter of the Guard",""));
        cubeCards.add(new DraftCube.CardIdentity("Recurring Nightmare",""));
        cubeCards.add(new DraftCube.CardIdentity("Reflecting Pool",""));
        cubeCards.add(new DraftCube.CardIdentity("Reflector Mage",""));
        cubeCards.add(new DraftCube.CardIdentity("Regrowth",""));
        cubeCards.add(new DraftCube.CardIdentity("Relic of Progenitus",""));
        cubeCards.add(new DraftCube.CardIdentity("Remand",""));
        cubeCards.add(new DraftCube.CardIdentity("Remove Soul",""));
        cubeCards.add(new DraftCube.CardIdentity("Repeal",""));
        cubeCards.add(new DraftCube.CardIdentity("Restoration Angel",""));
        cubeCards.add(new DraftCube.CardIdentity("Reveillark",""));
        cubeCards.add(new DraftCube.CardIdentity("Rift Bolt",""));
        cubeCards.add(new DraftCube.CardIdentity("Riftwing Cloudskate",""));
        cubeCards.add(new DraftCube.CardIdentity("Rishadan Port",""));
	cubeCards.add(new DraftCube.CardIdentity("Rishkar, Peema Renegade",""));
        cubeCards.add(new DraftCube.CardIdentity("Roast",""));
        cubeCards.add(new DraftCube.CardIdentity("Rofellos, Llanowar Emissary",""));
        cubeCards.add(new DraftCube.CardIdentity("Rootbound Crag",""));
        cubeCards.add(new DraftCube.CardIdentity("Rune-Scarred Demon",""));
        cubeCards.add(new DraftCube.CardIdentity("Sacred Foundry",""));
        cubeCards.add(new DraftCube.CardIdentity("Sakura-Tribe Elder",""));
        cubeCards.add(new DraftCube.CardIdentity("Sarkhan, the Dragonspeaker",""));
        cubeCards.add(new DraftCube.CardIdentity("Savannah",""));
        cubeCards.add(new DraftCube.CardIdentity("Scalding Tarn",""));
        cubeCards.add(new DraftCube.CardIdentity("Scavenging Ooze",""));
        cubeCards.add(new DraftCube.CardIdentity("Scrapheap Scrounger",""));
        cubeCards.add(new DraftCube.CardIdentity("Scrubland",""));
        cubeCards.add(new DraftCube.CardIdentity("Sea Gate Oracle",""));
	cubeCards.add(new DraftCube.CardIdentity("Seachrome Coast",""));
        cubeCards.add(new DraftCube.CardIdentity("Seal of Fire",""));
        cubeCards.add(new DraftCube.CardIdentity("Search for Tomorrow",""));
        cubeCards.add(new DraftCube.CardIdentity("Searing Spear",""));
        cubeCards.add(new DraftCube.CardIdentity("Secure the Wastes",""));
        cubeCards.add(new DraftCube.CardIdentity("Seeker of the Way",""));
        cubeCards.add(new DraftCube.CardIdentity("Selfless Spirit",""));
        cubeCards.add(new DraftCube.CardIdentity("Selvala, Heart of the Wilds",""));
        cubeCards.add(new DraftCube.CardIdentity("Sensei's Divining Top",""));
        cubeCards.add(new DraftCube.CardIdentity("Serendib Efreet",""));
        cubeCards.add(new DraftCube.CardIdentity("Serum Visions",""));
        cubeCards.add(new DraftCube.CardIdentity("Shadowmage Infiltrator",""));
        cubeCards.add(new DraftCube.CardIdentity("Shaman of Forgotten Ways",""));
        cubeCards.add(new DraftCube.CardIdentity("Shambling Vent",""));
        cubeCards.add(new DraftCube.CardIdentity("Shardless Agent",""));
        cubeCards.add(new DraftCube.CardIdentity("Shelldock Isle",""));
        cubeCards.add(new DraftCube.CardIdentity("Sheoldred, Whispering One",""));
	cubeCards.add(new DraftCube.CardIdentity("Show and Tell",""));
        cubeCards.add(new DraftCube.CardIdentity("Shriekmaw",""));
        cubeCards.add(new DraftCube.CardIdentity("Sidisi, Undead Vizier",""));
        cubeCards.add(new DraftCube.CardIdentity("Siege-Gang Commander",""));
        cubeCards.add(new DraftCube.CardIdentity("Silverblade Paladin",""));
        cubeCards.add(new DraftCube.CardIdentity("Skinrender",""));
        cubeCards.add(new DraftCube.CardIdentity("Slagstorm",""));
        cubeCards.add(new DraftCube.CardIdentity("Slaughter Pact",""));
        cubeCards.add(new DraftCube.CardIdentity("Smuggler's Copter",""));
        cubeCards.add(new DraftCube.CardIdentity("Snapcaster Mage",""));
	cubeCards.add(new DraftCube.CardIdentity("Sneak Attack",""));
        cubeCards.add(new DraftCube.CardIdentity("Soldier of the Pantheon",""));
        cubeCards.add(new DraftCube.CardIdentity("Solemn Simulacrum",""));
        cubeCards.add(new DraftCube.CardIdentity("Song of the Dryads",""));
        cubeCards.add(new DraftCube.CardIdentity("Sorin Markov",""));
        cubeCards.add(new DraftCube.CardIdentity("Sorin, Solemn Visitor",""));
        cubeCards.add(new DraftCube.CardIdentity("Soulfire Grand Master",""));
        cubeCards.add(new DraftCube.CardIdentity("Sower of Temptation",""));
        cubeCards.add(new DraftCube.CardIdentity("Spear of Heliod",""));
        cubeCards.add(new DraftCube.CardIdentity("Spectral Procession",""));
        cubeCards.add(new DraftCube.CardIdentity("Spell Pierce",""));
        cubeCards.add(new DraftCube.CardIdentity("Spell Queller",""));
        cubeCards.add(new DraftCube.CardIdentity("Spellskite",""));
        cubeCards.add(new DraftCube.CardIdentity("Sphinx's Revelation",""));
	cubeCards.add(new DraftCube.CardIdentity("Spirebluff Canal",""));
        cubeCards.add(new DraftCube.CardIdentity("Splinter Twin",""));
        cubeCards.add(new DraftCube.CardIdentity("Staggershock",""));
        cubeCards.add(new DraftCube.CardIdentity("Steam Vents",""));
        cubeCards.add(new DraftCube.CardIdentity("Stirring Wildwood",""));
        cubeCards.add(new DraftCube.CardIdentity("Stoke the Flames",""));
        cubeCards.add(new DraftCube.CardIdentity("Stomping Ground",""));
	cubeCards.add(new DraftCube.CardIdentity("Stoneforge Mystic",""));
        cubeCards.add(new DraftCube.CardIdentity("Stormbreath Dragon",""));
        cubeCards.add(new DraftCube.CardIdentity("Stormchaser Mage",""));
        cubeCards.add(new DraftCube.CardIdentity("Stratus Dancer",""));
        cubeCards.add(new DraftCube.CardIdentity("Stroke of Genius",""));
        cubeCards.add(new DraftCube.CardIdentity("Stromkirk Noble",""));
        cubeCards.add(new DraftCube.CardIdentity("Student of Warfare",""));
        cubeCards.add(new DraftCube.CardIdentity("Sublime Archangel",""));
        cubeCards.add(new DraftCube.CardIdentity("Sulfur Falls",""));
        cubeCards.add(new DraftCube.CardIdentity("Summoning Trap",""));
        cubeCards.add(new DraftCube.CardIdentity("Sun Titan",""));
        cubeCards.add(new DraftCube.CardIdentity("Sundering Titan",""));
        cubeCards.add(new DraftCube.CardIdentity("Sunpetal Grove",""));
        cubeCards.add(new DraftCube.CardIdentity("Supreme Verdict",""));
        cubeCards.add(new DraftCube.CardIdentity("Surrak, the Hunt Caller",""));
	cubeCards.add(new DraftCube.CardIdentity("Sword of Body and Mind",""));
	cubeCards.add(new DraftCube.CardIdentity("Sword of Feast and Famine",""));
	cubeCards.add(new DraftCube.CardIdentity("Sword of Fire and Ice",""));
	cubeCards.add(new DraftCube.CardIdentity("Sword of Light and Shadow",""));
	cubeCards.add(new DraftCube.CardIdentity("Sword of War and Peace",""));
        cubeCards.add(new DraftCube.CardIdentity("Swords to Plowshares",""));
        cubeCards.add(new DraftCube.CardIdentity("Sylvan Advocate",""));
        cubeCards.add(new DraftCube.CardIdentity("Sylvan Caryatid",""));
        cubeCards.add(new DraftCube.CardIdentity("Sylvan Library",""));
        cubeCards.add(new DraftCube.CardIdentity("Taiga",""));
        cubeCards.add(new DraftCube.CardIdentity("Talrand, Sky Summoner",""));
        cubeCards.add(new DraftCube.CardIdentity("Tamiyo, the Moon Sage",""));
        cubeCards.add(new DraftCube.CardIdentity("Tangle Wire",""));
        cubeCards.add(new DraftCube.CardIdentity("Tarmogoyf",""));
        cubeCards.add(new DraftCube.CardIdentity("Tasigur, the Golden Fang",""));
        cubeCards.add(new DraftCube.CardIdentity("Teferi, Mage of Zhalfir",""));
        cubeCards.add(new DraftCube.CardIdentity("Temple Garden",""));
        cubeCards.add(new DraftCube.CardIdentity("Terastodon",""));
        cubeCards.add(new DraftCube.CardIdentity("Terminate",""));
        cubeCards.add(new DraftCube.CardIdentity("Terminus",""));
        cubeCards.add(new DraftCube.CardIdentity("Thalia, Guardian of Thraben",""));
        cubeCards.add(new DraftCube.CardIdentity("Thalia, Heretic Cathar",""));
        cubeCards.add(new DraftCube.CardIdentity("Thassa, God of the Sea",""));
        cubeCards.add(new DraftCube.CardIdentity("Thing in the Ice",""));
        cubeCards.add(new DraftCube.CardIdentity("Thirst for Knowledge",""));
        cubeCards.add(new DraftCube.CardIdentity("Thoughtseize",""));
        cubeCards.add(new DraftCube.CardIdentity("Thragtusk",""));
        cubeCards.add(new DraftCube.CardIdentity("Thrun, the Last Troll",""));
        cubeCards.add(new DraftCube.CardIdentity("Thunderbreak Regent",""));
        cubeCards.add(new DraftCube.CardIdentity("Thundermaw Hellkite",""));
        cubeCards.add(new DraftCube.CardIdentity("Tidehollow Sculler",""));
        cubeCards.add(new DraftCube.CardIdentity("Time Warp",""));
        cubeCards.add(new DraftCube.CardIdentity("Tireless Tracker",""));
        cubeCards.add(new DraftCube.CardIdentity("Tooth and Nail",""));
	cubeCards.add(new DraftCube.CardIdentity("Torch Fiend",""));
	cubeCards.add(new DraftCube.CardIdentity("Tower of the Magistrate",""));
        cubeCards.add(new DraftCube.CardIdentity("Toxic Deluge",""));
        cubeCards.add(new DraftCube.CardIdentity("Treachery",""));
        cubeCards.add(new DraftCube.CardIdentity("Tropical Island",""));
        cubeCards.add(new DraftCube.CardIdentity("Trygon Predator",""));
        cubeCards.add(new DraftCube.CardIdentity("Tundra",""));
        cubeCards.add(new DraftCube.CardIdentity("Ugin, the Spirit Dragon",""));
        cubeCards.add(new DraftCube.CardIdentity("Ulamog, the Ceaseless Hunger",""));
        cubeCards.add(new DraftCube.CardIdentity("Ultimate Price",""));
	cubeCards.add(new DraftCube.CardIdentity("Umezawa's Jitte",""));
        cubeCards.add(new DraftCube.CardIdentity("Unburial Rites",""));
        cubeCards.add(new DraftCube.CardIdentity("Underground Sea",""));
        cubeCards.add(new DraftCube.CardIdentity("Underworld Connections",""));
        cubeCards.add(new DraftCube.CardIdentity("Unexpectedly Absent",""));
        cubeCards.add(new DraftCube.CardIdentity("Upheaval",""));
        cubeCards.add(new DraftCube.CardIdentity("Utopia Sprawl",""));
        cubeCards.add(new DraftCube.CardIdentity("Vampire Hexmage",""));
        cubeCards.add(new DraftCube.CardIdentity("Vampire Nighthawk",""));
        cubeCards.add(new DraftCube.CardIdentity("Vendilion Clique",""));
        cubeCards.add(new DraftCube.CardIdentity("Venser, Shaper Savant",""));
        cubeCards.add(new DraftCube.CardIdentity("Verdant Catacombs",""));
        cubeCards.add(new DraftCube.CardIdentity("Verdurous Gearhulk",""));
        cubeCards.add(new DraftCube.CardIdentity("Victimize",""));
        cubeCards.add(new DraftCube.CardIdentity("Vindicate",""));
        cubeCards.add(new DraftCube.CardIdentity("Volcanic Island",""));
        cubeCards.add(new DraftCube.CardIdentity("Volrath's Stronghold",""));
        cubeCards.add(new DraftCube.CardIdentity("Vorinclex, Voice of Hunger",""));
        cubeCards.add(new DraftCube.CardIdentity("Vraska the Unseen",""));
        cubeCards.add(new DraftCube.CardIdentity("Wake Thrasher",""));
	cubeCards.add(new DraftCube.CardIdentity("Walking Ballista",""));
        cubeCards.add(new DraftCube.CardIdentity("Wall of Blossoms",""));
        cubeCards.add(new DraftCube.CardIdentity("Wall of Omens",""));
        cubeCards.add(new DraftCube.CardIdentity("Wandering Fumarole",""));
        cubeCards.add(new DraftCube.CardIdentity("Wasteland",""));
        cubeCards.add(new DraftCube.CardIdentity("Watery Grave",""));
        cubeCards.add(new DraftCube.CardIdentity("Whip of Erebos",""));
        cubeCards.add(new DraftCube.CardIdentity("Whirler Rogue",""));
        cubeCards.add(new DraftCube.CardIdentity("Whisperwood Elemental",""));
	cubeCards.add(new DraftCube.CardIdentity("Wickerbough Elder",""));
        cubeCards.add(new DraftCube.CardIdentity("Windbrisk Heights",""));
        cubeCards.add(new DraftCube.CardIdentity("Windswept Heath",""));
        cubeCards.add(new DraftCube.CardIdentity("Wolfir Silverheart",""));
        cubeCards.add(new DraftCube.CardIdentity("Wood Elves",""));
        cubeCards.add(new DraftCube.CardIdentity("Wooded Foothills",""));
        cubeCards.add(new DraftCube.CardIdentity("Woodfall Primus",""));
        cubeCards.add(new DraftCube.CardIdentity("Woodland Cemetery",""));
        cubeCards.add(new DraftCube.CardIdentity("Wrath of God",""));
        cubeCards.add(new DraftCube.CardIdentity("Wretched Confluence",""));
        cubeCards.add(new DraftCube.CardIdentity("Wurmcoil Engine",""));
        cubeCards.add(new DraftCube.CardIdentity("Xenagos, the Reveler",""));
        cubeCards.add(new DraftCube.CardIdentity("Yavimaya Elder",""));
        cubeCards.add(new DraftCube.CardIdentity("Yosei, the Morning Star",""));
        cubeCards.add(new DraftCube.CardIdentity("Young Pyromancer",""));
        cubeCards.add(new DraftCube.CardIdentity("Zealous Conscripts",""));
    }
}
