package mage.tournament.cubes;

import mage.game.draft.DraftCube;

/**
 * @author fireshoes
 */

public class LegendaryCube extends DraftCube {

    public LegendaryCube() {
        super("Legendary Cube"); // http://magic.wizards.com/en/MTGO/articles/archive/legendary-cube-cardlist-2015-11-09

        cubeCards.add(new CardIdentity("Aboshan, Cephalid Emperor", ""));
        cubeCards.add(new CardIdentity("Absorb Vis", ""));
        cubeCards.add(new CardIdentity("Akroma's Memorial", ""));
        cubeCards.add(new CardIdentity("Akroma's Vengeance", ""));
        cubeCards.add(new CardIdentity("Akroma, Angel of Wrath", ""));
        cubeCards.add(new CardIdentity("Akuta, Born of Ash", ""));
        cubeCards.add(new CardIdentity("Alesha, Who Smiles at Death", ""));
        cubeCards.add(new CardIdentity("Alhammarret's Archive", ""));
        cubeCards.add(new CardIdentity("All Suns' Dawn", ""));
        cubeCards.add(new CardIdentity("Anafenza, Kin-Tree Spirit", ""));
        cubeCards.add(new CardIdentity("Anger of the Gods", ""));
        cubeCards.add(new CardIdentity("Anticipate", ""));
        cubeCards.add(new CardIdentity("Arashi, the Sky Asunder", ""));
        cubeCards.add(new CardIdentity("Arcane Denial", ""));
        cubeCards.add(new CardIdentity("Arcane Sanctum", ""));
        cubeCards.add(new CardIdentity("Arcanis the Omnipotent", ""));
        cubeCards.add(new CardIdentity("Arid Mesa", ""));
        cubeCards.add(new CardIdentity("Armillary Sphere", ""));
        cubeCards.add(new CardIdentity("Ascendant Evincar", ""));
        cubeCards.add(new CardIdentity("Ashling the Pilgrim", ""));
        cubeCards.add(new CardIdentity("Ashling, the Extinguisher", ""));
        cubeCards.add(new CardIdentity("Atarka, World Render", ""));
        cubeCards.add(new CardIdentity("Austere Command", ""));
        cubeCards.add(new CardIdentity("Avacyn, Angel of Hope", ""));
        cubeCards.add(new CardIdentity("Ayumi, the Last Visitor", ""));
        cubeCards.add(new CardIdentity("Azami, Lady of Scrolls", ""));
        cubeCards.add(new CardIdentity("Azorius Chancery", ""));
        cubeCards.add(new CardIdentity("Azorius Signet", ""));
        cubeCards.add(new CardIdentity("Azusa, Lost but Seeking", ""));
        cubeCards.add(new CardIdentity("Bad River", ""));
        cubeCards.add(new CardIdentity("Badlands", ""));
        cubeCards.add(new CardIdentity("Banishing Light", ""));
        cubeCards.add(new CardIdentity("Basalt Monolith", ""));
        cubeCards.add(new CardIdentity("Basilisk Collar", ""));
        cubeCards.add(new CardIdentity("Bayou", ""));
        cubeCards.add(new CardIdentity("Beacon of Destruction", ""));
        cubeCards.add(new CardIdentity("Beacon of Tomorrows", ""));
        cubeCards.add(new CardIdentity("Beast Within", ""));
        cubeCards.add(new CardIdentity("Berserkers' Onslaught", ""));
        cubeCards.add(new CardIdentity("Black Market", ""));
        cubeCards.add(new CardIdentity("Black Sun's Zenith", ""));
        cubeCards.add(new CardIdentity("Blasphemous Act", ""));
        cubeCards.add(new CardIdentity("Blood Crypt", ""));
        cubeCards.add(new CardIdentity("Bloodstained Mire", ""));
        cubeCards.add(new CardIdentity("Bonfire of the Damned", ""));
        cubeCards.add(new CardIdentity("Boros Garrison", ""));
        cubeCards.add(new CardIdentity("Boros Signet", ""));
        cubeCards.add(new CardIdentity("Brago, King Eternal", ""));
        cubeCards.add(new CardIdentity("Brainbite", ""));
        cubeCards.add(new CardIdentity("Brainstorm", ""));
        cubeCards.add(new CardIdentity("Breeding Pool", ""));
        cubeCards.add(new CardIdentity("Brimaz, King of Oreskos", ""));
        cubeCards.add(new CardIdentity("Brion Stoutarm", ""));
        cubeCards.add(new CardIdentity("Brothers Yamazaki", ""));
        cubeCards.add(new CardIdentity("Brothers Yamazaki", ""));
        cubeCards.add(new CardIdentity("Caged Sun", ""));
        cubeCards.add(new CardIdentity("Calciform Pools", ""));
        cubeCards.add(new CardIdentity("Canopy Vista", ""));
        cubeCards.add(new CardIdentity("Captain Sisay", ""));
        cubeCards.add(new CardIdentity("Careful Consideration", ""));
        cubeCards.add(new CardIdentity("Cascade Bluffs", ""));
        cubeCards.add(new CardIdentity("Catch // Release", ""));
        cubeCards.add(new CardIdentity("Cauldron of Souls", ""));
        cubeCards.add(new CardIdentity("Chain Reaction", ""));
        cubeCards.add(new CardIdentity("Chainer's Edict", ""));
        cubeCards.add(new CardIdentity("Champion's Helm", ""));
        cubeCards.add(new CardIdentity("Chandra, Fire of Kaladesh", ""));
        cubeCards.add(new CardIdentity("Charcoal Diamond", ""));
        cubeCards.add(new CardIdentity("Cho-Manno, Revolutionary", ""));
        cubeCards.add(new CardIdentity("Chromatic Lantern", ""));
        cubeCards.add(new CardIdentity("Chromatic Sphere", ""));
        cubeCards.add(new CardIdentity("Chromatic Star", ""));
        cubeCards.add(new CardIdentity("Cinder Glade", ""));
        cubeCards.add(new CardIdentity("Clifftop Retreat", ""));
        cubeCards.add(new CardIdentity("Coalition Relic", ""));
        cubeCards.add(new CardIdentity("Coalition Victory", ""));
        cubeCards.add(new CardIdentity("Coldsteel Heart", ""));
        cubeCards.add(new CardIdentity("Commander Eesha", ""));
        cubeCards.add(new CardIdentity("Compulsive Research", ""));
        cubeCards.add(new CardIdentity("Condemn", ""));
        cubeCards.add(new CardIdentity("Conflux", ""));
        cubeCards.add(new CardIdentity("Contagion Clasp", ""));
        cubeCards.add(new CardIdentity("Council's Judgment", ""));
        cubeCards.add(new CardIdentity("Crackling Doom", ""));
        cubeCards.add(new CardIdentity("Crib Swap", ""));
        cubeCards.add(new CardIdentity("Cromat", ""));
        cubeCards.add(new CardIdentity("Crovax, Ascendant Hero", ""));
        cubeCards.add(new CardIdentity("Cruel Ultimatum", ""));
        cubeCards.add(new CardIdentity("Crumbling Necropolis", ""));
        cubeCards.add(new CardIdentity("Crux of Fate", ""));
        cubeCards.add(new CardIdentity("Crystal Ball", ""));
        cubeCards.add(new CardIdentity("Cultivate", ""));
        cubeCards.add(new CardIdentity("Cyclonic Rift", ""));
        cubeCards.add(new CardIdentity("Daretti, Scrap Savant", ""));
        cubeCards.add(new CardIdentity("Dark Depths", ""));
        cubeCards.add(new CardIdentity("Daxos of Meletis", ""));
        cubeCards.add(new CardIdentity("Day of Destiny", ""));
        cubeCards.add(new CardIdentity("Death Denied", ""));
        cubeCards.add(new CardIdentity("Detention Sphere", ""));
        cubeCards.add(new CardIdentity("Devour Flesh", ""));
        cubeCards.add(new CardIdentity("Devour in Shadow", ""));
        cubeCards.add(new CardIdentity("Diabolic Tutor", ""));
        cubeCards.add(new CardIdentity("Diaochan, Artful Beauty", ""));
        cubeCards.add(new CardIdentity("Dimir Aqueduct", ""));
        cubeCards.add(new CardIdentity("Dimir Signet", ""));
        cubeCards.add(new CardIdentity("Disenchant", ""));
        cubeCards.add(new CardIdentity("Dismantling Blow", ""));
        cubeCards.add(new CardIdentity("Divine Reckoning", ""));
        cubeCards.add(new CardIdentity("Door to Nothingness", ""));
        cubeCards.add(new CardIdentity("Doran, the Siege Tower", ""));
        cubeCards.add(new CardIdentity("Doubling Season", ""));
        cubeCards.add(new CardIdentity("Dragon Breath", ""));
        cubeCards.add(new CardIdentity("Dragonlord Atarka", ""));
        cubeCards.add(new CardIdentity("Dragonlord Dromoka", ""));
        cubeCards.add(new CardIdentity("Dragonlord Ojutai", ""));
        cubeCards.add(new CardIdentity("Dragonlord Silumgar", ""));
        cubeCards.add(new CardIdentity("Dragonskull Summit", ""));
        cubeCards.add(new CardIdentity("Drana, Kalastria Bloodchief", ""));
        cubeCards.add(new CardIdentity("Drana, Liberator of Malakir", ""));
        cubeCards.add(new CardIdentity("Dreadship Reef", ""));
        cubeCards.add(new CardIdentity("Dromoka's Command", ""));
        cubeCards.add(new CardIdentity("Drowned Catacomb", ""));
        cubeCards.add(new CardIdentity("Duress", ""));
        cubeCards.add(new CardIdentity("Dwynen, Gilt-Leaf Daen", ""));
        cubeCards.add(new CardIdentity("Edric, Spymaster of Trest", ""));
        cubeCards.add(new CardIdentity("Eiganjo Castle", ""));
        cubeCards.add(new CardIdentity("Eight-and-a-Half-Tails", ""));
        cubeCards.add(new CardIdentity("Eladamri's Call", ""));
        cubeCards.add(new CardIdentity("Eladamri, Lord of Leaves", ""));
        cubeCards.add(new CardIdentity("Elbrus, the Binding Blade", ""));
        cubeCards.add(new CardIdentity("Elesh Norn, Grand Cenobite", ""));
        cubeCards.add(new CardIdentity("Emrakul, the Aeons Torn", ""));
        cubeCards.add(new CardIdentity("Endrek Sahr, Master Breeder", ""));
        cubeCards.add(new CardIdentity("Engineered Explosives", ""));
        cubeCards.add(new CardIdentity("Enlightened Tutor", ""));
        cubeCards.add(new CardIdentity("Esper Charm", ""));
        cubeCards.add(new CardIdentity("Everflowing Chalice", ""));
        cubeCards.add(new CardIdentity("Evolving Wilds", ""));
        cubeCards.add(new CardIdentity("Exava, Rakdos Blood Witch", ""));
        cubeCards.add(new CardIdentity("Experiment Kraj", ""));
        cubeCards.add(new CardIdentity("Explore", ""));
        cubeCards.add(new CardIdentity("Explosive Vegetation", ""));
        cubeCards.add(new CardIdentity("Expunge", ""));
        cubeCards.add(new CardIdentity("Ezuri, Claw of Progress", ""));
        cubeCards.add(new CardIdentity("Fact or Fiction", ""));
        cubeCards.add(new CardIdentity("Faith's Fetters", ""));
        cubeCards.add(new CardIdentity("Faithless Looting", ""));
        cubeCards.add(new CardIdentity("Far // Away", ""));
        cubeCards.add(new CardIdentity("Farseek", ""));
        cubeCards.add(new CardIdentity("Fellwar Stone", ""));
        cubeCards.add(new CardIdentity("Fetid Heath", ""));
        cubeCards.add(new CardIdentity("Fiery Confluence", ""));
        cubeCards.add(new CardIdentity("Fiery Fall", ""));
        cubeCards.add(new CardIdentity("Finest Hour", ""));
        cubeCards.add(new CardIdentity("Fire Diamond", ""));
        cubeCards.add(new CardIdentity("Fire-Lit Thicket", ""));
        cubeCards.add(new CardIdentity("Firebolt", ""));
        cubeCards.add(new CardIdentity("Fires of Yavimaya", ""));
        cubeCards.add(new CardIdentity("Flood Plain", ""));
        cubeCards.add(new CardIdentity("Flooded Grove", ""));
        cubeCards.add(new CardIdentity("Flooded Strand", ""));
        cubeCards.add(new CardIdentity("Forbidden Alchemy", ""));
        cubeCards.add(new CardIdentity("Foresee", ""));
        cubeCards.add(new CardIdentity("Frontier Bivouac", ""));
        cubeCards.add(new CardIdentity("Fungal Reaches", ""));
        cubeCards.add(new CardIdentity("Genesis Wave", ""));
        cubeCards.add(new CardIdentity("Genju of the Realm", ""));
        cubeCards.add(new CardIdentity("Ghave, Guru of Spores", ""));
        cubeCards.add(new CardIdentity("Ghoulcaller Gisa", ""));
        cubeCards.add(new CardIdentity("Gift of the Gargantuan", ""));
        cubeCards.add(new CardIdentity("Gilded Light", ""));
        cubeCards.add(new CardIdentity("Gilded Lotus", ""));
        cubeCards.add(new CardIdentity("Gisela, Blade of Goldnight", ""));
        cubeCards.add(new CardIdentity("Glacial Fortress", ""));
        cubeCards.add(new CardIdentity("Gleam of Resistance", ""));
        cubeCards.add(new CardIdentity("Glissa Sunseeker", ""));
        cubeCards.add(new CardIdentity("Glissa, the Traitor", ""));
        cubeCards.add(new CardIdentity("Godless Shrine", ""));
        cubeCards.add(new CardIdentity("Godo, Bandit Warlord", ""));
        cubeCards.add(new CardIdentity("Gods Willing", ""));
        cubeCards.add(new CardIdentity("Golgari Rot Farm", ""));
        cubeCards.add(new CardIdentity("Golgari Signet", ""));
        cubeCards.add(new CardIdentity("Grasslands", ""));
        cubeCards.add(new CardIdentity("Graven Cairns", ""));
        cubeCards.add(new CardIdentity("Grenzo, Dungeon Warden", ""));
        cubeCards.add(new CardIdentity("Griselbrand", ""));
        cubeCards.add(new CardIdentity("Gruul Signet", ""));
        cubeCards.add(new CardIdentity("Gruul Turf", ""));
        cubeCards.add(new CardIdentity("Hallowed Fountain", ""));
        cubeCards.add(new CardIdentity("Hanna, Ship's Navigator", ""));
        cubeCards.add(new CardIdentity("Harmonize", ""));
        cubeCards.add(new CardIdentity("Heartless Hidetsugu", ""));
        cubeCards.add(new CardIdentity("Hedron Archive", ""));
        cubeCards.add(new CardIdentity("Helvault", ""));
        cubeCards.add(new CardIdentity("Hero's Blade", ""));
        cubeCards.add(new CardIdentity("Hero's Demise", ""));
        cubeCards.add(new CardIdentity("Hero's Downfall", ""));
        cubeCards.add(new CardIdentity("Heroes' Podium", ""));
        cubeCards.add(new CardIdentity("Hide // Seek", ""));
        cubeCards.add(new CardIdentity("Hidetsugu's Second Rite", ""));
        cubeCards.add(new CardIdentity("Hinterland Harbor", ""));
        cubeCards.add(new CardIdentity("Homicidal Seclusion", ""));
        cubeCards.add(new CardIdentity("Honden of Cleansing Fire", ""));
        cubeCards.add(new CardIdentity("Honden of Infinite Rage", ""));
        cubeCards.add(new CardIdentity("Honden of Life's Web", ""));
        cubeCards.add(new CardIdentity("Honden of Night's Reach", ""));
        cubeCards.add(new CardIdentity("Honden of Seeing Winds", ""));
        cubeCards.add(new CardIdentity("Honor-Worn Shaku", ""));
        cubeCards.add(new CardIdentity("Horobi, Death's Wail", ""));
        cubeCards.add(new CardIdentity("Hua Tuo, Honored Physician", ""));
        cubeCards.add(new CardIdentity("Hull Breach", ""));
        cubeCards.add(new CardIdentity("Hythonia the Cruel", ""));
        cubeCards.add(new CardIdentity("Ichor Wellspring", ""));
        cubeCards.add(new CardIdentity("Impulse", ""));
        cubeCards.add(new CardIdentity("Into the Roil", ""));
        cubeCards.add(new CardIdentity("Isamaru, Hound of Konda", ""));
        cubeCards.add(new CardIdentity("Isao, Enlightened Bushi", ""));
        cubeCards.add(new CardIdentity("Isolated Chapel", ""));
        cubeCards.add(new CardIdentity("Ith, High Arcanist", ""));
        cubeCards.add(new CardIdentity("Izzet Boilerworks", ""));
        cubeCards.add(new CardIdentity("Izzet Signet", ""));
        cubeCards.add(new CardIdentity("Jace, Vryn's Prodigy", ""));
        cubeCards.add(new CardIdentity("Jareth, Leonine Titan", ""));
        cubeCards.add(new CardIdentity("Jaya Ballard, Task Mage", ""));
        cubeCards.add(new CardIdentity("Jazal Goldmane", ""));
        cubeCards.add(new CardIdentity("Jenara, Asura of War", ""));
        cubeCards.add(new CardIdentity("Jeska, Warrior Adept", ""));
        cubeCards.add(new CardIdentity("Jeskai Ascendancy", ""));
        cubeCards.add(new CardIdentity("Jin-Gitaxias, Core Augur", ""));
        cubeCards.add(new CardIdentity("Jiwari, the Earth Aflame", ""));
        cubeCards.add(new CardIdentity("Jor Kadeen, the Prevailer", ""));
        cubeCards.add(new CardIdentity("Jungle Shrine", ""));
        cubeCards.add(new CardIdentity("Kaervek the Merciless", ""));
        cubeCards.add(new CardIdentity("Kagemaro, First to Suffer", ""));
        cubeCards.add(new CardIdentity("Kaho, Minamo Historian", ""));
        cubeCards.add(new CardIdentity("Kalemne, Disciple of Iroas", ""));
        cubeCards.add(new CardIdentity("Kalitas, Bloodchief of Ghet", ""));
        cubeCards.add(new CardIdentity("Kamahl, Fist of Krosa", ""));
        cubeCards.add(new CardIdentity("Kamahl, Pit Fighter", ""));
        cubeCards.add(new CardIdentity("Karador, Ghost Chieftain", ""));
        cubeCards.add(new CardIdentity("Karlov of the Ghost Council", ""));
        cubeCards.add(new CardIdentity("Karn, Silver Golem", ""));
        cubeCards.add(new CardIdentity("Kataki, War's Wage", ""));
        cubeCards.add(new CardIdentity("Kazuul, Tyrant of the Cliffs", ""));
        cubeCards.add(new CardIdentity("Keiga, the Tide Star", ""));
        cubeCards.add(new CardIdentity("Kemba, Kha Regent", ""));
        cubeCards.add(new CardIdentity("Keranos, God of Storms", ""));
        cubeCards.add(new CardIdentity("Kira, Great Glass-Spinner", ""));
        cubeCards.add(new CardIdentity("Kodama of the North Tree", ""));
        cubeCards.add(new CardIdentity("Kodama's Reach", ""));
        cubeCards.add(new CardIdentity("Kokusho, the Evening Star", ""));
        cubeCards.add(new CardIdentity("Kolaghan's Command", ""));
        cubeCards.add(new CardIdentity("Kolaghan, the Storm's Fury", ""));
        cubeCards.add(new CardIdentity("Konda's Banner", ""));
        cubeCards.add(new CardIdentity("Kongming, \"Sleeping Dragon\"", ""));
        cubeCards.add(new CardIdentity("Kozilek, Butcher of Truth", ""));
        cubeCards.add(new CardIdentity("Krenko, Mob Boss", ""));
        cubeCards.add(new CardIdentity("Kresh the Bloodbraided", ""));
        cubeCards.add(new CardIdentity("Krosan Grip", ""));
        cubeCards.add(new CardIdentity("Krosan Verge", ""));
        cubeCards.add(new CardIdentity("Kumano, Master Yamabushi", ""));
        cubeCards.add(new CardIdentity("Kurkesh, Onakke Ancient", ""));
        cubeCards.add(new CardIdentity("Kytheon, Hero of Akros", ""));
        cubeCards.add(new CardIdentity("Last Stand", ""));
        cubeCards.add(new CardIdentity("Lavalanche", ""));
        cubeCards.add(new CardIdentity("Legacy Weapon", ""));
        cubeCards.add(new CardIdentity("Life's Legacy", ""));
        cubeCards.add(new CardIdentity("Lightning Bolt", ""));
        cubeCards.add(new CardIdentity("Lightning Greaves", ""));
        cubeCards.add(new CardIdentity("Liliana, Heretical Healer", ""));
        cubeCards.add(new CardIdentity("Linvala, Keeper of Silence", ""));
        cubeCards.add(new CardIdentity("Llawan, Cephalid Empress", ""));
        cubeCards.add(new CardIdentity("Lorthos, the Tidemaker", ""));
        cubeCards.add(new CardIdentity("Lu Xun, Scholar General", ""));
        cubeCards.add(new CardIdentity("Lyzolda, the Blood Witch", ""));
        cubeCards.add(new CardIdentity("Maelstrom Nexus", ""));
        cubeCards.add(new CardIdentity("Maelstrom Wanderer", ""));
        cubeCards.add(new CardIdentity("Maga, Traitor to Mortals", ""));
        cubeCards.add(new CardIdentity("Mage's Guile", ""));
        cubeCards.add(new CardIdentity("Mageta the Lion", ""));
        cubeCards.add(new CardIdentity("Mana Reflection", ""));
        cubeCards.add(new CardIdentity("Marath, Will of the Wild", ""));
        cubeCards.add(new CardIdentity("Marble Diamond", ""));
        cubeCards.add(new CardIdentity("March of the Machines", ""));
        cubeCards.add(new CardIdentity("Marchesa, the Black Rose", ""));
        cubeCards.add(new CardIdentity("Marsh Flats", ""));
        cubeCards.add(new CardIdentity("Mayael's Aria", ""));
        cubeCards.add(new CardIdentity("Melek, Izzet Paragon", ""));
        cubeCards.add(new CardIdentity("Memnarch", ""));
        cubeCards.add(new CardIdentity("Meng Huo, Barbarian King", ""));
        cubeCards.add(new CardIdentity("Meren of Clan Nel Toth", ""));
        cubeCards.add(new CardIdentity("Mikaeus, the Lunarch", ""));
        cubeCards.add(new CardIdentity("Mikaeus, the Unhallowed", ""));
        cubeCards.add(new CardIdentity("Mikokoro, Center of the Sea", ""));
        cubeCards.add(new CardIdentity("Minamo, School at Water's Edge", ""));
        cubeCards.add(new CardIdentity("Mind Stone", ""));
        cubeCards.add(new CardIdentity("Mind's Eye", ""));
        cubeCards.add(new CardIdentity("Mindslaver", ""));
        cubeCards.add(new CardIdentity("Mirari", ""));
        cubeCards.add(new CardIdentity("Mirari's Wake", ""));
        cubeCards.add(new CardIdentity("Miren, the Moaning Well", ""));
        cubeCards.add(new CardIdentity("Mirri the Cursed", ""));
        cubeCards.add(new CardIdentity("Mirri, Cat Warrior", ""));
        cubeCards.add(new CardIdentity("Misdirection", ""));
        cubeCards.add(new CardIdentity("Misty Rainforest", ""));
        cubeCards.add(new CardIdentity("Mizzium Mortars", ""));
        cubeCards.add(new CardIdentity("Mizzix of the Izmagnus", ""));
        cubeCards.add(new CardIdentity("Mizzix's Mastery", ""));
        cubeCards.add(new CardIdentity("Molten Slagheap", ""));
        cubeCards.add(new CardIdentity("Momentous Fall", ""));
        cubeCards.add(new CardIdentity("Mortify", ""));
        cubeCards.add(new CardIdentity("Moss Diamond", ""));
        cubeCards.add(new CardIdentity("Mountain Valley", ""));
        cubeCards.add(new CardIdentity("Muddle the Mixture", ""));
        cubeCards.add(new CardIdentity("Multani, Maro-Sorcerer", ""));
        cubeCards.add(new CardIdentity("Muzzio, Visionary Architect", ""));
        cubeCards.add(new CardIdentity("Mycosynth Wellspring", ""));
        cubeCards.add(new CardIdentity("Myojin of Cleansing Fire", ""));
        cubeCards.add(new CardIdentity("Myojin of Life's Web", ""));
        cubeCards.add(new CardIdentity("Myriad Landscape", ""));
        cubeCards.add(new CardIdentity("Mystic Confluence", ""));
        cubeCards.add(new CardIdentity("Mystic Gate", ""));
        cubeCards.add(new CardIdentity("Mystic Monastery", ""));
        cubeCards.add(new CardIdentity("Nagao, Bound by Honor", ""));
        cubeCards.add(new CardIdentity("Nath of the Gilt-Leaf", ""));
        cubeCards.add(new CardIdentity("Naturalize", ""));
        cubeCards.add(new CardIdentity("Negate", ""));
        cubeCards.add(new CardIdentity("Night's Whisper", ""));
        cubeCards.add(new CardIdentity("Nissa's Revelation", ""));
        cubeCards.add(new CardIdentity("Nissa, Vastwood Seer", ""));
        cubeCards.add(new CardIdentity("Niv-Mizzet, Dracogenius", ""));
        cubeCards.add(new CardIdentity("Niv-Mizzet, the Firemind", ""));
        cubeCards.add(new CardIdentity("Nomad Outpost", ""));
        cubeCards.add(new CardIdentity("Noyan Dar, Roil Shaper", ""));
        cubeCards.add(new CardIdentity("Ob Nixilis, the Fallen", ""));
        cubeCards.add(new CardIdentity("Obelisk of Alara", ""));
        cubeCards.add(new CardIdentity("Oblation", ""));
        cubeCards.add(new CardIdentity("Oblivion Ring", ""));
        cubeCards.add(new CardIdentity("Oblivion Stone", ""));
        cubeCards.add(new CardIdentity("Obzedat, Ghost Council", ""));
        cubeCards.add(new CardIdentity("Odric, Master Tactician", ""));
        cubeCards.add(new CardIdentity("Okina, Temple to the Grandfathers", ""));
        cubeCards.add(new CardIdentity("Omnath, Locus of Mana", ""));
        cubeCards.add(new CardIdentity("Omnath, Locus of Rage", ""));
        cubeCards.add(new CardIdentity("Opal-Eye, Konda's Yojimbo", ""));
        cubeCards.add(new CardIdentity("Opulent Palace", ""));
        cubeCards.add(new CardIdentity("Oran-Rief, the Vastwood", ""));
        cubeCards.add(new CardIdentity("Orim, Samite Healer", ""));
        cubeCards.add(new CardIdentity("Orzhov Basilica", ""));
        cubeCards.add(new CardIdentity("Orzhov Signet", ""));
        cubeCards.add(new CardIdentity("Outpost Siege", ""));
        cubeCards.add(new CardIdentity("Overgrown Tomb", ""));
        cubeCards.add(new CardIdentity("Panoptic Mirror", ""));
        cubeCards.add(new CardIdentity("Pariah", ""));
        cubeCards.add(new CardIdentity("Path to Exile", ""));
        cubeCards.add(new CardIdentity("Pernicious Deed", ""));
        cubeCards.add(new CardIdentity("Phage the Untouchable", ""));
        cubeCards.add(new CardIdentity("Phyrexian Arena", ""));
        cubeCards.add(new CardIdentity("Pia and Kiran Nalaar", ""));
        cubeCards.add(new CardIdentity("Pianna, Nomad Captain", ""));
        cubeCards.add(new CardIdentity("Pithing Needle", ""));
        cubeCards.add(new CardIdentity("Plateau", ""));
        cubeCards.add(new CardIdentity("Polluted Delta", ""));
        cubeCards.add(new CardIdentity("Polukranos, World Eater", ""));
        cubeCards.add(new CardIdentity("Praetor's Counsel", ""));
        cubeCards.add(new CardIdentity("Prairie Stream", ""));
        cubeCards.add(new CardIdentity("Prime Speaker Zegana", ""));
        cubeCards.add(new CardIdentity("Primeval Bounty", ""));
        cubeCards.add(new CardIdentity("Prismatic Lens", ""));
        cubeCards.add(new CardIdentity("Progenitus", ""));
        cubeCards.add(new CardIdentity("Prophetic Prism", ""));
        cubeCards.add(new CardIdentity("Psychotic Fury", ""));
        cubeCards.add(new CardIdentity("Pure // Simple", ""));
        cubeCards.add(new CardIdentity("Putrefy", ""));
        cubeCards.add(new CardIdentity("Pyromancer's Goggles", ""));
        cubeCards.add(new CardIdentity("Radha, Heir to Keld", ""));
        cubeCards.add(new CardIdentity("Radiant Purge", ""));
        cubeCards.add(new CardIdentity("Radiant's Judgment", ""));
        cubeCards.add(new CardIdentity("Rafiq of the Many", ""));
        cubeCards.add(new CardIdentity("Rakdos Carnarium", ""));
        cubeCards.add(new CardIdentity("Rakdos Signet", ""));
        cubeCards.add(new CardIdentity("Rakka Mar", ""));
        cubeCards.add(new CardIdentity("Rampant Growth", ""));
        cubeCards.add(new CardIdentity("Ray of Command", ""));
        cubeCards.add(new CardIdentity("Read the Bones", ""));
        cubeCards.add(new CardIdentity("Recoup", ""));
        cubeCards.add(new CardIdentity("Reflecting Pool", ""));
        cubeCards.add(new CardIdentity("Regrowth", ""));
        cubeCards.add(new CardIdentity("Reiterate", ""));
        cubeCards.add(new CardIdentity("Reki, the History of Kamigawa", ""));
        cubeCards.add(new CardIdentity("Repeal", ""));
        cubeCards.add(new CardIdentity("Repulse", ""));
        cubeCards.add(new CardIdentity("Rescind", ""));
        cubeCards.add(new CardIdentity("Reya Dawnbringer", ""));
        cubeCards.add(new CardIdentity("Rhys the Redeemed", ""));
        cubeCards.add(new CardIdentity("Righteous Confluence", ""));
        cubeCards.add(new CardIdentity("Rings of Brighthearth", ""));
        cubeCards.add(new CardIdentity("Rocky Tar Pit", ""));
        cubeCards.add(new CardIdentity("Rofellos, Llanowar Emissary", ""));
        cubeCards.add(new CardIdentity("Rootbound Crag", ""));
        cubeCards.add(new CardIdentity("Rorix Bladewing", ""));
        cubeCards.add(new CardIdentity("Rugged Prairie", ""));
        cubeCards.add(new CardIdentity("Rupture Spire", ""));
        cubeCards.add(new CardIdentity("Ruric Thar, the Unbowed", ""));
        cubeCards.add(new CardIdentity("Rush of Knowledge", ""));
        cubeCards.add(new CardIdentity("Ryusei, the Falling Star", ""));
        cubeCards.add(new CardIdentity("Sachi, Daughter of Seshiro", ""));
        cubeCards.add(new CardIdentity("Sacred Foundry", ""));
        cubeCards.add(new CardIdentity("Saffi Eriksdotter", ""));
        cubeCards.add(new CardIdentity("Sakashima the Impostor", ""));
        cubeCards.add(new CardIdentity("Saltcrusted Steppe", ""));
        cubeCards.add(new CardIdentity("Sandsteppe Citadel", ""));
        cubeCards.add(new CardIdentity("Savage Lands", ""));
        cubeCards.add(new CardIdentity("Savannah", ""));
        cubeCards.add(new CardIdentity("Scalding Tarn", ""));
        cubeCards.add(new CardIdentity("Scion of the Ur-Dragon", ""));
        cubeCards.add(new CardIdentity("Scrap", ""));
        cubeCards.add(new CardIdentity("Scrubland", ""));
        cubeCards.add(new CardIdentity("Sculpting Steel", ""));
        cubeCards.add(new CardIdentity("Search for Tomorrow", ""));
        cubeCards.add(new CardIdentity("Seaside Citadel", ""));
        cubeCards.add(new CardIdentity("Seizan, Perverter of Truth", ""));
        cubeCards.add(new CardIdentity("Selesnya Sanctuary", ""));
        cubeCards.add(new CardIdentity("Selesnya Signet", ""));
        cubeCards.add(new CardIdentity("Sensei Golden-Tail", ""));
        cubeCards.add(new CardIdentity("Sharuum the Hegemon", ""));
        cubeCards.add(new CardIdentity("Shattergang Brothers", ""));
        cubeCards.add(new CardIdentity("Sheoldred, Whispering One", ""));
        cubeCards.add(new CardIdentity("Shinka, the Bloodsoaked Keep", ""));
        cubeCards.add(new CardIdentity("Shizo, Death's Storehouse", ""));
        cubeCards.add(new CardIdentity("Shu Yun, the Silent Tempest", ""));
        cubeCards.add(new CardIdentity("Sidar Jabari", ""));
        cubeCards.add(new CardIdentity("Sidisi, Brood Tyrant", ""));
        cubeCards.add(new CardIdentity("Sidisi, Undead Vizier", ""));
        cubeCards.add(new CardIdentity("Sigarda, Host of Herons", ""));
        cubeCards.add(new CardIdentity("Sign in Blood", ""));
        cubeCards.add(new CardIdentity("Silence the Believers", ""));
        cubeCards.add(new CardIdentity("Silumgar's Command", ""));
        cubeCards.add(new CardIdentity("Silumgar, the Drifting Death", ""));
        cubeCards.add(new CardIdentity("Silvos, Rogue Elemental", ""));
        cubeCards.add(new CardIdentity("Simic Growth Chamber", ""));
        cubeCards.add(new CardIdentity("Simic Signet", ""));
        cubeCards.add(new CardIdentity("Skullbriar, the Walking Grave", ""));
        cubeCards.add(new CardIdentity("Sky Diamond", ""));
        cubeCards.add(new CardIdentity("Skyship Weatherlight", ""));
        cubeCards.add(new CardIdentity("Smoldering Marsh", ""));
        cubeCards.add(new CardIdentity("Song of the Dryads", ""));
        cubeCards.add(new CardIdentity("Sorin's Vengeance", ""));
        cubeCards.add(new CardIdentity("Soul's Fire", ""));
        cubeCards.add(new CardIdentity("Sphere of the Suns", ""));
        cubeCards.add(new CardIdentity("Sphinx-Bone Wand", ""));
        cubeCards.add(new CardIdentity("Spine of Ish Sah", ""));
        cubeCards.add(new CardIdentity("Spirit of the Night", ""));
        cubeCards.add(new CardIdentity("Spite // Malice", ""));
        cubeCards.add(new CardIdentity("Squee, Goblin Nabob", ""));
        cubeCards.add(new CardIdentity("Staff of Nin", ""));
        cubeCards.add(new CardIdentity("Steam Vents", ""));
        cubeCards.add(new CardIdentity("Stitcher Geralf", ""));
        cubeCards.add(new CardIdentity("Stomping Ground", ""));
        cubeCards.add(new CardIdentity("Stubborn Denial", ""));
        cubeCards.add(new CardIdentity("Sulfur Falls", ""));
        cubeCards.add(new CardIdentity("Sultai Charm", ""));
        cubeCards.add(new CardIdentity("Sun Ce, Young Conquerer", ""));
        cubeCards.add(new CardIdentity("Sun Quan, Lord of Wu", ""));
        cubeCards.add(new CardIdentity("Sunken Hollow", ""));
        cubeCards.add(new CardIdentity("Sunken Ruins", ""));
        cubeCards.add(new CardIdentity("Sunpetal Grove", ""));
        cubeCards.add(new CardIdentity("Surrak Dragonclaw", ""));
        cubeCards.add(new CardIdentity("Surrak, the Hunt Caller", ""));
        cubeCards.add(new CardIdentity("Swiftfoot Boots", ""));
        cubeCards.add(new CardIdentity("Sword of the Animist", ""));
        cubeCards.add(new CardIdentity("Sword of the Chosen", ""));
        cubeCards.add(new CardIdentity("Sydri, Galvanic Genius", ""));
        cubeCards.add(new CardIdentity("Sygg, River Cutthroat", ""));
        cubeCards.add(new CardIdentity("Sygg, River Guide", ""));
        cubeCards.add(new CardIdentity("Sylvan Bounty", ""));
        cubeCards.add(new CardIdentity("Tahngarth, Talruum Hero", ""));
        cubeCards.add(new CardIdentity("Taiga", ""));
        cubeCards.add(new CardIdentity("Tainted Pact", ""));
        cubeCards.add(new CardIdentity("Tajic, Blade of the Legion", ""));
        cubeCards.add(new CardIdentity("Talisman of Dominance", ""));
        cubeCards.add(new CardIdentity("Talisman of Impulse", ""));
        cubeCards.add(new CardIdentity("Talisman of Indulgence", ""));
        cubeCards.add(new CardIdentity("Talisman of Progress", ""));
        cubeCards.add(new CardIdentity("Talisman of Unity", ""));
        cubeCards.add(new CardIdentity("Talrand, Sky Summoner", ""));
        cubeCards.add(new CardIdentity("Tasigur, the Golden Fang", ""));
        cubeCards.add(new CardIdentity("Tatsumasa, the Dragon's Fang", ""));
        cubeCards.add(new CardIdentity("Teferi, Mage of Zhalfir", ""));
        cubeCards.add(new CardIdentity("Temple Garden", ""));
        cubeCards.add(new CardIdentity("Temple of Abandon", ""));
        cubeCards.add(new CardIdentity("Temple of Deceit", ""));
        cubeCards.add(new CardIdentity("Temple of Enlightenment", ""));
        cubeCards.add(new CardIdentity("Temple of Epiphany", ""));
        cubeCards.add(new CardIdentity("Temple of Malady", ""));
        cubeCards.add(new CardIdentity("Temple of Malice", ""));
        cubeCards.add(new CardIdentity("Temple of Mystery", ""));
        cubeCards.add(new CardIdentity("Temple of Plenty", ""));
        cubeCards.add(new CardIdentity("Temple of Silence", ""));
        cubeCards.add(new CardIdentity("Temple of the False God", ""));
        cubeCards.add(new CardIdentity("Temple of Triumph", ""));
        cubeCards.add(new CardIdentity("Temur Ascendancy", ""));
        cubeCards.add(new CardIdentity("Temur Battle Rage", ""));
        cubeCards.add(new CardIdentity("Tenza, Godo's Maul", ""));
        cubeCards.add(new CardIdentity("Terminate", ""));
        cubeCards.add(new CardIdentity("Terramorphic Expanse", ""));
        cubeCards.add(new CardIdentity("Terrarion", ""));
        cubeCards.add(new CardIdentity("Teysa, Envoy of Ghosts", ""));
        cubeCards.add(new CardIdentity("Tezzeret the Seeker", ""));
        cubeCards.add(new CardIdentity("Thada Adel, Acquisitor", ""));
        cubeCards.add(new CardIdentity("That Which Was Taken", ""));
        cubeCards.add(new CardIdentity("The Mimeoplasm", ""));
        cubeCards.add(new CardIdentity("Thirst for Knowledge", ""));
        cubeCards.add(new CardIdentity("Thran Dynamo", ""));
        cubeCards.add(new CardIdentity("Thraximundar", ""));
        cubeCards.add(new CardIdentity("Thrun, the Last Troll", ""));
        cubeCards.add(new CardIdentity("Time of Need", ""));
        cubeCards.add(new CardIdentity("Time Stop", ""));
        cubeCards.add(new CardIdentity("Time Warp", ""));
        cubeCards.add(new CardIdentity("Titania, Protector of Argoth", ""));
        cubeCards.add(new CardIdentity("Tithe", ""));
        cubeCards.add(new CardIdentity("Tolsimir Wolfblood", ""));
        cubeCards.add(new CardIdentity("Tomorrow, Azami's Familiar", ""));
        cubeCards.add(new CardIdentity("Tormenting Voice", ""));
        cubeCards.add(new CardIdentity("Toshiro Umezawa", ""));
        cubeCards.add(new CardIdentity("Toxic Deluge", ""));
        cubeCards.add(new CardIdentity("Trading Post", ""));
        cubeCards.add(new CardIdentity("Tragic Slip", ""));
        cubeCards.add(new CardIdentity("Transguild Promenade", ""));
        cubeCards.add(new CardIdentity("Traumatic Visions", ""));
        cubeCards.add(new CardIdentity("Tribute to Hunger", ""));
        cubeCards.add(new CardIdentity("Tromokratis", ""));
        cubeCards.add(new CardIdentity("Tropical Island", ""));
        cubeCards.add(new CardIdentity("Tsabo Tavoc", ""));
        cubeCards.add(new CardIdentity("Tuktuk the Explorer", ""));
        cubeCards.add(new CardIdentity("Tumble Magnet", ""));
        cubeCards.add(new CardIdentity("Tundra", ""));
        cubeCards.add(new CardIdentity("Turn // Burn", ""));
        cubeCards.add(new CardIdentity("Twilight Mire", ""));
        cubeCards.add(new CardIdentity("Tymaret, the Murder King", ""));
        cubeCards.add(new CardIdentity("Ugin's Insight", ""));
        cubeCards.add(new CardIdentity("Ulamog, the Infinite Gyre", ""));
        cubeCards.add(new CardIdentity("Ultimate Price", ""));
        cubeCards.add(new CardIdentity("Underground Sea", ""));
        cubeCards.add(new CardIdentity("Unexpectedly Absent", ""));
        cubeCards.add(new CardIdentity("Unstable Obelisk", ""));
        cubeCards.add(new CardIdentity("Untaidake, the Cloud Keeper", ""));
        cubeCards.add(new CardIdentity("Urabrask the Hidden", ""));
        cubeCards.add(new CardIdentity("Urban Evolution", ""));
        cubeCards.add(new CardIdentity("Urza's Rage", ""));
        cubeCards.add(new CardIdentity("Utter End", ""));
        cubeCards.add(new CardIdentity("Uyo, Silent Prophet", ""));
        cubeCards.add(new CardIdentity("Valorous Stance", ""));
        cubeCards.add(new CardIdentity("Vampiric Tutor", ""));
        cubeCards.add(new CardIdentity("Vanish into Memory", ""));
        cubeCards.add(new CardIdentity("Vedalken Orrery", ""));
        cubeCards.add(new CardIdentity("Vendetta", ""));
        cubeCards.add(new CardIdentity("Vendilion Clique", ""));
        cubeCards.add(new CardIdentity("Venser, Shaper Savant", ""));
        cubeCards.add(new CardIdentity("Verdant Catacombs", ""));
        cubeCards.add(new CardIdentity("Verdant Confluence", ""));
        cubeCards.add(new CardIdentity("Verdeloth the Ancient", ""));
        cubeCards.add(new CardIdentity("Vicious Shadows", ""));
        cubeCards.add(new CardIdentity("Visara the Dreadful", ""));
        cubeCards.add(new CardIdentity("Vish Kal, Blood Arbiter", ""));
        cubeCards.add(new CardIdentity("Volcanic Island", ""));
        cubeCards.add(new CardIdentity("Vorel of the Hull Clade", ""));
        cubeCards.add(new CardIdentity("Vorinclex, Voice of Hunger", ""));
        cubeCards.add(new CardIdentity("Warstorm Surge", ""));
        cubeCards.add(new CardIdentity("Watery Grave", ""));
        cubeCards.add(new CardIdentity("Wayfarer's Bauble", ""));
        cubeCards.add(new CardIdentity("Wear // Tear", ""));
        cubeCards.add(new CardIdentity("Whispers of the Muse", ""));
        cubeCards.add(new CardIdentity("Wild Ricochet", ""));
        cubeCards.add(new CardIdentity("Windswept Heath", ""));
        cubeCards.add(new CardIdentity("Wooded Bastion", ""));
        cubeCards.add(new CardIdentity("Wooded Foothills", ""));
        cubeCards.add(new CardIdentity("Woodland Cemetery", ""));
        cubeCards.add(new CardIdentity("Word of Seizing", ""));
        cubeCards.add(new CardIdentity("Worldly Tutor", ""));
        cubeCards.add(new CardIdentity("Worn Powerstone", ""));
        cubeCards.add(new CardIdentity("Wort, the Raidmother", ""));
        cubeCards.add(new CardIdentity("Wrath of God", ""));
        cubeCards.add(new CardIdentity("Wretched Confluence", ""));
        cubeCards.add(new CardIdentity("Wrexial, the Risen Deep", ""));
        cubeCards.add(new CardIdentity("Wydwen, the Biting Gale", ""));
        cubeCards.add(new CardIdentity("Xenagos, God of Revels", ""));
        cubeCards.add(new CardIdentity("Xiahou Dun, the One-Eyed", ""));
        cubeCards.add(new CardIdentity("Yasova Dragonclaw", ""));
        cubeCards.add(new CardIdentity("Yawgmoth's Agenda", ""));
        cubeCards.add(new CardIdentity("Yeva, Nature's Herald", ""));
        cubeCards.add(new CardIdentity("Yisan, the Wanderer Bard", ""));
        cubeCards.add(new CardIdentity("Yomiji, Who Bars the Way", ""));
        cubeCards.add(new CardIdentity("Yosei, the Morning Star", ""));
        cubeCards.add(new CardIdentity("Zedruu the Greathearted", ""));
        cubeCards.add(new CardIdentity("Zirilan of the Claw", ""));
        cubeCards.add(new CardIdentity("Zurgo Bellstriker", ""));
        cubeCards.add(new CardIdentity("Zurgo Helmsmasher", ""));
    }
}
