package mage.tournament.cubes;

import mage.game.draft.DraftCube;

/**
 * @author fireshoes
 */
public class LegendaryCubeApril2016 extends DraftCube {

    public LegendaryCubeApril2016() {
        super("Legendary Cube April 2016");
        // http://magic.wizards.com/en/MTGO/articles/archive/legendary-cube-cardlist

        cubeCards.add(new DraftCube.CardIdentity("Abundant Growth", ""));
        cubeCards.add(new DraftCube.CardIdentity("Academy Elite", ""));
        cubeCards.add(new DraftCube.CardIdentity("Adamaro, First to Desire", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ajani's Chosen", ""));
        cubeCards.add(new DraftCube.CardIdentity("Akroma's Memorial", ""));
        cubeCards.add(new DraftCube.CardIdentity("Akroma, Angel of Wrath", ""));
        cubeCards.add(new DraftCube.CardIdentity("Akuta, Born of Ash", ""));
        cubeCards.add(new DraftCube.CardIdentity("Alchemist's Vial", ""));
        cubeCards.add(new DraftCube.CardIdentity("Alesha, Who Smiles at Death", ""));
        cubeCards.add(new DraftCube.CardIdentity("Alhammarret's Archive", ""));
        cubeCards.add(new DraftCube.CardIdentity("Alhammarret, High Arbiter", ""));
        cubeCards.add(new DraftCube.CardIdentity("All Suns' Dawn", ""));
        cubeCards.add(new DraftCube.CardIdentity("Anafenza, Kin-Tree Spirit", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ancestral Mask", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ancient Craving", ""));
        cubeCards.add(new DraftCube.CardIdentity("Annihilate", ""));
        cubeCards.add(new DraftCube.CardIdentity("Arcane Denial", ""));
        cubeCards.add(new DraftCube.CardIdentity("Arcane Sanctum", ""));
        cubeCards.add(new DraftCube.CardIdentity("Argothian Enchantress", ""));
        cubeCards.add(new DraftCube.CardIdentity("Armillary Sphere", ""));
        cubeCards.add(new DraftCube.CardIdentity("Army of the Damned", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ashling the Pilgrim", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ashling, the Extinguisher", ""));
        cubeCards.add(new DraftCube.CardIdentity("Atarka, World Render", ""));
        cubeCards.add(new DraftCube.CardIdentity("Augur of Bolas", ""));
        cubeCards.add(new DraftCube.CardIdentity("Aurelia, the Warleader", ""));
        cubeCards.add(new DraftCube.CardIdentity("Avacyn, Angel of Hope", ""));
        cubeCards.add(new DraftCube.CardIdentity("Avacyn, Guardian Angel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Awakening Zone", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ayli, Eternal Pilgrim", ""));
        cubeCards.add(new DraftCube.CardIdentity("Azami, Lady of Scrolls", ""));
        cubeCards.add(new DraftCube.CardIdentity("Azorius Chancery", ""));
        cubeCards.add(new DraftCube.CardIdentity("Azusa, Lost but Seeking", ""));
        cubeCards.add(new DraftCube.CardIdentity("Badlands", ""));
        cubeCards.add(new DraftCube.CardIdentity("Baneslayer Angel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Barren Moor", ""));
        cubeCards.add(new DraftCube.CardIdentity("Basilisk Collar", ""));
        cubeCards.add(new DraftCube.CardIdentity("Bayou", ""));
        cubeCards.add(new DraftCube.CardIdentity("Beacon of Destruction", ""));
        cubeCards.add(new DraftCube.CardIdentity("Beacon of Tomorrows", ""));
        cubeCards.add(new DraftCube.CardIdentity("Bident of Thassa", ""));
        cubeCards.add(new DraftCube.CardIdentity("Bitter Revelation", ""));
        cubeCards.add(new DraftCube.CardIdentity("Black Sun's Zenith", ""));
        cubeCards.add(new DraftCube.CardIdentity("Bladewing the Risen", ""));
        cubeCards.add(new DraftCube.CardIdentity("Blasphemous Act", ""));
        cubeCards.add(new DraftCube.CardIdentity("Blood Crypt", ""));
        cubeCards.add(new DraftCube.CardIdentity("Bogardan Hellkite", ""));
        cubeCards.add(new DraftCube.CardIdentity("Bonehoard", ""));
        cubeCards.add(new DraftCube.CardIdentity("Boros Garrison", ""));
        cubeCards.add(new DraftCube.CardIdentity("Brago, King Eternal", ""));
        cubeCards.add(new DraftCube.CardIdentity("Braid of Fire", ""));
        cubeCards.add(new DraftCube.CardIdentity("Brainstorm", ""));
        cubeCards.add(new DraftCube.CardIdentity("Breeding Pool", ""));
        cubeCards.add(new DraftCube.CardIdentity("Brimaz, King of Oreskos", ""));
        cubeCards.add(new DraftCube.CardIdentity("Brion Stoutarm", ""));
        cubeCards.add(new DraftCube.CardIdentity("Brittle Effigy", ""));
        cubeCards.add(new DraftCube.CardIdentity("Buried Ruin", ""));
        cubeCards.add(new DraftCube.CardIdentity("Burn Away", ""));
        cubeCards.add(new DraftCube.CardIdentity("Burnished Hart", ""));
        cubeCards.add(new DraftCube.CardIdentity("Cage of Hands", ""));
        cubeCards.add(new DraftCube.CardIdentity("Caged Sun", ""));
        cubeCards.add(new DraftCube.CardIdentity("Call the Skybreaker", ""));
        cubeCards.add(new DraftCube.CardIdentity("Captain Sisay", ""));
        cubeCards.add(new DraftCube.CardIdentity("Cast Through Time", ""));
        cubeCards.add(new DraftCube.CardIdentity("Cauldron of Souls", ""));
        cubeCards.add(new DraftCube.CardIdentity("Celestial Flare", ""));
        cubeCards.add(new DraftCube.CardIdentity("Cephalid Coliseum", ""));
        cubeCards.add(new DraftCube.CardIdentity("Chain Reaction", ""));
        cubeCards.add(new DraftCube.CardIdentity("Champion's Helm", ""));
        cubeCards.add(new DraftCube.CardIdentity("Chandra, the Firebrand", ""));
        cubeCards.add(new DraftCube.CardIdentity("Chaos Warp", ""));
        cubeCards.add(new DraftCube.CardIdentity("Charcoal Diamond", ""));
        cubeCards.add(new DraftCube.CardIdentity("Charmbreaker Devils", ""));
        cubeCards.add(new DraftCube.CardIdentity("Cho-Manno, Revolutionary", ""));
        cubeCards.add(new DraftCube.CardIdentity("Citadel Siege", ""));
        cubeCards.add(new DraftCube.CardIdentity("Clifftop Retreat", ""));
        cubeCards.add(new DraftCube.CardIdentity("Coldsteel Heart", ""));
        cubeCards.add(new DraftCube.CardIdentity("Commune with the Gods", ""));
        cubeCards.add(new DraftCube.CardIdentity("Compulsive Research", ""));
        cubeCards.add(new DraftCube.CardIdentity("Conjurer's Closet", ""));
        cubeCards.add(new DraftCube.CardIdentity("Corpse Churn", ""));
        cubeCards.add(new DraftCube.CardIdentity("Corpsehatch", ""));
        cubeCards.add(new DraftCube.CardIdentity("Courser of Kruphix", ""));
        cubeCards.add(new DraftCube.CardIdentity("Crib Swap", ""));
        cubeCards.add(new DraftCube.CardIdentity("Crovax, Ascendant Hero", ""));
        cubeCards.add(new DraftCube.CardIdentity("Crucible of the Spirit Dragon", ""));
        cubeCards.add(new DraftCube.CardIdentity("Cruel Ultimatum", ""));
        cubeCards.add(new DraftCube.CardIdentity("Crumbling Necropolis", ""));
        cubeCards.add(new DraftCube.CardIdentity("Crush of Tentacles", ""));
        cubeCards.add(new DraftCube.CardIdentity("Crux of Fate", ""));
        cubeCards.add(new DraftCube.CardIdentity("Crypt of Agadeem", ""));
        cubeCards.add(new DraftCube.CardIdentity("Crystal Ball", ""));
        cubeCards.add(new DraftCube.CardIdentity("Cyclonic Rift", ""));
        cubeCards.add(new DraftCube.CardIdentity("Daghatar the Adamant", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dakra Mystic", ""));
        cubeCards.add(new DraftCube.CardIdentity("Daretti, Scrap Savant", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dark Petition", ""));
        cubeCards.add(new DraftCube.CardIdentity("Darksteel Ingot", ""));
        cubeCards.add(new DraftCube.CardIdentity("Darksteel Myr", ""));
        cubeCards.add(new DraftCube.CardIdentity("Daxos the Returned", ""));
        cubeCards.add(new DraftCube.CardIdentity("Day of Destiny", ""));
        cubeCards.add(new DraftCube.CardIdentity("Death Denied", ""));
        cubeCards.add(new DraftCube.CardIdentity("Deathbringer Regent", ""));
        cubeCards.add(new DraftCube.CardIdentity("Deep Analysis", ""));
        cubeCards.add(new DraftCube.CardIdentity("Devour in Shadow", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dimir Aqueduct", ""));
        cubeCards.add(new DraftCube.CardIdentity("Disciple of the Ring", ""));
        cubeCards.add(new DraftCube.CardIdentity("Divine Deflection", ""));
        cubeCards.add(new DraftCube.CardIdentity("Doomwake Giant", ""));
        cubeCards.add(new DraftCube.CardIdentity("Doubling Season", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dragon Tempest", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonlord Atarka", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonlord Dromoka", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonlord Ojutai", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonlord Silumgar", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonskull Summit", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonspeaker Shaman", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dragonstorm", ""));
        cubeCards.add(new DraftCube.CardIdentity("Drana, Kalastria Bloodchief", ""));
        cubeCards.add(new DraftCube.CardIdentity("Drana, Liberator of Malakir", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dread Summons", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dreamstone Hedron", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dregs of Sorrow", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dromoka, the Eternal", ""));
        cubeCards.add(new DraftCube.CardIdentity("Drowned Catacomb", ""));
        cubeCards.add(new DraftCube.CardIdentity("Druidic Satchel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Duress", ""));
        cubeCards.add(new DraftCube.CardIdentity("Dwynen, Gilt-Leaf Daen", ""));
        cubeCards.add(new DraftCube.CardIdentity("Edric, Spymaster of Trest", ""));
        cubeCards.add(new DraftCube.CardIdentity("Eidolon of Blossoms", ""));
        cubeCards.add(new DraftCube.CardIdentity("Eiganjo Castle", ""));
        cubeCards.add(new DraftCube.CardIdentity("Eight-and-a-Half-Tails", ""));
        cubeCards.add(new DraftCube.CardIdentity("Elbrus, the Binding Blade", ""));
        cubeCards.add(new DraftCube.CardIdentity("Elesh Norn, Grand Cenobite", ""));
        cubeCards.add(new DraftCube.CardIdentity("Elsewhere Flask", ""));
        cubeCards.add(new DraftCube.CardIdentity("Elvish Harbinger", ""));
        cubeCards.add(new DraftCube.CardIdentity("Empty the Catacombs", ""));
        cubeCards.add(new DraftCube.CardIdentity("Emrakul, the Aeons Torn", ""));
        cubeCards.add(new DraftCube.CardIdentity("Enchantress's Presence", ""));
        cubeCards.add(new DraftCube.CardIdentity("Endrek Sahr, Master Breeder", ""));
        cubeCards.add(new DraftCube.CardIdentity("Enduring Ideal", ""));
        cubeCards.add(new DraftCube.CardIdentity("Engineered Explosives", ""));
        cubeCards.add(new DraftCube.CardIdentity("Epic Proportions", ""));
        cubeCards.add(new DraftCube.CardIdentity("Eternal Dragon", ""));
        cubeCards.add(new DraftCube.CardIdentity("Everflowing Chalice", ""));
        cubeCards.add(new DraftCube.CardIdentity("Evil Twin", ""));
        cubeCards.add(new DraftCube.CardIdentity("Evolving Wilds", ""));
        cubeCards.add(new DraftCube.CardIdentity("Exile into Darkness", ""));
        cubeCards.add(new DraftCube.CardIdentity("Expedition Map", ""));
        cubeCards.add(new DraftCube.CardIdentity("Explore", ""));
        cubeCards.add(new DraftCube.CardIdentity("Explosive Revelation", ""));
        cubeCards.add(new DraftCube.CardIdentity("Explosive Vegetation", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ezuri, Claw of Progress", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ezuri, Renegade Leader", ""));
        cubeCards.add(new DraftCube.CardIdentity("Fable of Wolf and Owl", ""));
        cubeCards.add(new DraftCube.CardIdentity("Fact or Fiction", ""));
        cubeCards.add(new DraftCube.CardIdentity("Faerie Mechanist", ""));
        cubeCards.add(new DraftCube.CardIdentity("Faith's Fetters", ""));
        cubeCards.add(new DraftCube.CardIdentity("Faithless Looting", ""));
        cubeCards.add(new DraftCube.CardIdentity("Farhaven Elf", ""));
        cubeCards.add(new DraftCube.CardIdentity("Fated Retribution", ""));
        cubeCards.add(new DraftCube.CardIdentity("Fellwar Stone", ""));
        cubeCards.add(new DraftCube.CardIdentity("Fertile Ground", ""));
        cubeCards.add(new DraftCube.CardIdentity("Fierce Empath", ""));
        cubeCards.add(new DraftCube.CardIdentity("Fiery Fall", ""));
        cubeCards.add(new DraftCube.CardIdentity("Fire Diamond", ""));
        cubeCards.add(new DraftCube.CardIdentity("Flamekin Village", ""));
        cubeCards.add(new DraftCube.CardIdentity("Forbidden Alchemy", ""));
        cubeCards.add(new DraftCube.CardIdentity("Forced March", ""));
        cubeCards.add(new DraftCube.CardIdentity("Forgotten Cave", ""));
        cubeCards.add(new DraftCube.CardIdentity("Foul Renewal", ""));
        cubeCards.add(new DraftCube.CardIdentity("Foul-Tongue Invocation", ""));
        cubeCards.add(new DraftCube.CardIdentity("Frontier Bivouac", ""));
        cubeCards.add(new DraftCube.CardIdentity("Frontier Siege", ""));
        cubeCards.add(new DraftCube.CardIdentity("Galvanoth", ""));
        cubeCards.add(new DraftCube.CardIdentity("Genesis Wave", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ghastly Demise", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ghave, Guru of Spores", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ghoulcaller Gisa", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ghoultree", ""));
        cubeCards.add(new DraftCube.CardIdentity("Gild", ""));
        cubeCards.add(new DraftCube.CardIdentity("Gilded Lotus", ""));
        cubeCards.add(new DraftCube.CardIdentity("Glacial Fortress", ""));
        cubeCards.add(new DraftCube.CardIdentity("Glimmerpoint Stag", ""));
        cubeCards.add(new DraftCube.CardIdentity("Glissa Sunseeker", ""));
        cubeCards.add(new DraftCube.CardIdentity("Godless Shrine", ""));
        cubeCards.add(new DraftCube.CardIdentity("Godo, Bandit Warlord", ""));
        cubeCards.add(new DraftCube.CardIdentity("Golgari Grave-Troll", ""));
        cubeCards.add(new DraftCube.CardIdentity("Golgari Rot Farm", ""));
        cubeCards.add(new DraftCube.CardIdentity("Graveblade Marauder", ""));
        cubeCards.add(new DraftCube.CardIdentity("Grenzo, Dungeon Warden", ""));
        cubeCards.add(new DraftCube.CardIdentity("Griselbrand", ""));
        cubeCards.add(new DraftCube.CardIdentity("Grisly Salvage", ""));
        cubeCards.add(new DraftCube.CardIdentity("Gruul Turf", ""));
        cubeCards.add(new DraftCube.CardIdentity("Haakon, Stromgald Scourge", ""));
        cubeCards.add(new DraftCube.CardIdentity("Hallowed Burial", ""));
        cubeCards.add(new DraftCube.CardIdentity("Hallowed Fountain", ""));
        cubeCards.add(new DraftCube.CardIdentity("Haven of the Spirit Dragon", ""));
        cubeCards.add(new DraftCube.CardIdentity("Havengul Lich", ""));
        cubeCards.add(new DraftCube.CardIdentity("Havengul Runebinder", ""));
        cubeCards.add(new DraftCube.CardIdentity("Heartless Hidetsugu", ""));
        cubeCards.add(new DraftCube.CardIdentity("Hedron Archive", ""));
        cubeCards.add(new DraftCube.CardIdentity("Heliod, God of the Sun", ""));
        cubeCards.add(new DraftCube.CardIdentity("Helvault", ""));
        cubeCards.add(new DraftCube.CardIdentity("Herald of the Pantheon", ""));
        cubeCards.add(new DraftCube.CardIdentity("Hero's Blade", ""));
        cubeCards.add(new DraftCube.CardIdentity("Heroes' Podium", ""));
        cubeCards.add(new DraftCube.CardIdentity("Hide // Seek", ""));
        cubeCards.add(new DraftCube.CardIdentity("Hinterland Harbor", ""));
        cubeCards.add(new DraftCube.CardIdentity("Hoarding Dragon", ""));
        cubeCards.add(new DraftCube.CardIdentity("Honden of Cleansing Fire", ""));
        cubeCards.add(new DraftCube.CardIdentity("Honden of Infinite Rage", ""));
        cubeCards.add(new DraftCube.CardIdentity("Honden of Life's Web", ""));
        cubeCards.add(new DraftCube.CardIdentity("Honden of Night's Reach", ""));
        cubeCards.add(new DraftCube.CardIdentity("Honden of Seeing Winds", ""));
        cubeCards.add(new DraftCube.CardIdentity("Honor-Worn Shaku", ""));
        cubeCards.add(new DraftCube.CardIdentity("Horobi, Death's Wail", ""));
        cubeCards.add(new DraftCube.CardIdentity("Hull Breach", ""));
        cubeCards.add(new DraftCube.CardIdentity("Hythonia the Cruel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ichor Wellspring", ""));
        cubeCards.add(new DraftCube.CardIdentity("Idyllic Tutor", ""));
        cubeCards.add(new DraftCube.CardIdentity("Immaculate Magistrate", ""));
        cubeCards.add(new DraftCube.CardIdentity("Imperious Perfect", ""));
        cubeCards.add(new DraftCube.CardIdentity("Impulse", ""));
        cubeCards.add(new DraftCube.CardIdentity("Increasing Vengeance", ""));
        cubeCards.add(new DraftCube.CardIdentity("Interpret the Signs", ""));
        cubeCards.add(new DraftCube.CardIdentity("Into the Roil", ""));
        cubeCards.add(new DraftCube.CardIdentity("Isamaru, Hound of Konda", ""));
        cubeCards.add(new DraftCube.CardIdentity("Isolated Chapel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Izzet Boilerworks", ""));
        cubeCards.add(new DraftCube.CardIdentity("Jace's Sanctum", ""));
        cubeCards.add(new DraftCube.CardIdentity("Jace, Vryn's Prodigy", ""));
        cubeCards.add(new DraftCube.CardIdentity("Jarad, Golgari Lich Lord", ""));
        cubeCards.add(new DraftCube.CardIdentity("Jareth, Leonine Titan", ""));
        cubeCards.add(new DraftCube.CardIdentity("Jaya Ballard, Task Mage", ""));
        cubeCards.add(new DraftCube.CardIdentity("Jazal Goldmane", ""));
        cubeCards.add(new DraftCube.CardIdentity("Jeska, Warrior Adept", ""));
        cubeCards.add(new DraftCube.CardIdentity("Jeskai Ascendancy", ""));
        cubeCards.add(new DraftCube.CardIdentity("Jiwari, the Earth Aflame", ""));
        cubeCards.add(new DraftCube.CardIdentity("Jor Kadeen, the Prevailer", ""));
        cubeCards.add(new DraftCube.CardIdentity("Joraga Warcaller", ""));
        cubeCards.add(new DraftCube.CardIdentity("Jungle Shrine", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kaervek the Merciless", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kagemaro, First to Suffer", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kaho, Minamo Historian", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kaleidostone", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kalitas, Bloodchief of Ghet", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kalitas, Traitor of Ghet", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kamahl, Pit Fighter", ""));
        cubeCards.add(new DraftCube.CardIdentity("Karador, Ghost Chieftain", ""));
        cubeCards.add(new DraftCube.CardIdentity("Karlov of the Ghost Council", ""));
        cubeCards.add(new DraftCube.CardIdentity("Karn, Silver Golem", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kataki, War's Wage", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kazuul, Tyrant of the Cliffs", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kederekt Leviathan", ""));
        cubeCards.add(new DraftCube.CardIdentity("Keiga, the Tide Star", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kemba, Kha Regent", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kilnmouth Dragon", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kira, Great Glass-Spinner", ""));
        cubeCards.add(new DraftCube.CardIdentity("Knight of the White Orchid", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kokusho, the Evening Star", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kolaghan, the Storm's Fury", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kothophed, Soul Hoarder", ""));
        cubeCards.add(new DraftCube.CardIdentity("Krenko, Mob Boss", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kresh the Bloodbraided", ""));
        cubeCards.add(new DraftCube.CardIdentity("Krosan Verge", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kruphix's Insight", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kurkesh, Onakke Ancient", ""));
        cubeCards.add(new DraftCube.CardIdentity("Kytheon, Hero of Akros", ""));
        cubeCards.add(new DraftCube.CardIdentity("Lavalanche", ""));
        cubeCards.add(new DraftCube.CardIdentity("Lavinia of the Tenth", ""));
        cubeCards.add(new DraftCube.CardIdentity("Life from the Loam", ""));
        cubeCards.add(new DraftCube.CardIdentity("Lightning Greaves", ""));
        cubeCards.add(new DraftCube.CardIdentity("Lightning Surge", ""));
        cubeCards.add(new DraftCube.CardIdentity("Linvala, Keeper of Silence", ""));
        cubeCards.add(new DraftCube.CardIdentity("Linvala, the Preserver", ""));
        cubeCards.add(new DraftCube.CardIdentity("Lonely Sandbar", ""));
        cubeCards.add(new DraftCube.CardIdentity("Lord of Extinction", ""));
        cubeCards.add(new DraftCube.CardIdentity("Lotus Vale", ""));
        cubeCards.add(new DraftCube.CardIdentity("Lu Xun, Scholar General", ""));
        cubeCards.add(new DraftCube.CardIdentity("Lyzolda, the Blood Witch", ""));
        cubeCards.add(new DraftCube.CardIdentity("Maelstrom Wanderer", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mageta the Lion", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mana Bloom", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mana Reflection", ""));
        cubeCards.add(new DraftCube.CardIdentity("Marath, Will of the Wild", ""));
        cubeCards.add(new DraftCube.CardIdentity("Marble Diamond", ""));
        cubeCards.add(new DraftCube.CardIdentity("March of the Machines", ""));
        cubeCards.add(new DraftCube.CardIdentity("Martial Law", ""));
        cubeCards.add(new DraftCube.CardIdentity("Masked Admirers", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mayael the Anima", ""));
        cubeCards.add(new DraftCube.CardIdentity("Melek, Izzet Paragon", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mental Note", ""));
        cubeCards.add(new DraftCube.CardIdentity("Meren of Clan Nel Toth", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mesa Enchantress", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mikaeus, the Lunarch", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mikaeus, the Unhallowed", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mikokoro, Center of the Sea", ""));
        cubeCards.add(new DraftCube.CardIdentity("Millikin", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mimic Vat", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mina and Denn, Wildborn", ""));
        cubeCards.add(new DraftCube.CardIdentity("Minamo, School at Water's Edge", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mind Stone", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mind's Eye", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mirari", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mirari's Wake", ""));
        cubeCards.add(new DraftCube.CardIdentity("Miren, the Moaning Well", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mirri the Cursed", ""));
        cubeCards.add(new DraftCube.CardIdentity("Misdirection", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mizzium Mortars", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mizzix of the Izmagnus", ""));
        cubeCards.add(new DraftCube.CardIdentity("Momir Vig, Simic Visionary", ""));
        cubeCards.add(new DraftCube.CardIdentity("Moss Diamond", ""));
        cubeCards.add(new DraftCube.CardIdentity("Muddle the Mixture", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mulch", ""));
        cubeCards.add(new DraftCube.CardIdentity("Muzzio, Visionary Architect", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mycosynth Wellspring", ""));
        cubeCards.add(new DraftCube.CardIdentity("Myojin of Cleansing Fire", ""));
        cubeCards.add(new DraftCube.CardIdentity("Myr Battlesphere", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mystic Monastery", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mystic Restraints", ""));
        cubeCards.add(new DraftCube.CardIdentity("Mystical Teachings", ""));
        cubeCards.add(new DraftCube.CardIdentity("Nameless Inversion", ""));
        cubeCards.add(new DraftCube.CardIdentity("Narset, Enlightened Master", ""));
        cubeCards.add(new DraftCube.CardIdentity("Nature's Resurgence", ""));
        cubeCards.add(new DraftCube.CardIdentity("Night's Whisper", ""));
        cubeCards.add(new DraftCube.CardIdentity("Nighthowler", ""));
        cubeCards.add(new DraftCube.CardIdentity("Nissa's Revelation", ""));
        cubeCards.add(new DraftCube.CardIdentity("Nissa, Vastwood Seer", ""));
        cubeCards.add(new DraftCube.CardIdentity("Niv-Mizzet, Dracogenius", ""));
        cubeCards.add(new DraftCube.CardIdentity("Niv-Mizzet, the Firemind", ""));
        cubeCards.add(new DraftCube.CardIdentity("Nomad Outpost", ""));
        cubeCards.add(new DraftCube.CardIdentity("Noyan Dar, Roil Shaper", ""));
        cubeCards.add(new DraftCube.CardIdentity("Nylea, God of the Hunt", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ob Nixilis, the Fallen", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ob Nixilis, Unshackled", ""));
        cubeCards.add(new DraftCube.CardIdentity("Oblation", ""));
        cubeCards.add(new DraftCube.CardIdentity("Oblivion Stone", ""));
        cubeCards.add(new DraftCube.CardIdentity("Obzedat, Ghost Council", ""));
        cubeCards.add(new DraftCube.CardIdentity("Odric, Master Tactician", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ojutai, Soul of Winter", ""));
        cubeCards.add(new DraftCube.CardIdentity("Okina, Temple to the Grandfathers", ""));
        cubeCards.add(new DraftCube.CardIdentity("Omnath, Locus of Mana", ""));
        cubeCards.add(new DraftCube.CardIdentity("Opalescence", ""));
        cubeCards.add(new DraftCube.CardIdentity("Opulent Palace", ""));
        cubeCards.add(new DraftCube.CardIdentity("Oran-Rief, the Vastwood", ""));
        cubeCards.add(new DraftCube.CardIdentity("Orim, Samite Healer", ""));
        cubeCards.add(new DraftCube.CardIdentity("Orzhov Basilica", ""));
        cubeCards.add(new DraftCube.CardIdentity("Outpost Siege", ""));
        cubeCards.add(new DraftCube.CardIdentity("Overgrown Tomb", ""));
        cubeCards.add(new DraftCube.CardIdentity("Pacifism", ""));
        cubeCards.add(new DraftCube.CardIdentity("Pariah", ""));
        cubeCards.add(new DraftCube.CardIdentity("Perilous Vault", ""));
        cubeCards.add(new DraftCube.CardIdentity("Phage the Untouchable", ""));
        cubeCards.add(new DraftCube.CardIdentity("Pharika, God of Affliction", ""));
        cubeCards.add(new DraftCube.CardIdentity("Phyrexian Arena", ""));
        cubeCards.add(new DraftCube.CardIdentity("Phyrexian Ingester", ""));
        cubeCards.add(new DraftCube.CardIdentity("Phyrexian Metamorph", ""));
        cubeCards.add(new DraftCube.CardIdentity("Pia and Kiran Nalaar", ""));
        cubeCards.add(new DraftCube.CardIdentity("Pianna, Nomad Captain", ""));
        cubeCards.add(new DraftCube.CardIdentity("Pilgrim's Eye", ""));
        cubeCards.add(new DraftCube.CardIdentity("Planar Cleansing", ""));
        cubeCards.add(new DraftCube.CardIdentity("Plateau", ""));
        cubeCards.add(new DraftCube.CardIdentity("Platinum Angel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Plea for Guidance", ""));
        cubeCards.add(new DraftCube.CardIdentity("Polymorphist's Jest", ""));
        cubeCards.add(new DraftCube.CardIdentity("Praetor's Counsel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Priest of Titania", ""));
        cubeCards.add(new DraftCube.CardIdentity("Prime Speaker Zegana", ""));
        cubeCards.add(new DraftCube.CardIdentity("Primeval Bounty", ""));
        cubeCards.add(new DraftCube.CardIdentity("Prismatic Lens", ""));
        cubeCards.add(new DraftCube.CardIdentity("Pristine Talisman", ""));
        cubeCards.add(new DraftCube.CardIdentity("Prohibit", ""));
        cubeCards.add(new DraftCube.CardIdentity("Prophetic Bolt", ""));
        cubeCards.add(new DraftCube.CardIdentity("Pull from the Deep", ""));
        cubeCards.add(new DraftCube.CardIdentity("Pyromancer's Goggles", ""));
        cubeCards.add(new DraftCube.CardIdentity("Radha, Heir to Keld", ""));
        cubeCards.add(new DraftCube.CardIdentity("Radiant Purge", ""));
        cubeCards.add(new DraftCube.CardIdentity("Rafiq of the Many", ""));
        cubeCards.add(new DraftCube.CardIdentity("Rakdos Carnarium", ""));
        cubeCards.add(new DraftCube.CardIdentity("Rakka Mar", ""));
        cubeCards.add(new DraftCube.CardIdentity("Read the Bones", ""));
        cubeCards.add(new DraftCube.CardIdentity("Reclamation Sage", ""));
        cubeCards.add(new DraftCube.CardIdentity("Recumbent Bliss", ""));
        cubeCards.add(new DraftCube.CardIdentity("Reflecting Pool", ""));
        cubeCards.add(new DraftCube.CardIdentity("Regrowth", ""));
        cubeCards.add(new DraftCube.CardIdentity("Reiterate", ""));
        cubeCards.add(new DraftCube.CardIdentity("Reki, the History of Kamigawa", ""));
        cubeCards.add(new DraftCube.CardIdentity("Repeal", ""));
        cubeCards.add(new DraftCube.CardIdentity("Resounding Thunder", ""));
        cubeCards.add(new DraftCube.CardIdentity("Reya Dawnbringer", ""));
        cubeCards.add(new DraftCube.CardIdentity("Rhys the Redeemed", ""));
        cubeCards.add(new DraftCube.CardIdentity("Rhys the Exiled", ""));
        cubeCards.add(new DraftCube.CardIdentity("Rings of Brighthearth", ""));
        cubeCards.add(new DraftCube.CardIdentity("Roast", ""));
        cubeCards.add(new DraftCube.CardIdentity("Rofellos, Llanowar Emissary", ""));
        cubeCards.add(new DraftCube.CardIdentity("Roon of the Hidden Realm", ""));
        cubeCards.add(new DraftCube.CardIdentity("Rootbound Crag", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ruinous Path", ""));
        cubeCards.add(new DraftCube.CardIdentity("Runechanter's Pike", ""));
        cubeCards.add(new DraftCube.CardIdentity("Rupture Spire", ""));
        cubeCards.add(new DraftCube.CardIdentity("Rush of Knowledge", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ryusei, the Falling Star", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sacred Foundry", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sakashima the Impostor", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sandsteppe Citadel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sarkhan's Triumph", ""));
        cubeCards.add(new DraftCube.CardIdentity("Savage Lands", ""));
        cubeCards.add(new DraftCube.CardIdentity("Savannah", ""));
        cubeCards.add(new DraftCube.CardIdentity("Scion of the Ur-Dragon", ""));
        cubeCards.add(new DraftCube.CardIdentity("Scourge of Nel Toth", ""));
        cubeCards.add(new DraftCube.CardIdentity("Scrabbling Claws", ""));
        cubeCards.add(new DraftCube.CardIdentity("Scrap", ""));
        cubeCards.add(new DraftCube.CardIdentity("Scrubland", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sculpting Steel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Seal of Cleansing", ""));
        cubeCards.add(new DraftCube.CardIdentity("Seaside Citadel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Secluded Steppe", ""));
        cubeCards.add(new DraftCube.CardIdentity("Seer's Lantern", ""));
        cubeCards.add(new DraftCube.CardIdentity("Seer's Sundial", ""));
        cubeCards.add(new DraftCube.CardIdentity("Seizan, Perverter of Truth", ""));
        cubeCards.add(new DraftCube.CardIdentity("Selesnya Sanctuary", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sensei Golden-Tail", ""));
        cubeCards.add(new DraftCube.CardIdentity("Selvala, Explorer Returned", ""));
        cubeCards.add(new DraftCube.CardIdentity("Serra's Sanctum", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sewer Nemesis", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sharuum the Hegemon", ""));
        cubeCards.add(new DraftCube.CardIdentity("Shinka, the Bloodsoaked Keep", ""));
        cubeCards.add(new DraftCube.CardIdentity("Shizo, Death's Storehouse", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sidar Jabari", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sidisi, Brood Tyrant", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sidisi, Undead Vizier", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sigil of the Empty Throne", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sign in Blood", ""));
        cubeCards.add(new DraftCube.CardIdentity("Silent Sentinel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Silkwrap", ""));
        cubeCards.add(new DraftCube.CardIdentity("Silumgar, the Drifting Death", ""));
        cubeCards.add(new DraftCube.CardIdentity("Simic Growth Chamber", ""));
        cubeCards.add(new DraftCube.CardIdentity("Skaab Ruinator", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sky Diamond", ""));
        cubeCards.add(new DraftCube.CardIdentity("Skybind", ""));
        cubeCards.add(new DraftCube.CardIdentity("Slice in Twain", ""));
        cubeCards.add(new DraftCube.CardIdentity("Smother", ""));
        cubeCards.add(new DraftCube.CardIdentity("Solemn Simulacrum", ""));
        cubeCards.add(new DraftCube.CardIdentity("Song of the Dryads", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sphinx-Bone Wand", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sphinx of Uthuun", ""));
        cubeCards.add(new DraftCube.CardIdentity("Spider Spawning", ""));
        cubeCards.add(new DraftCube.CardIdentity("Spine of Ish Sah", ""));
        cubeCards.add(new DraftCube.CardIdentity("Spite // Malice", ""));
        cubeCards.add(new DraftCube.CardIdentity("Splinterfright", ""));
        cubeCards.add(new DraftCube.CardIdentity("Springjack Pasture", ""));
        cubeCards.add(new DraftCube.CardIdentity("Squee, Goblin Nabob", ""));
        cubeCards.add(new DraftCube.CardIdentity("Staff of Nin", ""));
        cubeCards.add(new DraftCube.CardIdentity("Starfield of Nyx", ""));
        cubeCards.add(new DraftCube.CardIdentity("Steam Vents", ""));
        cubeCards.add(new DraftCube.CardIdentity("Stitcher Geralf", ""));
        cubeCards.add(new DraftCube.CardIdentity("Stomping Ground", ""));
        cubeCards.add(new DraftCube.CardIdentity("Strategic Planning", ""));
        cubeCards.add(new DraftCube.CardIdentity("Stubborn Denial", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sudden Reclamation", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sulfur Falls", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sultai Charm", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sun Ce, Young Conquerer", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sun Quan, Lord of Wu", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sunpetal Grove", ""));
        cubeCards.add(new DraftCube.CardIdentity("Swiftfoot Boots", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sword of the Animist", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sword of the Chosen", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sylvan Messenger", ""));
        cubeCards.add(new DraftCube.CardIdentity("Sylvan Ranger", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tahngarth, Talruum Hero", ""));
        cubeCards.add(new DraftCube.CardIdentity("Taiga", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tainted Pact", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tajic, Blade of the Legion", ""));
        cubeCards.add(new DraftCube.CardIdentity("Talrand, Sky Summoner", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tasigur, the Golden Fang", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tatsumasa, the Dragon's Fang", ""));
        cubeCards.add(new DraftCube.CardIdentity("Teferi, Mage of Zhalfir", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple Garden", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple of Abandon", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple of Deceit", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple of Enlightenment", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple of Epiphany", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple of Malady", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple of Malice", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple of Mystery", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple of Plenty", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple of Silence", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple of the False God", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temple of Triumph", ""));
        cubeCards.add(new DraftCube.CardIdentity("Temur Ascendancy", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tenza, Godo's Maul", ""));
        cubeCards.add(new DraftCube.CardIdentity("Terashi's Grasp", ""));
        cubeCards.add(new DraftCube.CardIdentity("Terramorphic Expanse", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tezzeret the Seeker", ""));
        cubeCards.add(new DraftCube.CardIdentity("Thada Adel, Acquisitor", ""));
        cubeCards.add(new DraftCube.CardIdentity("Thirst for Knowledge", ""));
        cubeCards.add(new DraftCube.CardIdentity("Thought Vessel", ""));
        cubeCards.add(new DraftCube.CardIdentity("Thraximundar", ""));
        cubeCards.add(new DraftCube.CardIdentity("Thunder Dragon", ""));
        cubeCards.add(new DraftCube.CardIdentity("Thunderbreak Regent", ""));
        cubeCards.add(new DraftCube.CardIdentity("Time of Need", ""));
        cubeCards.add(new DraftCube.CardIdentity("Time Stop", ""));
        cubeCards.add(new DraftCube.CardIdentity("Titania, Protector of Argoth", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tithe", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tombstone Stairwell", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tormenting Voice", ""));
        cubeCards.add(new DraftCube.CardIdentity("Toshiro Umezawa", ""));
        cubeCards.add(new DraftCube.CardIdentity("Toxic Deluge", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tracker's Instincts", ""));
        cubeCards.add(new DraftCube.CardIdentity("Trading Post", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tranquil Thicket", ""));
        cubeCards.add(new DraftCube.CardIdentity("Transguild Promenade", ""));
        cubeCards.add(new DraftCube.CardIdentity("Trash for Treasure", ""));
        cubeCards.add(new DraftCube.CardIdentity("Treasure Mage", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tromokratis", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tropical Island", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tuktuk the Explorer", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tundra", ""));
        cubeCards.add(new DraftCube.CardIdentity("Twincast", ""));
        cubeCards.add(new DraftCube.CardIdentity("Tymaret, the Murder King", ""));
        cubeCards.add(new DraftCube.CardIdentity("Ugin's Insight", ""));
        cubeCards.add(new DraftCube.CardIdentity("Underground Sea", ""));
        cubeCards.add(new DraftCube.CardIdentity("Unstable Obelisk", ""));
        cubeCards.add(new DraftCube.CardIdentity("Urabrask the Hidden", ""));
        cubeCards.add(new DraftCube.CardIdentity("Urban Evolution", ""));
        cubeCards.add(new DraftCube.CardIdentity("Urza's Rage", ""));
        cubeCards.add(new DraftCube.CardIdentity("Utter End", ""));
        cubeCards.add(new DraftCube.CardIdentity("Utvara Hellkite", ""));
        cubeCards.add(new DraftCube.CardIdentity("Uyo, Silent Prophet", ""));
        cubeCards.add(new DraftCube.CardIdentity("Vanish into Memory", ""));
        cubeCards.add(new DraftCube.CardIdentity("Varolz, the Scar-Striped", ""));
        cubeCards.add(new DraftCube.CardIdentity("Vedalken Archmage", ""));
        cubeCards.add(new DraftCube.CardIdentity("Vedalken Orrery", ""));
        cubeCards.add(new DraftCube.CardIdentity("Vendetta", ""));
        cubeCards.add(new DraftCube.CardIdentity("Vendilion Clique", ""));
        cubeCards.add(new DraftCube.CardIdentity("Venser, Shaper Savant", ""));
        cubeCards.add(new DraftCube.CardIdentity("Verdeloth the Ancient", ""));
        cubeCards.add(new DraftCube.CardIdentity("Vish Kal, Blood Arbiter", ""));
        cubeCards.add(new DraftCube.CardIdentity("Voice of the Woods", ""));
        cubeCards.add(new DraftCube.CardIdentity("Volcanic Island", ""));
        cubeCards.add(new DraftCube.CardIdentity("Volley of Boulders", ""));
        cubeCards.add(new DraftCube.CardIdentity("Vorinclex, Voice of Hunger", ""));
        cubeCards.add(new DraftCube.CardIdentity("Wall of Omens", ""));
        cubeCards.add(new DraftCube.CardIdentity("Warleader's Helix", ""));
        cubeCards.add(new DraftCube.CardIdentity("Warstorm Surge", ""));
        cubeCards.add(new DraftCube.CardIdentity("Watery Grave", ""));
        cubeCards.add(new DraftCube.CardIdentity("Wayfarer's Bauble", ""));
        cubeCards.add(new DraftCube.CardIdentity("Wear // Tear", ""));
        cubeCards.add(new DraftCube.CardIdentity("Where Ancients Tread", ""));
        cubeCards.add(new DraftCube.CardIdentity("Wild Ricochet", ""));
        cubeCards.add(new DraftCube.CardIdentity("Wood Elves", ""));
        cubeCards.add(new DraftCube.CardIdentity("Woodland Cemetery", ""));
        cubeCards.add(new DraftCube.CardIdentity("Word of Seizing", ""));
        cubeCards.add(new DraftCube.CardIdentity("Wort, the Raidmother", ""));
        cubeCards.add(new DraftCube.CardIdentity("Wrexial, the Risen Deep", ""));
        cubeCards.add(new DraftCube.CardIdentity("Xiahou Dun, the One-Eyed", ""));
        cubeCards.add(new DraftCube.CardIdentity("Yawgmoth's Agenda", ""));
        cubeCards.add(new DraftCube.CardIdentity("Yeva, Nature's Herald", ""));
        cubeCards.add(new DraftCube.CardIdentity("Yosei, the Morning Star", ""));
        cubeCards.add(new DraftCube.CardIdentity("Zendikar Resurgent", ""));
        cubeCards.add(new DraftCube.CardIdentity("Zirilan of the Claw", ""));
        cubeCards.add(new DraftCube.CardIdentity("Zur the Enchanter", ""));
        cubeCards.add(new DraftCube.CardIdentity("Zurgo Bellstriker", ""));
        cubeCards.add(new DraftCube.CardIdentity("Zurgo Helmsmasher", ""));
    }
}
