package mage.player.ai.scoring;

public enum AiScoreModuleId {
    DECK_STRATEGY,
    FFA_TABLE_THREAT,
    FFA_TARGET_PRIORITY,
    TARGET_QUALITY,
    COMBAT_PRESSURE,
    DEFENSE_RESERVE,
    COMMANDER_LIFECYCLE,
    PHASE_STRATEGY,
    GAME_STAGE,
    BOARD_ROLE,
    THREAT_PROJECTION,
    RESOURCE_DEVELOPMENT,
    COLOR_ACCESS,
    HAND_PLAN,
    HAND_QUALITY,
    INTERACTION_TIMING,
    SACRIFICE_AND_COST,
    SEARCH_AND_TUTOR,
    TOKEN_SWARM,
    COMBO_PROGRESS,
    OVERKILL_AND_WIN_CLOSURE,
    POLITICAL_MEMORY,
    ALTERNATE_LOSS_PRESSURE
}
