

/*
 * ManaPool.java
 *
 * Created on Dec 22, 2009, 9:52:00 AM
 */

package mage.client.game;

import mage.view.ManaPoolView;

/**
 *
 * @author BetaSteward_at_googlemail.com
 */
public class ManaPool extends javax.swing.JPanel {

    /** Creates new form ManaPool */
    public ManaPool() {
        initComponents();
    }

    public void update(ManaPoolView pool) {
        this.btnBlack.setText(Integer.toString(pool.getBlack()));
        this.btnRed.setText(Integer.toString(pool.getRed()));
        this.btnWhite.setText(Integer.toString(pool.getWhite()));
        this.btnGreen.setText(Integer.toString(pool.getGreen()));
        this.btnBlue.setText(Integer.toString(pool.getBlue()));
        this.btnColorless.setText(Integer.toString(pool.getColorless()));
    } 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBlack = new javax.swing.JLabel();
        btnBlack = new javax.swing.JButton();
        btnBlue = new javax.swing.JButton();
        lblBlue = new javax.swing.JLabel();
        lblGreen = new javax.swing.JLabel();
        btnGreen = new javax.swing.JButton();
        btnColorless = new javax.swing.JButton();
        lblWhite = new javax.swing.JLabel();
        lblColorless = new javax.swing.JLabel();
        btnWhite = new javax.swing.JButton();
        btnRed = new javax.swing.JButton();
        lblRed = new javax.swing.JLabel();

        lblBlack.setLabelFor(btnBlack);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("SwingMessage"); // NOI18N
        lblBlack.setText(bundle.getString("ManaPool.lblBlack.text")); // NOI18N

        btnBlack.setText(bundle.getString("ManaPool.btnBlack.text")); // NOI18N

        btnBlue.setText(bundle.getString("ManaPool.btnBlue.text")); // NOI18N

        lblBlue.setLabelFor(btnBlack);
        lblBlue.setText(bundle.getString("ManaPool.lblBlue.text")); // NOI18N

        lblGreen.setLabelFor(btnBlack);
        lblGreen.setText(bundle.getString("ManaPool.lblGreen.text")); // NOI18N

        btnGreen.setText(bundle.getString("ManaPool.btnGreen.text")); // NOI18N

        btnColorless.setText(bundle.getString("ManaPool.btnColorless.text")); // NOI18N

        lblWhite.setLabelFor(btnBlack);
        lblWhite.setText(bundle.getString("ManaPool.lblWhite.text")); // NOI18N

        lblColorless.setLabelFor(btnBlack);
        lblColorless.setText(bundle.getString("ManaPool.lblColorless.text")); // NOI18N

        btnWhite.setText(bundle.getString("ManaPool.btnWhite.text")); // NOI18N

        btnRed.setText(bundle.getString("ManaPool.btnRed.text")); // NOI18N

        lblRed.setLabelFor(btnBlack);
        lblRed.setText(bundle.getString("ManaPool.lblRed.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGreen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblColorless)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE)
                        .addComponent(btnColorless, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWhite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnWhite, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRed, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBlack)
                            .addComponent(lblBlue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlack)
                    .addComponent(btnBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBlue))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGreen)
                    .addComponent(btnGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRed)
                    .addComponent(btnRed, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWhite)
                    .addComponent(btnWhite, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColorless)
                    .addComponent(btnColorless, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlack;
    private javax.swing.JButton btnBlue;
    private javax.swing.JButton btnColorless;
    private javax.swing.JButton btnGreen;
    private javax.swing.JButton btnRed;
    private javax.swing.JButton btnWhite;
    private javax.swing.JLabel lblBlack;
    private javax.swing.JLabel lblBlue;
    private javax.swing.JLabel lblColorless;
    private javax.swing.JLabel lblGreen;
    private javax.swing.JLabel lblRed;
    private javax.swing.JLabel lblWhite;
    // End of variables declaration//GEN-END:variables

}
