name: "Pull Request Labeler (auto)"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: label-the-PR
        uses: actions/labeler@v5
        with:
          configuration-path: '.github/labeler.yml'