name: "Pull Request Labeler (manual)"
on:
  workflow_dispatch:
    inputs:
      oldPRs:
        # no multi lines support, so call by single PR only
        description: 'PR number to process'
        required: true
        type: string
        default: '123'

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: label-the-PR
        uses: actions/labeler@v5
        with:
          configuration-path: '.github/labeler.yml'
          pr-number: |
            ${{ github.event.inputs.oldPRs }}